// Leerpad: Inhoudsmaten — liters omrekenen (groep 6-8, Doorstroomtoets)
// 4 stappen: liter/dl/cl/ml, kubieke maten, omrekenen, toepassingen.

const chapters = [
  { letter: "A", title: "Liter, deciliter, centiliter, milliliter", emoji: "🥛", from: 0, to: 0 },
  { letter: "B", title: "Kubieke maten (cm³, dm³, m³)", emoji: "📦", from: 1, to: 1 },
  { letter: "C", title: "Omrekenen tussen maten", emoji: "🔄", from: 2, to: 2 },
  { letter: "D", title: "Doorstroomtoets-opgaven", emoji: "🏆", from: 3, to: 3 },
];

const steps = [
  {
    title: "Liter, deciliter, centiliter, milliliter",
    explanation: "**Inhoudsmaten** zeggen hoeveel er in iets past (vloeistof, korrels, lucht).\n\n**De eenheden (van groot naar klein)**:\n• 1 liter (L) = 10 deciliter (dl)\n• 1 deciliter = 10 centiliter (cl)\n• 1 centiliter = 10 milliliter (ml)\n\n**Dus**: 1 liter = 10 dl = 100 cl = 1000 ml.\n\n**Herkennen in het dagelijks leven**:\n• Pak melk = 1 liter\n• Glas water = ongeveer 2 dl (200 ml)\n• Blikje frisdrank = 33 cl (330 ml)\n• Druppel = ongeveer 0,05 ml\n• Emmer = 10 liter\n• Badkuip = 150-200 liter\n\n**Voorvoegsels onthouden**:\n• **deci** = tiende (1 dl = 1/10 liter)\n• **centi** = honderdste (1 cl = 1/100 liter)\n• **milli** = duizendste (1 ml = 1/1000 liter)\n\n**Trap van inhoudsmaten** (elke stap ×10):\n```\nL → dl → cl → ml\n  ×10  ×10  ×10\n```\nNaar rechts = ×10. Naar links = ÷10.\n\n**Cito-tip**: Tel het aantal stappen op de trap. Elke stap = ×10 of ÷10.",
    checks: [
      {
        q: "Hoeveel **milliliter** zit er in 1 liter?",
        options: ["1000 ml", "100 ml", "10 ml", "10.000 ml"],
        answer: 0,
        wrongHints: [null, "Dat is 1 deciliter in milliliters.", "Dat is 1 centiliter in milliliters.", "Dat is 10 liter in milliliters."],
        uitlegPad: {
          stappen: [{ titel: "Trap aftellen", tekst: "L → dl (×10) → cl (×10) → ml (×10). Totaal: 10 × 10 × 10 = 1000." }],
          woorden: [{ woord: "milli", uitleg: "'Milli' = duizendste. 1 ml = 1/1000 liter. Dus 1 liter = 1000 ml." }],
          theorie: "3 stappen op de trap: ×10 × 10 × 10 = ×1000.",
          voorbeelden: [{ type: "dagelijks", tekst: "1 pak melk = 1 liter = 1000 ml." }],
          basiskennis: [{ onderwerp: "Voorvoegsel milli", uitleg: "Milli = duizendste. Zoals millimeter = duizendste meter." }],
          niveaus: { basis: "1 L = 1000 ml. A.", simpeler: "L→dl→cl→ml: 3 stappen × 10 = 1000. Dus 1000 ml. = A.", nogSimpeler: "1000 ml = A." },
        },
      },
      {
        q: "Een blikje frisdrank bevat 33 cl. Hoeveel **ml** is dat?",
        options: ["330 ml", "33 ml", "3300 ml", "3,3 ml"],
        answer: 0,
        wrongHints: [null, "cl en ml zijn niet hetzelfde eenheid.", "Dat is 33 dl in ml.", "Je deelt terwijl je moet vermenigvuldigen."],
        uitlegPad: {
          stappen: [{ titel: "cl → ml = ×10", tekst: "Eén stap op de trap naar rechts: cl → ml = ×10. Dus 33 × 10 = 330 ml." }],
          woorden: [{ woord: "centiliter", uitleg: "1 cl = 10 ml. 'Centi' = honderdste (van een liter)." }],
          theorie: "cl naar ml = 1 stap rechts op de trap = ×10.",
          voorbeelden: [{ type: "dagelijks", tekst: "33 cl blikje = 330 ml. Een glas van 2 dl = 200 ml." }],
          basiskennis: [{ onderwerp: "Richting op de trap", uitleg: "Naar kleinere eenheid (rechts) = vermenigvuldigen. Naar grotere (links) = delen." }],
          niveaus: { basis: "33 × 10 = 330 ml. A.", simpeler: "cl → ml = ×10. 33 × 10 = 330. = A.", nogSimpeler: "330 ml = A." },
        },
      },
      {
        q: "Hoeveel **deciliter** zit er in een halve liter?",
        options: ["5 dl", "50 dl", "0,5 dl", "500 dl"],
        answer: 0,
        wrongHints: [null, "Dat is een halve liter in cl.", "Dat is een halve ml, niet dl.", "Veel te veel — dat is 50 liter in dl."],
        uitlegPad: {
          stappen: [{ titel: "1 L = 10 dl", tekst: "1 liter = 10 dl. Een halve liter = 10 ÷ 2 = 5 dl." }],
          woorden: [{ woord: "deciliter", uitleg: "'Deci' = tiende. 1 dl = 1/10 liter. Dus 10 dl = 1 liter." }],
          theorie: "Half = ÷ 2. 10 dl ÷ 2 = 5 dl.",
          voorbeelden: [{ type: "dagelijks", tekst: "Een halfliters-fles water = 5 dl = 500 ml." }],
          basiskennis: [{ onderwerp: "Deci", uitleg: "Deci = tiende. Zoals decimeter = tiende meter." }],
          niveaus: { basis: "½ L = 5 dl. A.", simpeler: "1 L = 10 dl. Halve liter = 10 ÷ 2 = 5 dl. = A.", nogSimpeler: "5 dl = A." },
        },
      },
      {
        q: "3500 ml = hoeveel **liter**?",
        options: ["3,5 liter", "35 liter", "0,35 liter", "350 liter"],
        answer: 0,
        wrongHints: [null, "Dat is 3500 cl in liters.", "Dat is te weinig — 350 ml = 0,35 L.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "ml → L = ÷1000", tekst: "3 stappen op de trap naar links: ml → cl → dl → L = ÷1000. 3500 ÷ 1000 = 3,5." }],
          woorden: [{ woord: "komma verplaatsen", uitleg: "÷1000 = komma 3 plaatsen naar links. 3500 → 3,500 → 3,5." }],
          theorie: "Van kleine naar grote eenheid = delen. 3 stappen = ÷1000.",
          voorbeelden: [{ type: "praktijk", tekst: "3 pakken melk + een half pak = 3,5 liter = 3500 ml." }],
          basiskennis: [{ onderwerp: "Komma-truc", uitleg: "÷10 = komma 1 plek links. ÷100 = 2 plekken. ÷1000 = 3 plekken." }],
          niveaus: { basis: "3500 ÷ 1000 = 3,5 L. A.", simpeler: "ml→L = ÷1000. 3500 ÷ 1000 = 3,5 liter. = A.", nogSimpeler: "3,5 liter = A." },
        },
      },
      {
        q: "Wat is **meer**: 75 cl of 8 dl?",
        options: ["8 dl (= 800 ml)", "75 cl (= 750 ml)", "Ze zijn gelijk", "Kun je niet vergelijken"],
        answer: 0,
        wrongHints: [null, "Reken beide om naar ml om te vergelijken.", "Nee, ze verschillen 50 ml.", "Jawel — reken om naar dezelfde eenheid."],
        uitlegPad: {
          stappen: [{ titel: "Naar dezelfde eenheid", tekst: "75 cl = 750 ml. 8 dl = 800 ml. 800 > 750 → 8 dl is meer." }],
          woorden: [{ woord: "vergelijken", uitleg: "Om te vergelijken: reken beide om naar dezelfde eenheid (bv. ml)." }],
          theorie: "75 cl × 10 = 750 ml. 8 dl × 100 = 800 ml. 800 > 750.",
          voorbeelden: [{ type: "stappen", tekst: "75 cl → 750 ml. 8 dl → 800 ml. 800 > 750 → 8 dl is meer." }],
          basiskennis: [{ onderwerp: "Altijd eerst omrekenen", uitleg: "Je kunt cl en dl niet direct vergelijken. Reken om naar dezelfde eenheid." }],
          niveaus: { basis: "8 dl = 800 ml > 75 cl = 750 ml. A.", simpeler: "75 cl = 750 ml, 8 dl = 800 ml. 800 > 750. = A.", nogSimpeler: "8 dl is meer = A." },
        },
      },
    ],
  },

  {
    title: "Kubieke maten — cm³, dm³, m³",
    explanation: "**Kubieke maten** meten de inhoud van een ruimtelijke vorm (kubus, balk, cilinder).\n\n**De eenheden**:\n• cm³ (kubieke centimeter) — zo groot als een suikerklontje\n• dm³ (kubieke decimeter) — zo groot als een melkpak\n• m³ (kubieke meter) — zo groot als een wasmachine\n\n**Omrekenen kubieke maten**:\n• 1 dm³ = 1000 cm³ (10 × 10 × 10)\n• 1 m³ = 1000 dm³ (10 × 10 × 10)\n• 1 m³ = 1.000.000 cm³\n\n**De gouden regel — kubiek ↔ liter**:\n• **1 dm³ = 1 liter** ← dit moet je ONTHOUDEN!\n• 1 cm³ = 1 ml\n• 1 m³ = 1000 liter\n\n**Waarom ×1000 ipv ×10?**\nBij lengtematen: 1 dm = 10 cm (1 dimensie).\nBij kubieke maten: 10 × 10 × 10 = 1000 (3 dimensies).\n\n**Berekening inhoud**:\n• Balk: lengte × breedte × hoogte\n• Kubus: zijde × zijde × zijde (= zijde³)\n\n**Cito-tip**: Zorg dat alle maten in dezelfde eenheid staan voordat je vermenigvuldigt!",
    checks: [
      {
        q: "Hoeveel **cm³** is 1 dm³?",
        options: ["1000 cm³", "100 cm³", "10 cm³", "10.000 cm³"],
        answer: 0,
        wrongHints: [null, "Bij oppervlakte zou het 100 zijn (10×10). Maar kubiek = 3 dimensies.", "Dat is 1 dm in cm (lengte).", "Dat is dm² in cm² (oppervlakte), niet kubiek."],
        uitlegPad: {
          stappen: [{ titel: "3 dimensies", tekst: "1 dm = 10 cm. Kubiek: 10 × 10 × 10 = 1000 cm³." }],
          woorden: [{ woord: "kubiek", uitleg: "Kubiek (³) = 3 dimensies: lengte × breedte × hoogte." }],
          theorie: "Bij kubieke maten: elke stap op de trap = ×1000 (niet ×10 zoals bij lengte).",
          voorbeelden: [{ type: "visueel", tekst: "Een blokje van 10 × 10 × 10 cm = 1000 kleine blokjes van 1 cm³." }],
          basiskennis: [{ onderwerp: "Lengte vs kubiek", uitleg: "Lengte: ×10 per stap. Oppervlakte: ×100. Kubiek: ×1000." }],
          niveaus: { basis: "10 × 10 × 10 = 1000 cm³. A.", simpeler: "1 dm = 10 cm. Kubiek: 10³ = 1000. Dus 1000 cm³. = A.", nogSimpeler: "1000 cm³ = A." },
        },
      },
      {
        q: "**1 dm³ = ... liter.** Vul aan.",
        options: ["1 liter", "10 liter", "0,1 liter", "100 liter"],
        answer: 0,
        wrongHints: [null, "Dat is 10 dm³.", "Dat is 1 cm³ in dl, niet dm³ in liter.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "Gouden regel", tekst: "1 dm³ = 1 liter. Dit moet je gewoon onthouden!" }],
          woorden: [{ woord: "dm³ = liter", uitleg: "De kubieke decimeter en de liter zijn exact even groot." }],
          theorie: "1 dm³ = 1 L. Dus ook: 1 cm³ = 1 ml, en 1 m³ = 1000 L.",
          voorbeelden: [{ type: "dagelijks", tekst: "Een melkpak van 1 liter is een kubusje van 10 × 10 × 10 cm = 1 dm³." }],
          basiskennis: [{ onderwerp: "Bruggetje", uitleg: "dm³ = liter. cm³ = ml. m³ = 1000 liter. Onthoud de brug: dm³ ↔ L." }],
          niveaus: { basis: "1 dm³ = 1 liter. A.", simpeler: "De gouden regel: 1 dm³ = precies 1 liter. = A.", nogSimpeler: "1 liter = A." },
        },
      },
      {
        q: "Een aquarium is 50 cm lang, 30 cm breed en 40 cm hoog. Hoeveel **liter** water past erin?",
        options: ["60 liter", "120 liter", "6 liter", "600 liter"],
        answer: 0,
        wrongHints: [null, "Check je berekening — 50 × 30 × 40 = ?", "Vergeet niet: 1000 cm³ = 1 liter.", "Veel te veel — check de eenheden."],
        uitlegPad: {
          stappen: [{ titel: "L × B × H → cm³ → liter", tekst: "50 × 30 × 40 = 60.000 cm³. 60.000 ÷ 1000 = 60 liter." }],
          woorden: [{ woord: "inhoud berekenen", uitleg: "Inhoud balk = lengte × breedte × hoogte. Daarna omrekenen naar liter." }],
          theorie: "Stap 1: bereken in cm³. Stap 2: deel door 1000 (want 1000 cm³ = 1 L).",
          voorbeelden: [{ type: "stappen", tekst: "50 × 30 = 1500. 1500 × 40 = 60.000 cm³. 60.000 ÷ 1000 = 60 L." }],
          basiskennis: [{ onderwerp: "cm³ → liter", uitleg: "1000 cm³ = 1 dm³ = 1 liter. Dus cm³ ÷ 1000 = liter." }],
          niveaus: { basis: "50×30×40 = 60.000 cm³ = 60 L. A.", simpeler: "Inhoud = 60.000 cm³. ÷ 1000 = 60 liter. = A.", nogSimpeler: "60 liter = A." },
        },
      },
      {
        q: "Een zwembad bevat 50 m³ water. Hoeveel **liter** is dat?",
        options: ["50.000 liter", "5.000 liter", "500 liter", "500.000 liter"],
        answer: 0,
        wrongHints: [null, "1 m³ = 1000 liter, niet 100.", "Veel te weinig — 1 m³ alleen is al 1000 liter.", "Veel te veel — dat is 500 m³."],
        uitlegPad: {
          stappen: [{ titel: "m³ → liter = ×1000", tekst: "1 m³ = 1000 liter. 50 × 1000 = 50.000 liter." }],
          woorden: [{ woord: "m³", uitleg: "Kubieke meter. 1 m³ = 1000 dm³ = 1000 liter." }],
          theorie: "m³ → liter: ×1000. Of: m³ → dm³ → liter (dm³ = L, en 1 m³ = 1000 dm³).",
          voorbeelden: [{ type: "dagelijks", tekst: "Een standaard bad = ~0,2 m³ = 200 liter. Een klein zwembad = 50 m³ = 50.000 L." }],
          basiskennis: [{ onderwerp: "Schaal", uitleg: "m³ is erg groot: 1 m × 1 m × 1 m. Daar passen 1000 pakken melk in." }],
          niveaus: { basis: "50 × 1000 = 50.000 L. A.", simpeler: "1 m³ = 1000 L. 50 m³ = 50.000 L. = A.", nogSimpeler: "50.000 liter = A." },
        },
      },
      {
        q: "500 cm³ = hoeveel **dl**?",
        options: ["5 dl", "50 dl", "0,5 dl", "500 dl"],
        answer: 0,
        wrongHints: [null, "Reken eerst om naar ml, dan naar dl.", "Dat is te weinig (0,5 dl = 50 ml).", "Dat klopt niet — 500 cm³ is maar een halve liter."],
        uitlegPad: {
          stappen: [{ titel: "cm³ = ml, dan ml → dl", tekst: "500 cm³ = 500 ml. 500 ml ÷ 100 = 5 dl. (Want 1 dl = 100 ml.)" }],
          woorden: [{ woord: "twee stappen", uitleg: "Eerst cm³→ml (gouden regel), dan ml→dl (÷100)." }],
          theorie: "cm³ = ml (altijd). Dan ml naar dl: ÷ 100 (of 2 stappen op de trap links).",
          voorbeelden: [{ type: "stappen", tekst: "500 cm³ = 500 ml = 5 dl = 0,5 liter = een halve liter." }],
          basiskennis: [{ onderwerp: "Twee bruggen", uitleg: "Brug 1: cm³ = ml. Brug 2: ml → dl → L (trap)." }],
          niveaus: { basis: "500 ml ÷ 100 = 5 dl. A.", simpeler: "500 cm³ = 500 ml. 500 ml = 5 dl (÷100). = A.", nogSimpeler: "5 dl = A." },
        },
      },
    ],
  },

  {
    title: "Omrekenen — combinatie-opgaven",
    explanation: "Op de Doorstroomtoets moet je snel kunnen omrekenen tussen **liter-eenheden** en **kubieke maten**.\n\n**Samenvatting bruggen**:\n```\ncm³ = ml       ← gouden brug 1\ndm³ = liter    ← gouden brug 2\nm³ = 1000 L    ← gouden brug 3\n```\n\n**Trap van inhoudsmaten**:\n```\nm³ → dm³ → cm³\n ×1000  ×1000\n```\n\n**Trap van liters**:\n```\nL → dl → cl → ml\n ×10  ×10  ×10\n```\n\n**Strategie bij omrekenen**:\n1. Kijk naar de beginmaat en de eindmaat.\n2. Moet je via een brug (kubiek ↔ liter)? Gebruik die eerst.\n3. Reken daarna om op de juiste trap.\n\n**Veel-gemaakte fouten**:\n• cm³ → dm³ = ÷1000 (NIET ÷10!)\n• ml en cm³ door elkaar halen → ze zijn gelijk!\n• Bij kubieke maten ×1000 per stap, bij litermaten ×10 per stap.\n\n**Cito-tip**: Schrijf de bruggen op je kladblad:\ncm³=ml, dm³=L, m³=1000L. Dan gaat het sneller.",
    checks: [
      {
        q: "2,5 liter = hoeveel **ml**?",
        options: ["2500 ml", "250 ml", "25 ml", "25.000 ml"],
        answer: 0,
        wrongHints: [null, "Dat is 2,5 dl in ml.", "Dat is 2,5 cl in ml.", "Dat is 25 liter in ml."],
        uitlegPad: {
          stappen: [{ titel: "L → ml = ×1000", tekst: "Liter naar ml: 3 stappen op de trap = ×1000. 2,5 × 1000 = 2500." }],
          woorden: [{ woord: "komma verplaatsen", uitleg: "×1000 = komma 3 plaatsen naar rechts. 2,5 → 2500." }],
          theorie: "L → dl (×10) → cl (×10) → ml (×10) = ×1000 totaal.",
          voorbeelden: [{ type: "dagelijks", tekst: "2,5 liter cola-fles = 2500 ml." }],
          basiskennis: [{ onderwerp: "Komma-truc", uitleg: "×10 = komma 1 rechts. ×100 = 2. ×1000 = 3." }],
          niveaus: { basis: "2,5 × 1000 = 2500 ml. A.", simpeler: "L→ml: ×1000. 2,5 × 1000 = 2500. = A.", nogSimpeler: "2500 ml = A." },
        },
      },
      {
        q: "Een kubus heeft ribben van 20 cm. Hoeveel **liter** past erin?",
        options: ["8 liter", "80 liter", "0,8 liter", "800 liter"],
        answer: 0,
        wrongHints: [null, "Check: 20 × 20 × 20 = ? En dan cm³ naar liter.", "Dat is te weinig — 800 cm³ = 0,8 L, maar de inhoud is groter.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "20³ cm³ → liter", tekst: "20 × 20 × 20 = 8000 cm³. 8000 cm³ = 8000 ml = 8 liter." }],
          woorden: [{ woord: "kubus-inhoud", uitleg: "Kubus = alle zijden gelijk. Inhoud = zijde × zijde × zijde = zijde³." }],
          theorie: "Stap 1: 20³ = 8000 cm³. Stap 2: cm³ = ml, dus 8000 ml. Stap 3: ÷1000 = 8 L.",
          voorbeelden: [{ type: "stappen", tekst: "20 × 20 = 400. 400 × 20 = 8000 cm³ = 8000 ml = 8 liter." }],
          basiskennis: [{ onderwerp: "cm³ = ml", uitleg: "De gouden brug: 1 cm³ = 1 ml. Dus 8000 cm³ = 8000 ml = 8 L." }],
          niveaus: { basis: "20³ = 8000 cm³ = 8 L. A.", simpeler: "20×20×20 = 8000 cm³ = 8000 ml = 8 liter. = A.", nogSimpeler: "8 liter = A." },
        },
      },
      {
        q: "0,75 liter = hoeveel **cl**?",
        options: ["75 cl", "7,5 cl", "750 cl", "0,75 cl"],
        answer: 0,
        wrongHints: [null, "Dat is 0,75 liter in dl.", "Dat is 0,75 liter in ml.", "Je deelt terwijl je moet vermenigvuldigen."],
        uitlegPad: {
          stappen: [{ titel: "L → cl = ×100", tekst: "Liter naar cl: 2 stappen op de trap = ×100. 0,75 × 100 = 75." }],
          woorden: [{ woord: "centiliter", uitleg: "Centi = honderdste. 1 L = 100 cl. Dus ×100." }],
          theorie: "L → dl (×10) → cl (×10) = ×100 totaal.",
          voorbeelden: [{ type: "dagelijks", tekst: "Een wijnfles = 0,75 L = 75 cl. Staat ook op het etiket!" }],
          basiskennis: [{ onderwerp: "Wijnfles-ezelsbruggetje", uitleg: "Een standaard wijnfles = 75 cl = 750 ml = 0,75 L." }],
          niveaus: { basis: "0,75 × 100 = 75 cl. A.", simpeler: "L→cl: ×100. 0,75 × 100 = 75. = A.", nogSimpeler: "75 cl = A." },
        },
      },
      {
        q: "4500 cm³ = hoeveel **dm³**?",
        options: ["4,5 dm³", "45 dm³", "0,45 dm³", "450 dm³"],
        answer: 0,
        wrongHints: [null, "Bij kubieke maten: elke stap = ×1000, niet ×100.", "Dat is te weinig.", "Dat is te veel."],
        uitlegPad: {
          stappen: [{ titel: "cm³ → dm³ = ÷1000", tekst: "1 stap op de kubieke trap naar links: ÷1000. 4500 ÷ 1000 = 4,5." }],
          woorden: [{ woord: "kubieke trap", uitleg: "Bij kubieke maten: elke stap = ×1000 of ÷1000 (niet ×10!)." }],
          theorie: "cm³ → dm³ = ÷1000. Want 1 dm = 10 cm, en kubiek: 10³ = 1000.",
          voorbeelden: [{ type: "check", tekst: "4,5 dm³ = 4,5 liter (want dm³ = L). Past bij 4500 ml = 4500 cm³. ✓" }],
          basiskennis: [{ onderwerp: "×1000 niet ×10", uitleg: "VEELGEMAAKTE FOUT: ÷10 ipv ÷1000. Bij kubiek altijd ×1000 per stap!" }],
          niveaus: { basis: "4500 ÷ 1000 = 4,5 dm³. A.", simpeler: "cm³→dm³: ÷1000. 4500 ÷ 1000 = 4,5. = A.", nogSimpeler: "4,5 dm³ = A." },
        },
      },
      {
        q: "Een emmer van 12 liter. Hoeveel **cm³** is dat?",
        options: ["12.000 cm³", "1.200 cm³", "120 cm³", "120.000 cm³"],
        answer: 0,
        wrongHints: [null, "1 liter = 1000 ml = 1000 cm³, niet 100.", "Veel te weinig.", "Dat is 120 liter in cm³."],
        uitlegPad: {
          stappen: [{ titel: "L → cm³ via brug", tekst: "12 L = 12 dm³ (brug). 12 dm³ × 1000 = 12.000 cm³." }],
          woorden: [{ woord: "twee bruggen", uitleg: "L = dm³ (brug 1). dm³ → cm³ = ×1000 (brug 2)." }],
          theorie: "Of sneller: 1 L = 1000 ml = 1000 cm³. Dus 12 × 1000 = 12.000.",
          voorbeelden: [{ type: "stappen", tekst: "12 L = 12.000 ml = 12.000 cm³." }],
          basiskennis: [{ onderwerp: "L → cm³ shortcut", uitleg: "Liter → cm³ = altijd ×1000. Want L = dm³, en dm³ = 1000 cm³." }],
          niveaus: { basis: "12 × 1000 = 12.000 cm³. A.", simpeler: "1 L = 1000 cm³. 12 L = 12.000 cm³. = A.", nogSimpeler: "12.000 cm³ = A." },
        },
      },
    ],
  },

  {
    title: "Doorstroomtoets-opgaven — inhoudsmaten in context",
    explanation: "Op de Doorstroomtoets komen inhoudsmaten voor in **praktijkopgaven**: koken, aquarium vullen, zwembad, medicijnen, etc.\n\n**Veelvoorkomende vraagtypen**:\n1. Omrekenen: '500 ml = ... dl?'\n2. Inhoud berekenen: 'Hoeveel liter past in een bak van 40 × 25 × 30 cm?'\n3. Vergelijken: 'Welke verpakking is voordeliger?'\n4. Praktisch: 'Hoeveel glazen van 2 dl kun je vullen uit een fles van 1,5 liter?'\n\n**Tips voor de toets**:\n• Schrijf altijd de eenheid achter je antwoord.\n• Bij 'hoeveel glazen/bekers': deel de totale hoeveelheid door de inhoud van 1 glas.\n• Bij 'voordeliger': reken om naar prijs per liter.\n• Teken een trapje als je het omrekenen lastig vindt.\n\n**Veelgemaakte fouten**:\n• Vergeten om te rekenen (antwoord in cm³ terwijl er liter gevraagd wordt).\n• cm³ → dm³ als ÷10 doen ipv ÷1000.\n• ml en cl door elkaar halen (1 cl = 10 ml, niet 1 ml!).",
    checks: [
      {
        q: "Een pan heeft een inhoud van 3 liter. Je giet er 1,8 liter soep in. Hoeveel **ml** kun je er nog bij?",
        options: ["1200 ml", "1800 ml", "120 ml", "12.000 ml"],
        answer: 0,
        wrongHints: [null, "Dat is hoeveel soep er IN de pan zit, niet hoeveel er nog bij kan.", "Dat is te weinig — het verschil is meer dan 1 dl.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "Verschil × 1000", tekst: "3 - 1,8 = 1,2 liter over. 1,2 × 1000 = 1200 ml." }],
          woorden: [{ woord: "restcapaciteit", uitleg: "Totale inhoud minus wat erin zit = hoeveel er nog bij kan." }],
          theorie: "Stap 1: 3 L - 1,8 L = 1,2 L. Stap 2: 1,2 L = 1200 ml.",
          voorbeelden: [{ type: "dagelijks", tekst: "3-literspan met 1,8 L soep: nog 1,2 L = 1200 ml ruimte over." }],
          basiskennis: [{ onderwerp: "Aftrekken + omrekenen", uitleg: "Twee stappen: eerst aftrekken (in liters), dan omrekenen naar gevraagde eenheid." }],
          niveaus: { basis: "3 - 1,8 = 1,2 L = 1200 ml. A.", simpeler: "Over: 3 - 1,8 = 1,2 L. In ml: 1,2 × 1000 = 1200. = A.", nogSimpeler: "1200 ml = A." },
        },
      },
      {
        q: "Je vult 8 glazen van 25 cl. Hoeveel **liter** is dat in totaal?",
        options: ["2 liter", "20 liter", "0,2 liter", "200 liter"],
        answer: 0,
        wrongHints: [null, "8 × 25 = 200 cl. Reken dat om naar liter.", "Dat is te weinig — 8 glazen is meer dan 1 glas.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "8 × 25 cl → liter", tekst: "8 × 25 = 200 cl. 200 cl ÷ 100 = 2 liter." }],
          woorden: [{ woord: "totaal berekenen", uitleg: "Aantal × inhoud per stuk = totale inhoud." }],
          theorie: "Stap 1: 8 × 25 = 200 cl. Stap 2: cl → L = ÷100. 200 ÷ 100 = 2.",
          voorbeelden: [{ type: "dagelijks", tekst: "8 glazen van 25 cl = 2 liter. Dat is 2 pakken melk." }],
          basiskennis: [{ onderwerp: "Vermenigvuldigen + omrekenen", uitleg: "Eerst vermenigvuldigen, dan omrekenen. Of andersom (25 cl = 0,25 L, × 8 = 2 L)." }],
          niveaus: { basis: "8 × 25 = 200 cl = 2 L. A.", simpeler: "200 cl ÷ 100 = 2 liter. = A.", nogSimpeler: "2 liter = A." },
        },
      },
      {
        q: "Een bak is 30 cm lang, 20 cm breed en 15 cm hoog. Past er **meer of minder** dan 10 liter in?",
        options: ["Minder (9 liter)", "Meer (90 liter)", "Precies 10 liter", "Meer (10,5 liter)"],
        answer: 0,
        wrongHints: [null, "Check je berekening: 30 × 20 × 15 = ?", "Niet precies — reken uit.", "Dat klopt niet helemaal — reken stap voor stap."],
        uitlegPad: {
          stappen: [{ titel: "L × B × H = cm³ → liter", tekst: "30 × 20 × 15 = 9000 cm³ = 9000 ml = 9 liter. Dat is minder dan 10." }],
          woorden: [{ woord: "schatting vs berekening", uitleg: "De Doorstroomtoets vraagt soms 'meer of minder dan X'. Je moet uitrekenen." }],
          theorie: "30 × 20 = 600. 600 × 15 = 9000 cm³ = 9 L. 9 < 10 → minder.",
          voorbeelden: [{ type: "stappen", tekst: "30 × 20 × 15 = 9000 cm³ = 9 L < 10 L → minder." }],
          basiskennis: [{ onderwerp: "Slim rekenen", uitleg: "30 × 20 = 600 (makkelijk). 600 × 15 = 600 × 10 + 600 × 5 = 6000 + 3000 = 9000." }],
          niveaus: { basis: "9000 cm³ = 9 L < 10 L → minder. A.", simpeler: "30×20×15 = 9000 cm³ = 9 liter. Minder dan 10. = A.", nogSimpeler: "Minder (9 liter) = A." },
        },
      },
      {
        q: "Een fles water is 1,5 liter. Je schenkt 4 bekers van 3 dl vol. Hoeveel ml heb je **over**?",
        options: ["300 ml", "1200 ml", "30 ml", "0 ml"],
        answer: 0,
        wrongHints: [null, "Dat is hoeveel je geschonken hebt (4 × 3 dl), niet wat overblijft.", "Te weinig — het verschil is meer dan 1 cl.", "Er blijft wel iets over."],
        uitlegPad: {
          stappen: [{ titel: "Geschonken - totaal", tekst: "4 × 3 dl = 12 dl = 1200 ml. Fles = 1500 ml. Over: 1500 - 1200 = 300 ml." }],
          woorden: [{ woord: "restberekening", uitleg: "Totaal - gebruikt = rest. Zorg dat alles in dezelfde eenheid staat." }],
          theorie: "1,5 L = 1500 ml. 4 × 3 dl = 12 dl = 1200 ml. 1500 - 1200 = 300 ml.",
          voorbeelden: [{ type: "stappen", tekst: "Fles: 1500 ml. Geschonken: 1200 ml. Over: 300 ml = 3 dl = 0,3 L." }],
          basiskennis: [{ onderwerp: "Alles in ml", uitleg: "Reken alles om naar ml, dan aftrekken. Minder fouten." }],
          niveaus: { basis: "1500 - 1200 = 300 ml. A.", simpeler: "Fles = 1500 ml. Gebruikt = 1200 ml. Over = 300 ml. = A.", nogSimpeler: "300 ml = A." },
        },
      },
      {
        q: "Een medicijn-flesje bevat 100 ml. Je neemt 3× per dag 5 ml. Hoeveel **dagen** kun je ermee doen?",
        options: ["6 dagen (en dan rest je 10 ml)", "20 dagen", "7 dagen", "5 dagen"],
        answer: 0,
        wrongHints: [null, "100 ÷ 5 = 20 doses, niet dagen.", "Check: 7 × 15 = 105, meer dan 100.", "Check: 5 × 15 = 75, dat is niet 100."],
        uitlegPad: {
          stappen: [{ titel: "Per dag × doses", tekst: "Per dag: 3 × 5 = 15 ml. 100 ÷ 15 = 6,67 → 6 volledige dagen (6 × 15 = 90, rest 10 ml)." }],
          woorden: [{ woord: "dagdosis", uitleg: "Dagdosis = aantal keer per dag × hoeveelheid per keer." }],
          theorie: "3 × 5 = 15 ml/dag. 100 ÷ 15 = 6 rest 10. Dus 6 volledige dagen + 10 ml over.",
          voorbeelden: [{ type: "rekenen", tekst: "Dag 1: 15 ml (rest 85). Dag 2: 15 (70). Dag 3: 15 (55). Dag 4: 15 (40). Dag 5: 15 (25). Dag 6: 15 (10). Dag 7: niet genoeg (10 < 15)." }],
          basiskennis: [{ onderwerp: "Delen met rest", uitleg: "Bij 'hoeveel dagen' vraagt de Doorstroomtoets soms naar hele dagen. 6,67 → 6 dagen." }],
          niveaus: { basis: "100 ÷ 15 = 6 dagen (rest 10 ml). A.", simpeler: "Per dag 15 ml. Na 6 dagen: 90 ml op, 10 ml over. = A.", nogSimpeler: "6 dagen = A." },
        },
      },
    ],
  },
];

export default {
  id: "inhoudsmaten-po",
  title: "Inhoudsmaten — liters, ml, cm³ omrekenen (groep 6-8)",
  subject: "rekenen",
  level: "groep6-8",
  emoji: "🥛",
  referentieNiveau: "1F-1S",
  sloThema: "Rekenen — inhoudsmaten (liters + kubieke maten) Doorstroomtoets",
  triggerKeywords: [
    "inhoudsmaten",
    "liter",
    "milliliter",
    "deciliter",
    "centiliter",
    "kubieke centimeter",
    "cm3",
    "dm3",
    "m3",
    "omrekenen inhoud",
    "doorstroomtoets rekenen"
  ],
  intro: "Leer liters, deciliters, centiliters en milliliters omrekenen. Plus: kubieke maten (cm³, dm³, m³) en de gouden regel 1 dm³ = 1 liter. Alles wat je nodig hebt voor de Doorstroomtoets.",
  prerequisites: [
    { id: "kommagetallen-po", title: "Kommagetallen", niveau: "groep 6-8" },
    { id: "maten-omtrek-oppervlakte-po", title: "Maten + omtrek + oppervlakte", niveau: "groep 6-8" },
  ],
  chapters,
  steps,
};
