// 🌍 Vertalingen voor het plaatjesdictee voor nieuwkomers (NieuwkomersPlaatjesDictee.jsx).
// Gemaakt 29 sep 2026 voor het plaatjesdictee: de app zegt het woord in de thuistaal ("apple",
// "تفاحة", "яблуко", "elma") en het kind schrijft het Nederlandse woord bij het plaatje.
// Eén regel per woord uit WOORDKAARTEN en PICTO (nieuwkomersPicto.js), kleuren niet meegeteld.
//
// Herkomst: 56 woorden komen uit de nagekeken woordenboekjes van de lessen
// (woordenNieuwkomers.js, woorden2Nieuwkomers.js; "de wc" uit nieuwkomersSteun.js). Die zijn alleen
// ingekort tot een gesproken woord: Engels zonder "the"/"to", tekst tussen haakjes weg, bij "a / b"
// alleen het eerste woord (juf/meester: "female teacher"/"male teacher").
// De 134 andere woorden zijn NIEUW vertaald en staan in NAKIJKEN: die moeten nog worden
// nagekeken door iemand die de taal als moedertaal spreekt.
//
// Regels bij het vertalen: het gewone woord dat een kind van 6-10 kent, passend bij het PLAATJE
// (de bank = sofa, de motor = motorfiets, de wip = wipwap, rijden = autorijden, de boot = zeilboot);
// Engels zonder lidwoord; Arabisch (standaard) enkelvoud zonder ال (de overgenomen woorden houden
// ال zoals in de lessen); Oekraïens en Turks eerste naamval enkelvoud; doe-woorden als hele werkwoord (Engels kaal: "write"; Arabisch zoals in de
// lessen: يكتب; Oekraïens писати; Turks yazmak).

export const VERTALINGEN = {
  // In de klas
  "de tafel": { en: "table", ar: "الطاولة", uk: "стіл", tr: "masa" },
  "de stoel": { en: "chair", ar: "الكرسي", uk: "стілець", tr: "sandalye" },
  "de deur": { en: "door", ar: "الباب", uk: "двері", tr: "kapı" },
  "het raam": { en: "window", ar: "النافذة", uk: "вікно", tr: "pencere" },
  "het bord": { en: "board", ar: "السبّورة", uk: "дошка", tr: "tahta" },
  "de tas": { en: "bag", ar: "الحقيبة", uk: "сумка", tr: "çanta" },
  "de pen": { en: "pen", ar: "القلم", uk: "ручка", tr: "kalem" },
  "de schaar": { en: "scissors", ar: "مقص", uk: "ножиці", tr: "makas" },
  "de lijm": { en: "glue", ar: "صمغ", uk: "клей", tr: "yapıştırıcı" },
  "het papier": { en: "paper", ar: "ورق", uk: "папір", tr: "kâğıt" },
  "het schrift": { en: "notebook", ar: "دفتر", uk: "зошит", tr: "defter" },
  "het boek": { en: "book", ar: "الكتاب", uk: "книжка", tr: "kitap" },
  "de kwast": { en: "paintbrush", ar: "فرشاة", uk: "пензлик", tr: "fırça" },
  "het etui": { en: "pencil case", ar: "مقلمة", uk: "пенал", tr: "kalemlik" },
  "de computer": { en: "computer", ar: "حاسوب", uk: "комп’ютер", tr: "bilgisayar" },
  "de klok": { en: "clock", ar: "ساعة", uk: "годинник", tr: "saat" },
  "de juf": { en: "female teacher", ar: "المعلّمة", uk: "вчителька", tr: "kadın öğretmen" },
  "de meester": { en: "male teacher", ar: "المعلّم", uk: "вчитель", tr: "erkek öğretmen" },
  "de wc": { en: "toilet", ar: "الحمام", uk: "туалет", tr: "tuvalet" },
  // Eten en drinken
  "de melk": { en: "milk", ar: "الحليب", uk: "молоко", tr: "süt" },
  "het water": { en: "water", ar: "الماء", uk: "вода", tr: "su" },
  "het brood": { en: "bread", ar: "الخبز", uk: "хліб", tr: "ekmek" },
  "de kaas": { en: "cheese", ar: "الجبن", uk: "сир", tr: "peynir" },
  "het ei": { en: "egg", ar: "البيضة", uk: "яйце", tr: "yumurta" },
  "de rijst": { en: "rice", ar: "الأرز", uk: "рис", tr: "pirinç" },
  "de soep": { en: "soup", ar: "الحساء", uk: "суп", tr: "çorba" },
  "de thee": { en: "tea", ar: "الشاي", uk: "чай", tr: "çay" },
  "de boterham": { en: "sandwich", ar: "شطيرة", uk: "бутерброд", tr: "sandviç" },
  "de pizza": { en: "pizza", ar: "بيتزا", uk: "піца", tr: "pizza" },
  "het koekje": { en: "cookie", ar: "بسكويت", uk: "печиво", tr: "bisküvi" },
  "de taart": { en: "cake", ar: "كعكة", uk: "торт", tr: "pasta" },
  "het ijsje": { en: "ice cream", ar: "آيس كريم", uk: "морозиво", tr: "dondurma" },
  "de chocola": { en: "chocolate", ar: "شوكولاتة", uk: "шоколад", tr: "çikolata" },
  "de patat": { en: "fries", ar: "بطاطا مقلية", uk: "картопля фрі", tr: "patates kızartması" },
  "de lepel": { en: "spoon", ar: "ملعقة", uk: "ложка", tr: "kaşık" },
  "de vork": { en: "fork", ar: "شوكة", uk: "виделка", tr: "çatal" },
  "het mes": { en: "knife", ar: "سكين", uk: "ніж", tr: "bıçak" },
  "de beker": { en: "cup", ar: "كوب", uk: "чашка", tr: "bardak" },
  // Fruit en groente
  "de appel": { en: "apple", ar: "التفاحة", uk: "яблуко", tr: "elma" },
  "de banaan": { en: "banana", ar: "الموزة", uk: "банан", tr: "muz" },
  "de sinaasappel": { en: "orange", ar: "برتقالة", uk: "апельсин", tr: "portakal" },
  "de peer": { en: "pear", ar: "كمثرى", uk: "груша", tr: "armut" },
  "de druif": { en: "grape", ar: "عنب", uk: "виноград", tr: "üzüm" },
  "de aardbei": { en: "strawberry", ar: "فراولة", uk: "полуниця", tr: "çilek" },
  "de citroen": { en: "lemon", ar: "ليمون", uk: "лимон", tr: "limon" },
  "de kers": { en: "cherry", ar: "كرز", uk: "вишня", tr: "kiraz" },
  "de ananas": { en: "pineapple", ar: "أناناس", uk: "ананас", tr: "ananas" },
  "de wortel": { en: "carrot", ar: "جزرة", uk: "морква", tr: "havuç" },
  "de tomaat": { en: "tomato", ar: "طماطم", uk: "помідор", tr: "domates" },
  "de komkommer": { en: "cucumber", ar: "خيار", uk: "огірок", tr: "salatalık" },
  // Mijn lichaam
  "het hoofd": { en: "head", ar: "الرأس", uk: "голова", tr: "baş" },
  "het oog": { en: "eye", ar: "العين", uk: "око", tr: "göz" },
  "het oor": { en: "ear", ar: "الأذن", uk: "вухо", tr: "kulak" },
  "de mond": { en: "mouth", ar: "الفم", uk: "рот", tr: "ağız" },
  "de tong": { en: "tongue", ar: "لسان", uk: "язик", tr: "dil" },
  "de buik": { en: "belly", ar: "البطن", uk: "живіт", tr: "karın" },
  "de arm": { en: "arm", ar: "الذراع", uk: "рука", tr: "kol" },
  "de hand": { en: "hand", ar: "اليد", uk: "рука", tr: "el" },
  "de voet": { en: "foot", ar: "القدم", uk: "стопа", tr: "ayak" },
  // Kleding
  "de jas": { en: "coat", ar: "المعطف", uk: "куртка", tr: "mont" },
  "de broek": { en: "trousers", ar: "البنطال", uk: "штани", tr: "pantolon" },
  "het T-shirt": { en: "T-shirt", ar: "تي شيرت", uk: "футболка", tr: "tişört" },
  "de trui": { en: "jumper", ar: "الكنزة", uk: "светр", tr: "kazak" },
  "de jurk": { en: "dress", ar: "فستان", uk: "сукня", tr: "elbise" },
  "de rok": { en: "skirt", ar: "تنورة", uk: "спідниця", tr: "etek" },
  "de korte broek": { en: "shorts", ar: "شورت", uk: "шорти", tr: "şort" },
  "de onderbroek": { en: "underpants", ar: "سروال داخلي", uk: "труси", tr: "külot" },
  "de sok": { en: "sock", ar: "الجورب", uk: "шкарпетка", tr: "çorap" },
  "de schoen": { en: "shoe", ar: "الحذاء", uk: "черевик", tr: "ayakkabı" },
  "de laars": { en: "boot", ar: "جزمة", uk: "чобіт", tr: "çizme" },
  "de muts": { en: "woolly hat", ar: "القبعة الصوفية", uk: "шапка", tr: "bere" },
  "de pet": { en: "cap", ar: "قبعة", uk: "кепка", tr: "şapka" },
  "de sjaal": { en: "scarf", ar: "وشاح", uk: "шарф", tr: "atkı" },
  "de handschoen": { en: "glove", ar: "قفاز", uk: "рукавичка", tr: "eldiven" },
  // Thuis
  "het huis": { en: "house", ar: "البيت", uk: "будинок", tr: "ev" },
  "de tuin": { en: "garden", ar: "الحديقة", uk: "сад", tr: "bahçe" },
  "het gezin": { en: "family", ar: "عائلة", uk: "сім’я", tr: "aile" },
  "de baby": { en: "baby", ar: "رضيع", uk: "немовля", tr: "bebek" },
  "het bed": { en: "bed", ar: "السرير", uk: "ліжко", tr: "yatak" },
  "de lamp": { en: "lamp", ar: "المصباح", uk: "лампа", tr: "lamba" },
  "de kast": { en: "cupboard", ar: "الخزانة", uk: "шафа", tr: "dolap" },
  "de bank": { en: "sofa", ar: "كنبة", uk: "диван", tr: "kanepe" },
  "de televisie": { en: "television", ar: "تلفاز", uk: "телевізор", tr: "televizyon" },
  "de sleutel": { en: "key", ar: "مفتاح", uk: "ключ", tr: "anahtar" },
  "de koelkast": { en: "fridge", ar: "ثلاجة", uk: "холодильник", tr: "buzdolabı" },
  "de trap": { en: "stairs", ar: "درج", uk: "сходи", tr: "merdiven" },
  "het bad": { en: "bath", ar: "حوض استحمام", uk: "ванна", tr: "küvet" },
  "de douche": { en: "shower", ar: "دُش", uk: "душ", tr: "duş" },
  "de wasbak": { en: "sink", ar: "مغسلة", uk: "умивальник", tr: "lavabo" },
  "de handdoek": { en: "towel", ar: "منشفة", uk: "рушник", tr: "havlu" },
  "de zeep": { en: "soap", ar: "صابون", uk: "мило", tr: "sabun" },
  "de tandenborstel": { en: "toothbrush", ar: "فرشاة أسنان", uk: "зубна щітка", tr: "diş fırçası" },
  // Dieren thuis en op de boerderij
  "de hond": { en: "dog", ar: "كلب", uk: "собака", tr: "köpek" },
  "de kat": { en: "cat", ar: "قطة", uk: "кіт", tr: "kedi" },
  "de vogel": { en: "bird", ar: "طائر", uk: "птах", tr: "kuş" },
  "de vis": { en: "fish", ar: "سمكة", uk: "риба", tr: "balık" },
  "het paard": { en: "horse", ar: "حصان", uk: "кінь", tr: "at" },
  "de koe": { en: "cow", ar: "بقرة", uk: "корова", tr: "inek" },
  "het varken": { en: "pig", ar: "خنزير", uk: "свиня", tr: "domuz" },
  "het schaap": { en: "sheep", ar: "خروف", uk: "вівця", tr: "koyun" },
  "de kip": { en: "chicken", ar: "دجاجة", uk: "курка", tr: "tavuk" },
  "de eend": { en: "duck", ar: "بطة", uk: "качка", tr: "ördek" },
  "het konijn": { en: "rabbit", ar: "أرنب", uk: "кролик", tr: "tavşan" },
  "de muis": { en: "mouse", ar: "فأر", uk: "миша", tr: "fare" },
  // Dieren in de dierentuin en de natuur
  "de leeuw": { en: "lion", ar: "أسد", uk: "лев", tr: "aslan" },
  "de olifant": { en: "elephant", ar: "فيل", uk: "слон", tr: "fil" },
  "de giraf": { en: "giraffe", ar: "زرافة", uk: "жирафа", tr: "zürafa" },
  "de beer": { en: "bear", ar: "دب", uk: "ведмідь", tr: "ayı" },
  "de tijger": { en: "tiger", ar: "نمر", uk: "тигр", tr: "kaplan" },
  "de zebra": { en: "zebra", ar: "حمار وحشي", uk: "зебра", tr: "zebra" },
  "de aap": { en: "monkey", ar: "قرد", uk: "мавпа", tr: "maymun" },
  "de slang": { en: "snake", ar: "ثعبان", uk: "змія", tr: "yılan" },
  "de kikker": { en: "frog", ar: "ضفدع", uk: "жаба", tr: "kurbağa" },
  "de vlinder": { en: "butterfly", ar: "فراشة", uk: "метелик", tr: "kelebek" },
  "de bij": { en: "bee", ar: "نحلة", uk: "бджола", tr: "arı" },
  "de spin": { en: "spider", ar: "عنكبوت", uk: "павук", tr: "örümcek" },
  "de uil": { en: "owl", ar: "بومة", uk: "сова", tr: "baykuş" },
  // Spelen
  "de bal": { en: "ball", ar: "كرة", uk: "м’яч", tr: "top" },
  "de ballon": { en: "balloon", ar: "بالون", uk: "повітряна кулька", tr: "balon" },
  "de schommel": { en: "swing", ar: "أرجوحة", uk: "гойдалка", tr: "salıncak" },
  "de glijbaan": { en: "slide", ar: "زلّاقة", uk: "гірка", tr: "kaydırak" },
  "de wip": { en: "seesaw", ar: "أرجوحة التوازن", uk: "гойдалка-балансир", tr: "tahterevalli" },
  "de trampoline": { en: "trampoline", ar: "ترامبولين", uk: "батут", tr: "trambolin" },
  "de vlieger": { en: "kite", ar: "طائرة ورقية", uk: "повітряний змій", tr: "uçurtma" },
  "de pop": { en: "doll", ar: "دمية", uk: "лялька", tr: "oyuncak bebek" },
  "de knuffelbeer": { en: "teddy bear", ar: "دب محشو", uk: "ведмедик", tr: "oyuncak ayı" },
  "de trommel": { en: "drum", ar: "طبل", uk: "барабан", tr: "davul" },
  "de gitaar": { en: "guitar", ar: "غيتار", uk: "гітара", tr: "gitar" },
  "de piano": { en: "piano", ar: "بيانو", uk: "піаніно", tr: "piyano" },
  // Buiten en verkeer
  "de auto": { en: "car", ar: "السيارة", uk: "машина", tr: "araba" },
  "de bus": { en: "bus", ar: "الحافلة", uk: "автобус", tr: "otobüs" },
  "de fiets": { en: "bicycle", ar: "الدرّاجة", uk: "велосипед", tr: "bisiklet" },
  "de trein": { en: "train", ar: "قطار", uk: "потяг", tr: "tren" },
  "het vliegtuig": { en: "plane", ar: "طائرة", uk: "літак", tr: "uçak" },
  "de boot": { en: "boat", ar: "قارب", uk: "човен", tr: "tekne" },
  "de motor": { en: "motorbike", ar: "دراجة نارية", uk: "мотоцикл", tr: "motosiklet" },
  "de vrachtwagen": { en: "truck", ar: "شاحنة", uk: "вантажівка", tr: "kamyon" },
  "de tractor": { en: "tractor", ar: "جرار", uk: "трактор", tr: "traktör" },
  "de brandweerauto": { en: "fire engine", ar: "سيارة إطفاء", uk: "пожежна машина", tr: "itfaiye arabası" },
  "de ambulance": { en: "ambulance", ar: "سيارة إسعاف", uk: "швидка", tr: "ambulans" },
  "de politieauto": { en: "police car", ar: "سيارة شرطة", uk: "поліцейська машина", tr: "polis arabası" },
  "de straat": { en: "street", ar: "الشارع", uk: "вулиця", tr: "sokak" },
  "het stoplicht": { en: "traffic light", ar: "إشارة مرور", uk: "світлофор", tr: "trafik ışığı" },
  "het zebrapad": { en: "zebra crossing", ar: "ممر مشاة", uk: "пішохідний перехід", tr: "yaya geçidi" },
  "de winkel": { en: "shop", ar: "المتجر", uk: "магазин", tr: "dükkân" },
  "de school": { en: "school", ar: "المدرسة", uk: "школа", tr: "okul" },
  // Het weer en de natuur
  "de zon": { en: "sun", ar: "شمس", uk: "сонце", tr: "güneş" },
  "de regen": { en: "rain", ar: "مطر", uk: "дощ", tr: "yağmur" },
  "de regenboog": { en: "rainbow", ar: "قوس قزح", uk: "веселка", tr: "gökkuşağı" },
  "de ster": { en: "star", ar: "نجمة", uk: "зірка", tr: "yıldız" },
  "de paraplu": { en: "umbrella", ar: "مظلة", uk: "парасолька", tr: "şemsiye" },
  "de boom": { en: "tree", ar: "شجرة", uk: "дерево", tr: "ağaç" },
  "de bloem": { en: "flower", ar: "زهرة", uk: "квітка", tr: "çiçek" },
  "het strand": { en: "beach", ar: "شاطئ", uk: "пляж", tr: "plaj" },
  // Doen in de klas
  "schrijven": { en: "write", ar: "يكتب", uk: "писати", tr: "yazmak" },
  "lezen": { en: "read", ar: "يقرأ", uk: "читати", tr: "okumak" },
  "kleuren": { en: "colour", ar: "يلوّن", uk: "розфарбовувати", tr: "boyamak" },
  "knippen": { en: "cut", ar: "يقصّ", uk: "вирізати ножицями", tr: "makasla kesmek" },
  "plakken": { en: "glue", ar: "يلصق", uk: "клеїти", tr: "yapıştırmak" },
  "tellen": { en: "count", ar: "يعدّ", uk: "рахувати", tr: "saymak" },
  "kijken": { en: "look", ar: "ينظر", uk: "дивитися", tr: "bakmak" },
  "luisteren": { en: "listen", ar: "يستمع", uk: "слухати", tr: "dinlemek" },
  "opruimen": { en: "tidy up", ar: "يرتّب", uk: "прибирати", tr: "toplamak" },
  "praten": { en: "talk", ar: "يتكلّم", uk: "говорити", tr: "konuşmak" },
  "zingen": { en: "sing", ar: "يغنّي", uk: "співати", tr: "şarkı söylemek" },
  "klappen": { en: "clap", ar: "يصفّق", uk: "плескати", tr: "alkışlamak" },
  "wijzen": { en: "point", ar: "يشير", uk: "показувати", tr: "göstermek" },
  // Doen: elke dag
  "eten": { en: "eat", ar: "يأكل", uk: "їсти", tr: "yemek" },
  "drinken": { en: "drink", ar: "يشرب", uk: "пити", tr: "içmek" },
  "slapen": { en: "sleep", ar: "ينام", uk: "спати", tr: "uyumak" },
  "handen wassen": { en: "wash hands", ar: "يغسل يديه", uk: "мити руки", tr: "el yıkamak" },
  "tanden poetsen": { en: "brush teeth", ar: "ينظّف أسنانه", uk: "чистити зуби", tr: "diş fırçalamak" },
  "koken": { en: "cook", ar: "يطبخ", uk: "готувати", tr: "yemek pişirmek" },
  "lachen": { en: "laugh", ar: "يضحك", uk: "сміятися", tr: "gülmek" },
  "geven": { en: "give", ar: "يعطي", uk: "давати", tr: "vermek" },
  "knuffelen": { en: "hug", ar: "يعانق", uk: "обіймати", tr: "sarılmak" },
  // Doen: bewegen
  "rennen": { en: "run", ar: "يركض", uk: "бігати", tr: "koşmak" },
  "springen": { en: "jump", ar: "يقفز", uk: "стрибати", tr: "zıplamak" },
  "zitten": { en: "sit", ar: "يجلس", uk: "сидіти", tr: "oturmak" },
  "zwemmen": { en: "swim", ar: "يسبح", uk: "плавати", tr: "yüzmek" },
  "klimmen": { en: "climb", ar: "يتسلّق", uk: "лазити", tr: "tırmanmak" },
  "fietsen": { en: "ride a bike", ar: "يركب الدراجة", uk: "їздити на велосипеді", tr: "bisiklete binmek" },
  "schoppen": { en: "kick", ar: "يركل", uk: "бити ногою", tr: "tekmelemek" },
  "vangen": { en: "catch", ar: "يلتقط", uk: "ловити", tr: "yakalamak" },
  "schommelen": { en: "swing", ar: "يتأرجح", uk: "гойдатися", tr: "sallanmak" },
  "rijden": { en: "drive", ar: "يقود السيارة", uk: "водити машину", tr: "araba sürmek" },
  // Wel een plaatje, (nog) in geen thema
  "tekenen": { en: "draw", ar: "يرسم", uk: "малювати", tr: "resim çizmek" },
  "de dokter": { en: "doctor", ar: "طبيب", uk: "лікар", tr: "doktor" },
  "de lolly": { en: "lollipop", ar: "مصاصة", uk: "льодяник", tr: "lolipop" },
  "de chips": { en: "chips", ar: "رقائق البطاطا", uk: "чипси", tr: "cips" },
};

// Nieuw vertaald op 29 sep 2026 (niet uit de lessen): nog laten nakijken door een moedertaalspreker.
export const NAKIJKEN = [
  "de schaar", "de lijm", "het papier", "het schrift", "de kwast", "het etui", "de computer",
  "de klok", "de boterham", "de pizza", "het koekje", "de taart", "het ijsje", "de chocola",
  "de patat", "de lepel", "de vork", "het mes", "de beker", "de sinaasappel", "de peer", "de druif",
  "de aardbei", "de citroen", "de kers", "de ananas", "de wortel", "de tomaat", "de komkommer",
  "de tong", "het T-shirt", "de jurk", "de rok", "de korte broek", "de onderbroek", "de laars",
  "de pet", "de sjaal", "de handschoen", "het gezin", "de baby", "de bank", "de televisie",
  "de sleutel", "de koelkast", "de trap", "het bad", "de douche", "de wasbak", "de handdoek",
  "de zeep", "de tandenborstel", "de hond", "de kat", "de vogel", "de vis", "het paard", "de koe",
  "het varken", "het schaap", "de kip", "de eend", "het konijn", "de muis", "de leeuw",
  "de olifant", "de giraf", "de beer", "de tijger", "de zebra", "de aap", "de slang", "de kikker",
  "de vlinder", "de bij", "de spin", "de uil", "de bal", "de ballon", "de schommel", "de glijbaan",
  "de wip", "de trampoline", "de vlieger", "de pop", "de knuffelbeer", "de trommel", "de gitaar",
  "de piano", "de trein", "het vliegtuig", "de boot", "de motor", "de vrachtwagen", "de tractor",
  "de brandweerauto", "de ambulance", "de politieauto", "het stoplicht", "het zebrapad", "de zon",
  "de regen", "de regenboog", "de ster", "de paraplu", "de boom", "de bloem", "het strand",
  "praten", "zingen", "klappen", "wijzen", "eten", "drinken", "slapen", "handen wassen",
  "tanden poetsen", "koken", "lachen", "geven", "knuffelen", "rennen", "springen", "zitten",
  "zwemmen", "klimmen", "fietsen", "schoppen", "vangen", "schommelen", "rijden", "de dokter",
  "de lolly", "de chips",
];
