// 🌍 Vertalingen voor het plaatjesdictee voor nieuwkomers (NieuwkomersPlaatjesDictee.jsx).
// Gemaakt 29 sep 2026 voor het plaatjesdictee: de app zegt het woord in de thuistaal ("apple",
// "تفاحة", "яблуко", "elma") en het kind schrijft het Nederlandse woord bij het plaatje.
// Eén regel per woord uit WOORDKAARTEN en PICTO (nieuwkomersPicto.js), kleuren niet meegeteld.
//
// Herkomst: 56 woorden komen uit de nagekeken woordenboekjes van de lessen
// (woordenNieuwkomers.js, woorden2Nieuwkomers.js; "de wc" uit nieuwkomersSteun.js). Die zijn alleen
// ingekort tot een gesproken woord: Engels zonder "the"/"to", tekst tussen haakjes weg, bij "a / b"
// alleen het eerste woord (juf/meester: "female teacher"/"male teacher").
// De 134 andere woorden zijn NIEUW vertaald en staan in NAKIJKEN: die moeten nog worden
// nagekeken door iemand die de taal als moedertaal spreekt.
//
// Regels bij het vertalen: het gewone woord dat een kind van 6-10 kent, passend bij het PLAATJE
// (de bank = sofa, de motor = motorfiets, de wip = wipwap, rijden = autorijden, de boot = zeilboot);
// Engels zonder lidwoord; Arabisch (standaard) enkelvoud zonder ال (de overgenomen woorden houden
// ال zoals in de lessen); Oekraïens en Turks eerste naamval enkelvoud; doe-woorden als hele werkwoord (Engels kaal: "write"; Arabisch zoals in de
// lessen: يكتب; Oekraïens писати; Turks yazmak).
// 30 sep 2026: Roemeens (ro, hele werkwoord "a scrie", zelfstandig naamwoord zonder lidwoord) en Bulgaars
// (bg, werkwoord in de woordenboekvorm "пиша", zonder lidwoord) erbij op verzoek van een nieuwkomersschool.
// ALLE ro/bg-woorden zijn nieuw vertaald door Claude → NAKIJKEN_RO_BG hieronder.

export const VERTALINGEN = {
  // In de klas
  "de tafel": { en: "table", ar: "الطاولة", uk: "стіл", tr: "masa", ro: "masă", bg: "маса" },
  "de stoel": { en: "chair", ar: "الكرسي", uk: "стілець", tr: "sandalye", ro: "scaun", bg: "стол" },
  "de deur": { en: "door", ar: "الباب", uk: "двері", tr: "kapı", ro: "ușă", bg: "врата" },
  "het raam": { en: "window", ar: "النافذة", uk: "вікно", tr: "pencere", ro: "fereastră", bg: "прозорец" },
  "het bord": { en: "board", ar: "السبّورة", uk: "дошка", tr: "tahta", ro: "tablă", bg: "дъска" },
  "de tas": { en: "bag", ar: "الحقيبة", uk: "сумка", tr: "çanta", ro: "geantă", bg: "чанта" },
  "de pen": { en: "pen", ar: "القلم", uk: "ручка", tr: "kalem", ro: "pix", bg: "химикалка" },
  "de schaar": { en: "scissors", ar: "مقص", uk: "ножиці", tr: "makas", ro: "foarfecă", bg: "ножица" },
  "de lijm": { en: "glue", ar: "صمغ", uk: "клей", tr: "yapıştırıcı", ro: "lipici", bg: "лепило" },
  "het papier": { en: "paper", ar: "ورق", uk: "папір", tr: "kâğıt", ro: "hârtie", bg: "хартия" },
  "het schrift": { en: "notebook", ar: "دفتر", uk: "зошит", tr: "defter", ro: "caiet", bg: "тетрадка" },
  "het boek": { en: "book", ar: "الكتاب", uk: "книжка", tr: "kitap", ro: "carte", bg: "книга" },
  "de kwast": { en: "paintbrush", ar: "فرشاة", uk: "пензлик", tr: "fırça", ro: "pensulă", bg: "четка" },
  "het etui": { en: "pencil case", ar: "مقلمة", uk: "пенал", tr: "kalemlik", ro: "penar", bg: "несесер" },
  "de computer": { en: "computer", ar: "حاسوب", uk: "комп’ютер", tr: "bilgisayar", ro: "calculator", bg: "компютър" },
  "de klok": { en: "clock", ar: "ساعة", uk: "годинник", tr: "saat", ro: "ceas", bg: "часовник" },
  "de juf": { en: "female teacher", ar: "المعلّمة", uk: "вчителька", tr: "kadın öğretmen", ro: "învățătoare", bg: "учителка" },
  "de meester": { en: "male teacher", ar: "المعلّم", uk: "вчитель", tr: "erkek öğretmen", ro: "învățător", bg: "учител" },
  "de wc": { en: "toilet", ar: "الحمام", uk: "туалет", tr: "tuvalet", ro: "toaletă", bg: "тоалетна" },
  // Eten en drinken
  "de melk": { en: "milk", ar: "الحليب", uk: "молоко", tr: "süt", ro: "lapte", bg: "мляко" },
  "het water": { en: "water", ar: "الماء", uk: "вода", tr: "su", ro: "apă", bg: "вода" },
  "het brood": { en: "bread", ar: "الخبز", uk: "хліб", tr: "ekmek", ro: "pâine", bg: "хляб" },
  "de kaas": { en: "cheese", ar: "الجبن", uk: "сир", tr: "peynir", ro: "brânză", bg: "кашкавал" },
  "het ei": { en: "egg", ar: "البيضة", uk: "яйце", tr: "yumurta", ro: "ou", bg: "яйце" },
  "de rijst": { en: "rice", ar: "الأرز", uk: "рис", tr: "pirinç", ro: "orez", bg: "ориз" },
  "de soep": { en: "soup", ar: "الحساء", uk: "суп", tr: "çorba", ro: "supă", bg: "супа" },
  "de thee": { en: "tea", ar: "الشاي", uk: "чай", tr: "çay", ro: "ceai", bg: "чай" },
  "de boterham": { en: "sandwich", ar: "شطيرة", uk: "бутерброд", tr: "sandviç", ro: "sandviș", bg: "сандвич" },
  "de pizza": { en: "pizza", ar: "بيتزا", uk: "піца", tr: "pizza", ro: "pizza", bg: "пица" },
  "het koekje": { en: "cookie", ar: "بسكويت", uk: "печиво", tr: "bisküvi", ro: "biscuit", bg: "бисквитка" },
  "de taart": { en: "cake", ar: "كعكة", uk: "торт", tr: "pasta", ro: "tort", bg: "торта" },
  "het ijsje": { en: "ice cream", ar: "آيس كريم", uk: "морозиво", tr: "dondurma", ro: "înghețată", bg: "сладолед" },
  "de chocola": { en: "chocolate", ar: "شوكولاتة", uk: "шоколад", tr: "çikolata", ro: "ciocolată", bg: "шоколад" },
  "de patat": { en: "fries", ar: "بطاطا مقلية", uk: "картопля фрі", tr: "patates kızartması", ro: "cartofi prăjiți", bg: "пържени картофи" },
  "de lepel": { en: "spoon", ar: "ملعقة", uk: "ложка", tr: "kaşık", ro: "lingură", bg: "лъжица" },
  "de vork": { en: "fork", ar: "شوكة", uk: "виделка", tr: "çatal", ro: "furculiță", bg: "вилица" },
  "het mes": { en: "knife", ar: "سكين", uk: "ніж", tr: "bıçak", ro: "cuțit", bg: "нож" },
  "de beker": { en: "cup", ar: "كوب", uk: "чашка", tr: "bardak", ro: "cană", bg: "чаша" },
  // Fruit en groente
  "de appel": { en: "apple", ar: "التفاحة", uk: "яблуко", tr: "elma", ro: "măr", bg: "ябълка" },
  "de banaan": { en: "banana", ar: "الموزة", uk: "банан", tr: "muz", ro: "banană", bg: "банан" },
  "de sinaasappel": { en: "orange", ar: "برتقالة", uk: "апельсин", tr: "portakal", ro: "portocală", bg: "портокал" },
  "de peer": { en: "pear", ar: "كمثرى", uk: "груша", tr: "armut", ro: "pară", bg: "круша" },
  "de druif": { en: "grape", ar: "عنب", uk: "виноград", tr: "üzüm", ro: "strugure", bg: "грозде" },
  "de aardbei": { en: "strawberry", ar: "فراولة", uk: "полуниця", tr: "çilek", ro: "căpșună", bg: "ягода" },
  "de citroen": { en: "lemon", ar: "ليمون", uk: "лимон", tr: "limon", ro: "lămâie", bg: "лимон" },
  "de kers": { en: "cherry", ar: "كرز", uk: "вишня", tr: "kiraz", ro: "cireașă", bg: "череша" },
  "de ananas": { en: "pineapple", ar: "أناناس", uk: "ананас", tr: "ananas", ro: "ananas", bg: "ананас" },
  "de wortel": { en: "carrot", ar: "جزرة", uk: "морква", tr: "havuç", ro: "morcov", bg: "морков" },
  "de tomaat": { en: "tomato", ar: "طماطم", uk: "помідор", tr: "domates", ro: "roșie", bg: "домат" },
  "de komkommer": { en: "cucumber", ar: "خيار", uk: "огірок", tr: "salatalık", ro: "castravete", bg: "краставица" },
  // Mijn lichaam
  "het hoofd": { en: "head", ar: "الرأس", uk: "голова", tr: "baş", ro: "cap", bg: "глава" },
  "het oog": { en: "eye", ar: "العين", uk: "око", tr: "göz", ro: "ochi", bg: "око" },
  "het oor": { en: "ear", ar: "الأذن", uk: "вухо", tr: "kulak", ro: "ureche", bg: "ухо" },
  "de mond": { en: "mouth", ar: "الفم", uk: "рот", tr: "ağız", ro: "gură", bg: "уста" },
  "de tong": { en: "tongue", ar: "لسان", uk: "язик", tr: "dil", ro: "limbă", bg: "език" },
  "de buik": { en: "belly", ar: "البطن", uk: "живіт", tr: "karın", ro: "burtă", bg: "корем" },
  "de arm": { en: "arm", ar: "الذراع", uk: "рука", tr: "kol", ro: "braț", bg: "ръка" },
  "de hand": { en: "hand", ar: "اليد", uk: "рука", tr: "el", ro: "mână", bg: "ръка" },
  "de voet": { en: "foot", ar: "القدم", uk: "стопа", tr: "ayak", ro: "laba piciorului", bg: "стъпало" },
  // Kleding
  "de jas": { en: "coat", ar: "المعطف", uk: "куртка", tr: "mont", ro: "geacă", bg: "яке" },
  "de broek": { en: "trousers", ar: "البنطال", uk: "штани", tr: "pantolon", ro: "pantaloni", bg: "панталон" },
  "het T-shirt": { en: "T-shirt", ar: "تي شيرت", uk: "футболка", tr: "tişört", ro: "tricou", bg: "тениска" },
  "de trui": { en: "jumper", ar: "الكنزة", uk: "светр", tr: "kazak", ro: "pulover", bg: "пуловер" },
  "de jurk": { en: "dress", ar: "فستان", uk: "сукня", tr: "elbise", ro: "rochie", bg: "рокля" },
  "de rok": { en: "skirt", ar: "تنورة", uk: "спідниця", tr: "etek", ro: "fustă", bg: "пола" },
  "de korte broek": { en: "shorts", ar: "شورت", uk: "шорти", tr: "şort", ro: "pantaloni scurți", bg: "къси панталони" },
  "de onderbroek": { en: "underpants", ar: "سروال داخلي", uk: "труси", tr: "külot", ro: "chiloți", bg: "гащи" },
  "de sok": { en: "sock", ar: "الجورب", uk: "шкарпетка", tr: "çorap", ro: "șosetă", bg: "чорап" },
  "de schoen": { en: "shoe", ar: "الحذاء", uk: "черевик", tr: "ayakkabı", ro: "pantof", bg: "обувка" },
  "de laars": { en: "boot", ar: "جزمة", uk: "чобіт", tr: "çizme", ro: "cizmă", bg: "ботуш" },
  "de muts": { en: "woolly hat", ar: "القبعة الصوفية", uk: "шапка", tr: "bere", ro: "căciulă", bg: "шапка" },
  "de pet": { en: "cap", ar: "قبعة", uk: "кепка", tr: "şapka", ro: "șapcă", bg: "каскет" },
  "de sjaal": { en: "scarf", ar: "وشاح", uk: "шарф", tr: "atkı", ro: "fular", bg: "шал" },
  "de handschoen": { en: "glove", ar: "قفاز", uk: "рукавичка", tr: "eldiven", ro: "mănușă", bg: "ръкавица" },
  // Thuis
  "het huis": { en: "house", ar: "البيت", uk: "будинок", tr: "ev", ro: "casă", bg: "къща" },
  "de tuin": { en: "garden", ar: "الحديقة", uk: "сад", tr: "bahçe", ro: "grădină", bg: "градина" },
  "het gezin": { en: "family", ar: "عائلة", uk: "сім’я", tr: "aile", ro: "familie", bg: "семейство" },
  "de baby": { en: "baby", ar: "رضيع", uk: "немовля", tr: "bebek", ro: "bebeluș", bg: "бебе" },
  "het bed": { en: "bed", ar: "السرير", uk: "ліжко", tr: "yatak", ro: "pat", bg: "легло" },
  "de lamp": { en: "lamp", ar: "المصباح", uk: "лампа", tr: "lamba", ro: "lampă", bg: "лампа" },
  "de kast": { en: "cupboard", ar: "الخزانة", uk: "шафа", tr: "dolap", ro: "dulap", bg: "шкаф" },
  "de bank": { en: "sofa", ar: "كنبة", uk: "диван", tr: "kanepe", ro: "canapea", bg: "диван" },
  "de televisie": { en: "television", ar: "تلفاز", uk: "телевізор", tr: "televizyon", ro: "televizor", bg: "телевизор" },
  "de sleutel": { en: "key", ar: "مفتاح", uk: "ключ", tr: "anahtar", ro: "cheie", bg: "ключ" },
  "de koelkast": { en: "fridge", ar: "ثلاجة", uk: "холодильник", tr: "buzdolabı", ro: "frigider", bg: "хладилник" },
  "de trap": { en: "stairs", ar: "درج", uk: "сходи", tr: "merdiven", ro: "scară", bg: "стълба" },
  "het bad": { en: "bath", ar: "حوض استحمام", uk: "ванна", tr: "küvet", ro: "cadă", bg: "вана" },
  "de douche": { en: "shower", ar: "دُش", uk: "душ", tr: "duş", ro: "duș", bg: "душ" },
  "de wasbak": { en: "sink", ar: "مغسلة", uk: "умивальник", tr: "lavabo", ro: "chiuvetă", bg: "мивка" },
  "de handdoek": { en: "towel", ar: "منشفة", uk: "рушник", tr: "havlu", ro: "prosop", bg: "кърпа" },
  "de zeep": { en: "soap", ar: "صابون", uk: "мило", tr: "sabun", ro: "săpun", bg: "сапун" },
  "de tandenborstel": { en: "toothbrush", ar: "فرشاة أسنان", uk: "зубна щітка", tr: "diş fırçası", ro: "periuță de dinți", bg: "четка за зъби" },
  // Dieren thuis en op de boerderij
  "de hond": { en: "dog", ar: "كلب", uk: "собака", tr: "köpek", ro: "câine", bg: "куче" },
  "de kat": { en: "cat", ar: "قطة", uk: "кіт", tr: "kedi", ro: "pisică", bg: "котка" },
  "de vogel": { en: "bird", ar: "طائر", uk: "птах", tr: "kuş", ro: "pasăre", bg: "птица" },
  "de vis": { en: "fish", ar: "سمكة", uk: "риба", tr: "balık", ro: "pește", bg: "риба" },
  "het paard": { en: "horse", ar: "حصان", uk: "кінь", tr: "at", ro: "cal", bg: "кон" },
  "de koe": { en: "cow", ar: "بقرة", uk: "корова", tr: "inek", ro: "vacă", bg: "крава" },
  "het varken": { en: "pig", ar: "خنزير", uk: "свиня", tr: "domuz", ro: "porc", bg: "прасе" },
  "het schaap": { en: "sheep", ar: "خروف", uk: "вівця", tr: "koyun", ro: "oaie", bg: "овца" },
  "de kip": { en: "chicken", ar: "دجاجة", uk: "курка", tr: "tavuk", ro: "găină", bg: "кокошка" },
  "de eend": { en: "duck", ar: "بطة", uk: "качка", tr: "ördek", ro: "rață", bg: "патица" },
  "het konijn": { en: "rabbit", ar: "أرنب", uk: "кролик", tr: "tavşan", ro: "iepure", bg: "заек" },
  "de muis": { en: "mouse", ar: "فأر", uk: "миша", tr: "fare", ro: "șoarece", bg: "мишка" },
  // Dieren in de dierentuin en de natuur
  "de leeuw": { en: "lion", ar: "أسد", uk: "лев", tr: "aslan", ro: "leu", bg: "лъв" },
  "de olifant": { en: "elephant", ar: "فيل", uk: "слон", tr: "fil", ro: "elefant", bg: "слон" },
  "de giraf": { en: "giraffe", ar: "زرافة", uk: "жирафа", tr: "zürafa", ro: "girafă", bg: "жираф" },
  "de beer": { en: "bear", ar: "دب", uk: "ведмідь", tr: "ayı", ro: "urs", bg: "мечка" },
  "de tijger": { en: "tiger", ar: "نمر", uk: "тигр", tr: "kaplan", ro: "tigru", bg: "тигър" },
  "de zebra": { en: "zebra", ar: "حمار وحشي", uk: "зебра", tr: "zebra", ro: "zebră", bg: "зебра" },
  "de aap": { en: "monkey", ar: "قرد", uk: "мавпа", tr: "maymun", ro: "maimuță", bg: "маймуна" },
  "de slang": { en: "snake", ar: "ثعبان", uk: "змія", tr: "yılan", ro: "șarpe", bg: "змия" },
  "de kikker": { en: "frog", ar: "ضفدع", uk: "жаба", tr: "kurbağa", ro: "broască", bg: "жаба" },
  "de vlinder": { en: "butterfly", ar: "فراشة", uk: "метелик", tr: "kelebek", ro: "fluture", bg: "пеперуда" },
  "de bij": { en: "bee", ar: "نحلة", uk: "бджола", tr: "arı", ro: "albină", bg: "пчела" },
  "de spin": { en: "spider", ar: "عنكبوت", uk: "павук", tr: "örümcek", ro: "păianjen", bg: "паяк" },
  "de uil": { en: "owl", ar: "بومة", uk: "сова", tr: "baykuş", ro: "bufniță", bg: "бухал" },
  // Spelen
  "de bal": { en: "ball", ar: "كرة", uk: "м’яч", tr: "top", ro: "minge", bg: "топка" },
  "de ballon": { en: "balloon", ar: "بالون", uk: "повітряна кулька", tr: "balon", ro: "balon", bg: "балон" },
  "de schommel": { en: "swing", ar: "أرجوحة", uk: "гойдалка", tr: "salıncak", ro: "leagăn", bg: "люлка" },
  "de glijbaan": { en: "slide", ar: "زلّاقة", uk: "гірка", tr: "kaydırak", ro: "tobogan", bg: "пързалка" },
  "de wip": { en: "seesaw", ar: "أرجوحة التوازن", uk: "гойдалка-балансир", tr: "tahterevalli", ro: "balansoar", bg: "клатушка" },
  "de trampoline": { en: "trampoline", ar: "ترامبولين", uk: "батут", tr: "trambolin", ro: "trambulină", bg: "батут" },
  "de vlieger": { en: "kite", ar: "طائرة ورقية", uk: "повітряний змій", tr: "uçurtma", ro: "zmeu", bg: "хвърчило" },
  "de pop": { en: "doll", ar: "دمية", uk: "лялька", tr: "oyuncak bebek", ro: "păpușă", bg: "кукла" },
  "de knuffelbeer": { en: "teddy bear", ar: "دب محشو", uk: "ведмедик", tr: "oyuncak ayı", ro: "ursuleț de pluș", bg: "плюшено мече" },
  "de trommel": { en: "drum", ar: "طبل", uk: "барабан", tr: "davul", ro: "tobă", bg: "барабан" },
  "de gitaar": { en: "guitar", ar: "غيتار", uk: "гітара", tr: "gitar", ro: "chitară", bg: "китара" },
  "de piano": { en: "piano", ar: "بيانو", uk: "піаніно", tr: "piyano", ro: "pian", bg: "пиано" },
  // Buiten en verkeer
  "de auto": { en: "car", ar: "السيارة", uk: "машина", tr: "araba", ro: "mașină", bg: "кола" },
  "de bus": { en: "bus", ar: "الحافلة", uk: "автобус", tr: "otobüs", ro: "autobuz", bg: "автобус" },
  "de fiets": { en: "bicycle", ar: "الدرّاجة", uk: "велосипед", tr: "bisiklet", ro: "bicicletă", bg: "колело" },
  "de trein": { en: "train", ar: "قطار", uk: "потяг", tr: "tren", ro: "tren", bg: "влак" },
  "het vliegtuig": { en: "plane", ar: "طائرة", uk: "літак", tr: "uçak", ro: "avion", bg: "самолет" },
  "de boot": { en: "boat", ar: "قارب", uk: "човен", tr: "tekne", ro: "barcă", bg: "лодка" },
  "de motor": { en: "motorbike", ar: "دراجة نارية", uk: "мотоцикл", tr: "motosiklet", ro: "motocicletă", bg: "мотор" },
  "de vrachtwagen": { en: "truck", ar: "شاحنة", uk: "вантажівка", tr: "kamyon", ro: "camion", bg: "камион" },
  "de tractor": { en: "tractor", ar: "جرار", uk: "трактор", tr: "traktör", ro: "tractor", bg: "трактор" },
  "de brandweerauto": { en: "fire engine", ar: "سيارة إطفاء", uk: "пожежна машина", tr: "itfaiye arabası", ro: "mașină de pompieri", bg: "пожарна кола" },
  "de ambulance": { en: "ambulance", ar: "سيارة إسعاف", uk: "швидка", tr: "ambulans", ro: "ambulanță", bg: "линейка" },
  "de politieauto": { en: "police car", ar: "سيارة شرطة", uk: "поліцейська машина", tr: "polis arabası", ro: "mașină de poliție", bg: "полицейска кола" },
  "de straat": { en: "street", ar: "الشارع", uk: "вулиця", tr: "sokak", ro: "stradă", bg: "улица" },
  "het stoplicht": { en: "traffic light", ar: "إشارة مرور", uk: "світлофор", tr: "trafik ışığı", ro: "semafor", bg: "светофар" },
  "het zebrapad": { en: "zebra crossing", ar: "ممر مشاة", uk: "пішохідний перехід", tr: "yaya geçidi", ro: "trecere de pietoni", bg: "пешеходна пътека" },
  "de winkel": { en: "shop", ar: "المتجر", uk: "магазин", tr: "dükkân", ro: "magazin", bg: "магазин" },
  "de school": { en: "school", ar: "المدرسة", uk: "школа", tr: "okul", ro: "școală", bg: "училище" },
  // Het weer en de natuur
  "de zon": { en: "sun", ar: "شمس", uk: "сонце", tr: "güneş", ro: "soare", bg: "слънце" },
  "de regen": { en: "rain", ar: "مطر", uk: "дощ", tr: "yağmur", ro: "ploaie", bg: "дъжд" },
  "de regenboog": { en: "rainbow", ar: "قوس قزح", uk: "веселка", tr: "gökkuşağı", ro: "curcubeu", bg: "дъга" },
  "de ster": { en: "star", ar: "نجمة", uk: "зірка", tr: "yıldız", ro: "stea", bg: "звезда" },
  "de paraplu": { en: "umbrella", ar: "مظلة", uk: "парасолька", tr: "şemsiye", ro: "umbrelă", bg: "чадър" },
  "de boom": { en: "tree", ar: "شجرة", uk: "дерево", tr: "ağaç", ro: "copac", bg: "дърво" },
  "de bloem": { en: "flower", ar: "زهرة", uk: "квітка", tr: "çiçek", ro: "floare", bg: "цвете" },
  "het strand": { en: "beach", ar: "شاطئ", uk: "пляж", tr: "plaj", ro: "plajă", bg: "плаж" },
  // Doen in de klas
  "schrijven": { en: "write", ar: "يكتب", uk: "писати", tr: "yazmak", ro: "a scrie", bg: "пиша" },
  "lezen": { en: "read", ar: "يقرأ", uk: "читати", tr: "okumak", ro: "a citi", bg: "чета" },
  "kleuren": { en: "colour", ar: "يلوّن", uk: "розфарбовувати", tr: "boyamak", ro: "a colora", bg: "оцветявам" },
  "knippen": { en: "cut", ar: "يقصّ", uk: "вирізати ножицями", tr: "makasla kesmek", ro: "a tăia cu foarfeca", bg: "режа с ножица" },
  "plakken": { en: "glue", ar: "يلصق", uk: "клеїти", tr: "yapıştırmak", ro: "a lipi", bg: "лепя" },
  "tellen": { en: "count", ar: "يعدّ", uk: "рахувати", tr: "saymak", ro: "a număra", bg: "броя" },
  "kijken": { en: "look", ar: "ينظر", uk: "дивитися", tr: "bakmak", ro: "a privi", bg: "гледам" },
  "luisteren": { en: "listen", ar: "يستمع", uk: "слухати", tr: "dinlemek", ro: "a asculta", bg: "слушам" },
  "opruimen": { en: "tidy up", ar: "يرتّب", uk: "прибирати", tr: "toplamak", ro: "a face ordine", bg: "разтребвам" },
  "praten": { en: "talk", ar: "يتكلّم", uk: "говорити", tr: "konuşmak", ro: "a vorbi", bg: "говоря" },
  "zingen": { en: "sing", ar: "يغنّي", uk: "співати", tr: "şarkı söylemek", ro: "a cânta", bg: "пея" },
  "klappen": { en: "clap", ar: "يصفّق", uk: "плескати", tr: "alkışlamak", ro: "a bate din palme", bg: "пляскам с ръце" },
  "wijzen": { en: "point", ar: "يشير", uk: "показувати", tr: "göstermek", ro: "a arăta cu degetul", bg: "соча" },
  // Doen: elke dag
  "eten": { en: "eat", ar: "يأكل", uk: "їсти", tr: "yemek", ro: "a mânca", bg: "ям" },
  "drinken": { en: "drink", ar: "يشرب", uk: "пити", tr: "içmek", ro: "a bea", bg: "пия" },
  "slapen": { en: "sleep", ar: "ينام", uk: "спати", tr: "uyumak", ro: "a dormi", bg: "спя" },
  "handen wassen": { en: "wash hands", ar: "يغسل يديه", uk: "мити руки", tr: "el yıkamak", ro: "a se spăla pe mâini", bg: "мия си ръцете" },
  "tanden poetsen": { en: "brush teeth", ar: "ينظّف أسنانه", uk: "чистити зуби", tr: "diş fırçalamak", ro: "a se spăla pe dinți", bg: "мия си зъбите" },
  "koken": { en: "cook", ar: "يطبخ", uk: "готувати", tr: "yemek pişirmek", ro: "a găti", bg: "готвя" },
  "lachen": { en: "laugh", ar: "يضحك", uk: "сміятися", tr: "gülmek", ro: "a râde", bg: "смея се" },
  "geven": { en: "give", ar: "يعطي", uk: "давати", tr: "vermek", ro: "a da", bg: "давам" },
  "knuffelen": { en: "hug", ar: "يعانق", uk: "обіймати", tr: "sarılmak", ro: "a îmbrățișa", bg: "прегръщам" },
  // Doen: bewegen
  "rennen": { en: "run", ar: "يركض", uk: "бігати", tr: "koşmak", ro: "a alerga", bg: "тичам" },
  "springen": { en: "jump", ar: "يقفز", uk: "стрибати", tr: "zıplamak", ro: "a sări", bg: "скачам" },
  "zitten": { en: "sit", ar: "يجلس", uk: "сидіти", tr: "oturmak", ro: "a sta jos", bg: "седя" },
  "zwemmen": { en: "swim", ar: "يسبح", uk: "плавати", tr: "yüzmek", ro: "a înota", bg: "плувам" },
  "klimmen": { en: "climb", ar: "يتسلّق", uk: "лазити", tr: "tırmanmak", ro: "a se cățăra", bg: "катеря се" },
  "fietsen": { en: "ride a bike", ar: "يركب الدراجة", uk: "їздити на велосипеді", tr: "bisiklete binmek", ro: "a merge cu bicicleta", bg: "карам колело" },
  "schoppen": { en: "kick", ar: "يركل", uk: "бити ногою", tr: "tekmelemek", ro: "a da cu piciorul", bg: "ритам" },
  "vangen": { en: "catch", ar: "يلتقط", uk: "ловити", tr: "yakalamak", ro: "a prinde", bg: "хващам" },
  "schommelen": { en: "swing", ar: "يتأرجح", uk: "гойдатися", tr: "sallanmak", ro: "a se da în leagăn", bg: "люлея се" },
  "rijden": { en: "drive", ar: "يقود السيارة", uk: "водити машину", tr: "araba sürmek", ro: "a conduce mașina", bg: "карам кола" },
  // Wel een plaatje, (nog) in geen thema
  "tekenen": { en: "draw", ar: "يرسم", uk: "малювати", tr: "resim çizmek", ro: "a desena", bg: "рисувам" },
  "de dokter": { en: "doctor", ar: "طبيب", uk: "лікар", tr: "doktor", ro: "doctor", bg: "лекар" },
  "de lolly": { en: "lollipop", ar: "مصاصة", uk: "льодяник", tr: "lolipop", ro: "acadea", bg: "близалка" },
  "de chips": { en: "chips", ar: "رقائق البطاطا", uk: "чипси", tr: "cips", ro: "chipsuri", bg: "чипс" },
};

// Nieuw vertaald op 29 sep 2026 (niet uit de lessen): nog laten nakijken door een moedertaalspreker.
export const NAKIJKEN = [
  "de schaar", "de lijm", "het papier", "het schrift", "de kwast", "het etui", "de computer",
  "de klok", "de boterham", "de pizza", "het koekje", "de taart", "het ijsje", "de chocola",
  "de patat", "de lepel", "de vork", "het mes", "de beker", "de sinaasappel", "de peer", "de druif",
  "de aardbei", "de citroen", "de kers", "de ananas", "de wortel", "de tomaat", "de komkommer",
  "de tong", "het T-shirt", "de jurk", "de rok", "de korte broek", "de onderbroek", "de laars",
  "de pet", "de sjaal", "de handschoen", "het gezin", "de baby", "de bank", "de televisie",
  "de sleutel", "de koelkast", "de trap", "het bad", "de douche", "de wasbak", "de handdoek",
  "de zeep", "de tandenborstel", "de hond", "de kat", "de vogel", "de vis", "het paard", "de koe",
  "het varken", "het schaap", "de kip", "de eend", "het konijn", "de muis", "de leeuw",
  "de olifant", "de giraf", "de beer", "de tijger", "de zebra", "de aap", "de slang", "de kikker",
  "de vlinder", "de bij", "de spin", "de uil", "de bal", "de ballon", "de schommel", "de glijbaan",
  "de wip", "de trampoline", "de vlieger", "de pop", "de knuffelbeer", "de trommel", "de gitaar",
  "de piano", "de trein", "het vliegtuig", "de boot", "de motor", "de vrachtwagen", "de tractor",
  "de brandweerauto", "de ambulance", "de politieauto", "het stoplicht", "het zebrapad", "de zon",
  "de regen", "de regenboog", "de ster", "de paraplu", "de boom", "de bloem", "het strand",
  "praten", "zingen", "klappen", "wijzen", "eten", "drinken", "slapen", "handen wassen",
  "tanden poetsen", "koken", "lachen", "geven", "knuffelen", "rennen", "springen", "zitten",
  "zwemmen", "klimmen", "fietsen", "schoppen", "vangen", "schommelen", "rijden", "de dokter",
  "de lolly", "de chips",
];

// Roemeens en Bulgaars (30 sep 2026): álle 190 woorden nieuw vertaald, nog geen moedertaalcheck.
// Zelfde lijst als de sleutels van VERTALINGEN; haal een woord hier weg zodra het is nagekeken.
export const NAKIJKEN_RO_BG = { ro: Object.keys(VERTALINGEN), bg: Object.keys(VERTALINGEN) };
