// Leerpad: Schaal en plattegrond — groep 7-8 (Doorstroomtoets)
// 4 stappen: schaal begrijpen, van kaart naar echt, van echt naar kaart, toepassingen.

const chapters = [
  { letter: "A", title: "Schaal begrijpen", emoji: "🗺️", from: 0, to: 0 },
  { letter: "B", title: "Van kaart naar werkelijkheid", emoji: "📏", from: 1, to: 1 },
  { letter: "C", title: "Van werkelijkheid naar kaart", emoji: "✏️", from: 2, to: 2 },
  { letter: "D", title: "Doorstroomtoets-opgaven", emoji: "🏆", from: 3, to: 3 },
];

const steps = [
  {
    title: "Schaal begrijpen — wat betekent 1:100?",
    explanation: "**Schaal** geeft de verhouding tussen een afstand **op de kaart** (of tekening) en de **echte afstand**.\n\n**Schrijfwijze**: 1 : getal\n• 1 : 100 → 1 cm op de kaart = 100 cm in het echt = **1 meter**\n• 1 : 1000 → 1 cm op de kaart = 1000 cm = **10 meter**\n• 1 : 25.000 → 1 cm op de kaart = 25.000 cm = **250 meter**\n• 1 : 100.000 → 1 cm op de kaart = 100.000 cm = **1 kilometer**\n\n**Hoe lees je het?**\n'1 : 100' betekent: alles in het echt is **100 keer zo groot** als op de tekening.\n\n**Groot getal = klein kaartje**:\n• 1 : 100 → groot, gedetailleerd (plattegrond van je slaapkamer)\n• 1 : 100.000 → klein, overzicht (kaart van een provincie)\n\n**Klein getal = groot kaartje**:\n• 1 : 10 → bijna echt formaat (maquette)\n\n**Cito-tip**: De schaal staat altijd ergens bij de plattegrond of kaart. Zoek hem eerst!",
    checks: [
      {
        q: "Een plattegrond heeft schaal **1 : 200**. Wat betekent dit?",
        options: ["1 cm op de plattegrond = 200 cm (2 meter) in het echt", "1 meter op de plattegrond = 200 meter in het echt", "Het gebouw is 200 keer zo klein als de tekening", "De tekening is 200 cm breed"],
        answer: 0,
        wrongHints: [null, "Bij schaal gaat het om cm-op-tekening, niet meter-op-tekening.", "Andersom: het echt is groter dan de tekening.", "Schaal zegt niets over de breedte van de tekening zelf."],
        uitlegPad: {
          stappen: [{ titel: "1 : 200 lezen", tekst: "1 cm tekening = 200 cm echt. 200 cm = 2 meter." }],
          woorden: [{ woord: "schaal", uitleg: "Verhouding tussen afstand op papier en afstand in werkelijkheid." }],
          theorie: "Het getal achter de dubbele punt zegt hoeveel keer groter het echt is.",
          voorbeelden: [{ type: "dagelijks", tekst: "Plattegrond van een huis: 1:200. Een muur van 3 cm op papier = 6 meter echt." }],
          basiskennis: [{ onderwerp: "Eenheid", uitleg: "Bij schaal is de eenheid altijd hetzelfde: 1 CM op papier = X CM echt." }],
          niveaus: { basis: "1 cm = 200 cm = 2 m in het echt. A.", simpeler: "1:200 = 1 cm op papier = 200 cm echt = 2 meter. = A.", nogSimpeler: "1 cm = 2 meter = A." },
        },
      },
      {
        q: "Welke schaal geeft het **meeste detail**?",
        options: ["1 : 100", "1 : 10.000", "1 : 100.000", "1 : 1.000.000"],
        answer: 0,
        wrongHints: [null, "Groter getal = kleiner kaartje = MINDER detail.", "Nog groter getal = nog minder detail.", "Dat is een heel klein kaartje van een heel groot gebied."],
        uitlegPad: {
          stappen: [{ titel: "Klein getal = groot detail", tekst: "1:100 = elke echte meter is 1 cm op papier. Veel detail! Bij 1:100.000 is een km maar 1 cm." }],
          woorden: [{ woord: "grote schaal", uitleg: "Paradoxaal: 1:100 heet 'grote schaal' (groot detail), 1:100.000 heet 'kleine schaal'." }],
          theorie: "Kleiner getal achter de : = meer detail. Groter getal = minder detail.",
          voorbeelden: [{ type: "vergelijk", tekst: "1:100 = plattegrond van 1 kamer. 1:100.000 = kaart van een provincie." }],
          basiskennis: [{ onderwerp: "Ezelsbruggetje", uitleg: "Klein schaal-getal → je ziet veel details. Groot getal → je ziet veel gebied maar weinig detail." }],
          niveaus: { basis: "1:100 = meeste detail. A.", simpeler: "Kleiner getal = meer detail. 100 < 10.000 < 100.000. = A.", nogSimpeler: "1 : 100 = A." },
        },
      },
      {
        q: "Op een kaart met schaal 1 : 50.000 is 1 cm gelijk aan hoeveel in het echt?",
        options: ["500 meter", "50 meter", "5 kilometer", "50 kilometer"],
        answer: 0,
        wrongHints: [null, "50.000 cm = ? meter. Reken om.", "Dat is 1:500.000.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "50.000 cm omrekenen", tekst: "1 cm = 50.000 cm. 50.000 cm ÷ 100 = 500 meter." }],
          woorden: [{ woord: "cm → meter", uitleg: "1 meter = 100 cm. Dus deel door 100." }],
          theorie: "Schaal 1:50.000. 1 cm = 50.000 cm = 500 m = 0,5 km.",
          voorbeelden: [{ type: "stappen", tekst: "50.000 cm ÷ 100 = 500 m. Of: 50.000 ÷ 100.000 = 0,5 km." }],
          basiskennis: [{ onderwerp: "Snel omrekenen", uitleg: "Deel het schaal-getal door 100 → meter. Deel door 100.000 → kilometer." }],
          niveaus: { basis: "50.000 cm = 500 m. A.", simpeler: "50.000 ÷ 100 = 500 meter. = A.", nogSimpeler: "500 meter = A." },
        },
      },
      {
        q: "Een maquette van een gebouw heeft schaal 1 : 50. Het gebouw is in het echt 15 meter hoog. Hoe hoog is de maquette?",
        options: ["30 cm", "3 cm", "300 cm", "0,3 cm"],
        answer: 0,
        wrongHints: [null, "15 m = 1500 cm. Deel dat door 50.", "Dat is de hoogte als de schaal 1:5 was.", "Dat is te klein."],
        uitlegPad: {
          stappen: [{ titel: "Echt → model: ÷ schaal", tekst: "15 m = 1500 cm. 1500 ÷ 50 = 30 cm." }],
          woorden: [{ woord: "maquette", uitleg: "Verkleind model van een gebouw. Schaal geeft de verkleinings-factor." }],
          theorie: "Van echt naar model: deel door het schaal-getal. 1500 ÷ 50 = 30 cm.",
          voorbeelden: [{ type: "stappen", tekst: "15 m = 1500 cm. 1500 ÷ 50 = 30 cm hoogte maquette." }],
          basiskennis: [{ onderwerp: "Eerst naar cm", uitleg: "Reken de echte maat altijd eerst om naar cm, dan delen." }],
          niveaus: { basis: "1500 cm ÷ 50 = 30 cm. A.", simpeler: "15 m = 1500 cm. ÷ 50 = 30 cm. = A.", nogSimpeler: "30 cm = A." },
        },
      },
      {
        q: "Op een plattegrond met schaal 1 : 500 meet je een gang van 4 cm. Hoe lang is de gang in het echt?",
        options: ["20 meter", "200 meter", "2 meter", "2000 meter"],
        answer: 0,
        wrongHints: [null, "4 × 500 = 2000 cm. Reken om naar meter.", "Check: 4 × 500 = ?", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "Kaart → echt: × schaal", tekst: "4 cm × 500 = 2000 cm = 20 meter." }],
          woorden: [{ woord: "vermenigvuldigen", uitleg: "Van kaart naar echt: vermenigvuldig de kaart-afstand met het schaal-getal." }],
          theorie: "4 × 500 = 2000 cm. 2000 ÷ 100 = 20 m.",
          voorbeelden: [{ type: "check", tekst: "20 meter ÷ 500 = 0,04 m = 4 cm. Klopt! ✓" }],
          basiskennis: [{ onderwerp: "Twee richtingen", uitleg: "Kaart → echt = ×. Echt → kaart = ÷." }],
          niveaus: { basis: "4 × 500 = 2000 cm = 20 m. A.", simpeler: "4 cm × 500 = 2000 cm = 20 meter. = A.", nogSimpeler: "20 meter = A." },
        },
      },
    ],
  },

  {
    title: "Van kaart naar werkelijkheid",
    explanation: "**Van kaart naar werkelijkheid** = je meet iets op de kaart en wilt weten hoe groot het echt is.\n\n**Formule**:\nEchte afstand = afstand op kaart × schaal-getal\n\n**Stappen**:\n1. Meet de afstand op de kaart in **cm**.\n2. Vermenigvuldig met het **schaal-getal** (het getal achter de :).\n3. Je krijgt het antwoord in **cm**. Reken om naar m of km.\n\n**Voorbeeld**:\nSchaal 1 : 25.000. Afstand op kaart = 6 cm.\n• 6 × 25.000 = 150.000 cm\n• 150.000 cm ÷ 100 = 1500 m\n• 1500 m ÷ 1000 = **1,5 km**\n\n**Snelle trucs**:\n• Schaal 1:100.000 → 1 cm = 1 km. Dus 6 cm = 6 km.\n• Schaal 1:50.000 → 1 cm = 0,5 km = 500 m. Dus 6 cm = 3 km.\n• Schaal 1:25.000 → 1 cm = 0,25 km = 250 m. Dus 6 cm = 1,5 km.\n\n**Cito-tip**: Als de kaart een schaalbalk heeft (lijntje met 'km' ernaast), gebruik die! Leg je liniaal erlangs.",
    checks: [
      {
        q: "Op een kaart (schaal 1 : 25.000) meet je 8 cm tussen twee dorpen. Hoeveel **km** is dat in het echt?",
        options: ["2 km", "20 km", "0,2 km", "200 km"],
        answer: 0,
        wrongHints: [null, "8 × 25.000 = 200.000 cm. Hoeveel km is dat?", "Dat is te weinig.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "×25.000 → cm → km", tekst: "8 × 25.000 = 200.000 cm = 2000 m = 2 km." }],
          woorden: [{ woord: "omrekenketen", uitleg: "cm → m (÷100) → km (÷1000). Of cm → km = ÷100.000." }],
          theorie: "200.000 cm ÷ 100.000 = 2 km. Of: 1 cm = 0,25 km → 8 × 0,25 = 2 km.",
          voorbeelden: [{ type: "snelle truc", tekst: "1:25.000: 1 cm = 250 m. 8 cm = 8 × 250 = 2000 m = 2 km." }],
          basiskennis: [{ onderwerp: "÷100.000 truc", uitleg: "cm naar km = altijd ÷100.000 (want 1 km = 100.000 cm)." }],
          niveaus: { basis: "8 × 25.000 = 200.000 cm = 2 km. A.", simpeler: "8 × 0,25 km = 2 km. = A.", nogSimpeler: "2 km = A." },
        },
      },
      {
        q: "Plattegrond schaal 1 : 200. Een kamer is op de tekening 5 cm breed en 3,5 cm lang. Wat is de **echte oppervlakte**?",
        options: ["70 m²", "7 m²", "17,5 m²", "700 m²"],
        answer: 0,
        wrongHints: [null, "Reken eerst cm op tekening → m in echt. Dan pas L × B.", "Check je berekening: 10 × 7 = ?", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "Eerst maten, dan oppervlakte", tekst: "Breedte: 5 × 200 = 1000 cm = 10 m. Lengte: 3,5 × 200 = 700 cm = 7 m. Oppervlakte: 10 × 7 = 70 m²." }],
          woorden: [{ woord: "oppervlakte via schaal", uitleg: "Reken EERST elke maat om. Daarna pas vermenigvuldigen." }],
          theorie: "NIET de oppervlakte van de tekening vermenigvuldigen met de schaal — dat geeft een fout antwoord!",
          voorbeelden: [{ type: "fout", tekst: "FOUT: 5 × 3,5 = 17,5 cm² × 200 = 3500. GOED: 10 m × 7 m = 70 m²." }],
          basiskennis: [{ onderwerp: "Veelgemaakte fout", uitleg: "Oppervlakte van tekening × schaal ≠ echte oppervlakte. Je moet de schaal op ELKE maat apart toepassen." }],
          niveaus: { basis: "10 m × 7 m = 70 m². A.", simpeler: "5 cm → 10 m, 3,5 cm → 7 m. 10 × 7 = 70 m². = A.", nogSimpeler: "70 m² = A." },
        },
      },
      {
        q: "Op een kaart (1 : 100.000) is de afstand tussen twee steden 12 cm. Hoeveel km is dat?",
        options: ["12 km", "120 km", "1,2 km", "1200 km"],
        answer: 0,
        wrongHints: [null, "Bij 1:100.000 is 1 cm = 1 km. Dus 12 cm = ?", "Dat is te weinig.", "Veel te veel."],
        uitlegPad: {
          stappen: [{ titel: "1:100.000 truc", tekst: "Bij schaal 1:100.000 is 1 cm precies 1 km. Dus 12 cm = 12 km." }],
          woorden: [{ woord: "1:100.000 ezelsbruggetje", uitleg: "100.000 cm = 1000 m = 1 km. Dus 1 cm = 1 km. Makkelijk!" }],
          theorie: "12 × 100.000 = 1.200.000 cm = 12.000 m = 12 km.",
          voorbeelden: [{ type: "truc", tekst: "Onthoud: 1:100.000 → cm = km. Dus gewoon de cm-maat lezen als km." }],
          basiskennis: [{ onderwerp: "Handige schalen", uitleg: "1:100.000 → 1cm=1km. 1:50.000 → 1cm=500m. 1:25.000 → 1cm=250m." }],
          niveaus: { basis: "1 cm = 1 km → 12 km. A.", simpeler: "Bij 1:100.000: 1 cm = 1 km. 12 cm = 12 km. = A.", nogSimpeler: "12 km = A." },
        },
      },
      {
        q: "Op een bouwtekening (schaal 1 : 50) is een raam 3 cm breed. Hoe breed is het raam in het echt?",
        options: ["1,5 meter", "15 meter", "150 cm", "0,15 meter"],
        answer: 0,
        wrongHints: [null, "3 × 50 = 150. Dat is in cm. Reken om naar meter.", "Beide antwoorden zijn hetzelfde! Check de eenheid.", "Dat is te klein."],
        uitlegPad: {
          stappen: [{ titel: "3 × 50 = 150 cm = 1,5 m", tekst: "3 cm × 50 = 150 cm. 150 cm ÷ 100 = 1,5 meter." }],
          woorden: [{ woord: "bouwtekening", uitleg: "Technische tekening van een gebouw. Schaal vaak 1:50 of 1:100." }],
          theorie: "Kaart → echt: ×50. Resultaat in cm → reken om naar m.",
          voorbeelden: [{ type: "check", tekst: "1,5 m = 150 cm. 150 ÷ 50 = 3 cm op tekening. ✓ klopt." }],
          basiskennis: [{ onderwerp: "Let op eenheid antwoord", uitleg: "De Doorstroomtoets vraagt soms in meter, soms in cm. Lees goed wat er gevraagd wordt!" }],
          niveaus: { basis: "3 × 50 = 150 cm = 1,5 m. A.", simpeler: "3 cm × 50 = 150 cm = 1,5 meter. = A.", nogSimpeler: "1,5 meter = A." },
        },
      },
      {
        q: "Op een wegenkaart (1 : 200.000) meet je 3,5 cm. Hoeveel km fiets je dan in het echt?",
        options: ["7 km", "70 km", "0,7 km", "35 km"],
        answer: 0,
        wrongHints: [null, "3,5 × 200.000 = ? cm. Dan naar km.", "Dat is te weinig.", "Check: 1 cm = 2 km bij deze schaal."],
        uitlegPad: {
          stappen: [{ titel: "3,5 × 200.000 → km", tekst: "3,5 × 200.000 = 700.000 cm = 7000 m = 7 km." }],
          woorden: [{ woord: "wegenkaart", uitleg: "Wegenkaarten hebben vaak schaal 1:200.000 of 1:250.000." }],
          theorie: "1:200.000 → 1 cm = 2 km. Dus 3,5 × 2 = 7 km. Snelle truc!",
          voorbeelden: [{ type: "truc", tekst: "1:200.000: deel schaal door 100.000 → 2. Dus 1 cm = 2 km. Snel!" }],
          basiskennis: [{ onderwerp: "Fietsroute", uitleg: "Kaartafstand ≠ werkelijke weg (bochten). Maar op de Doorstroomtoets = rechte lijn." }],
          niveaus: { basis: "3,5 × 2 = 7 km. A.", simpeler: "1 cm = 2 km. 3,5 cm = 7 km. = A.", nogSimpeler: "7 km = A." },
        },
      },
    ],
  },

  {
    title: "Van werkelijkheid naar kaart",
    explanation: "**Van werkelijkheid naar kaart** = je weet de echte afstand en wilt weten hoe groot het op de tekening wordt.\n\n**Formule**:\nAfstand op kaart = echte afstand ÷ schaal-getal\n\n**Stappen**:\n1. Reken de echte afstand om naar **cm**.\n2. Deel door het **schaal-getal**.\n3. Antwoord in cm (= afstand op de tekening).\n\n**Voorbeeld**:\nSchaal 1 : 500. Een tuin is 20 meter lang.\n• 20 m = 2000 cm\n• 2000 ÷ 500 = **4 cm** op de tekening.\n\n**Soms moet je de schaal BEPALEN**:\nAls je weet: afstand echt = 300 m, afstand op kaart = 6 cm.\n• 300 m = 30.000 cm\n• 30.000 ÷ 6 = 5000\n• Schaal = 1 : 5000\n\n**Cito-tip**: Denk altijd: van groot naar klein = **delen**. Van klein naar groot = **vermenigvuldigen**.",
    checks: [
      {
        q: "Een voetbalveld is 100 meter lang. Op een tekening (schaal 1 : 500) is dat hoeveel cm?",
        options: ["20 cm", "200 cm", "2 cm", "50 cm"],
        answer: 0,
        wrongHints: [null, "100 m = 10.000 cm. Dan ÷ 500.", "Dat is te klein.", "Check: 10.000 ÷ 500 = ?"],
        uitlegPad: {
          stappen: [{ titel: "Meter → cm, dan ÷ schaal", tekst: "100 m = 10.000 cm. 10.000 ÷ 500 = 20 cm." }],
          woorden: [{ woord: "echt → tekening", uitleg: "Van werkelijkheid naar tekening: altijd DELEN door het schaal-getal." }],
          theorie: "Echt → kaart = ÷ schaal. Eerst echte maat in cm, dan delen.",
          voorbeelden: [{ type: "check", tekst: "20 cm × 500 = 10.000 cm = 100 m. ✓ klopt!" }],
          basiskennis: [{ onderwerp: "Omgekeerde controle", uitleg: "Controleer: kaart-maat × schaal moet de echte maat geven." }],
          niveaus: { basis: "10.000 ÷ 500 = 20 cm. A.", simpeler: "100 m = 10.000 cm. ÷ 500 = 20 cm. = A.", nogSimpeler: "20 cm = A." },
        },
      },
      {
        q: "Een park is in het echt 3 km lang. Op een kaart met schaal 1 : 50.000 is dat hoeveel cm?",
        options: ["6 cm", "60 cm", "0,6 cm", "600 cm"],
        answer: 0,
        wrongHints: [null, "3 km = 300.000 cm. Dan ÷ 50.000.", "Dat is te weinig.", "Dat is te veel (6 meter!)."],
        uitlegPad: {
          stappen: [{ titel: "km → cm, dan ÷ schaal", tekst: "3 km = 300.000 cm. 300.000 ÷ 50.000 = 6 cm." }],
          woorden: [{ woord: "km naar cm", uitleg: "1 km = 100.000 cm. Dus 3 km = 300.000 cm." }],
          theorie: "Snelle truc: bij 1:50.000 is 1 cm = 500 m. 3 km = 3000 m. 3000 ÷ 500 = 6 cm.",
          voorbeelden: [{ type: "truc", tekst: "1:50.000 → 1 cm = 0,5 km. Dus 3 km ÷ 0,5 = 6 cm. Sneller!" }],
          basiskennis: [{ onderwerp: "Twee routes", uitleg: "Route 1: alles in cm. Route 2: gebruik de 'cm = ? km'-truc." }],
          niveaus: { basis: "300.000 ÷ 50.000 = 6 cm. A.", simpeler: "3 km ÷ 0,5 km/cm = 6 cm. = A.", nogSimpeler: "6 cm = A." },
        },
      },
      {
        q: "Een fietspad is 2,5 km in het echt. Op een kaart is het 10 cm. Welke **schaal** heeft de kaart?",
        options: ["1 : 25.000", "1 : 250", "1 : 2.500", "1 : 250.000"],
        answer: 0,
        wrongHints: [null, "2,5 km = 250.000 cm. Deel dat door 10.", "Check: 250.000 ÷ 10 = ?", "Dat is een te kleine schaal."],
        uitlegPad: {
          stappen: [{ titel: "Schaal = echt ÷ kaart", tekst: "2,5 km = 250.000 cm. 250.000 ÷ 10 = 25.000. Schaal = 1 : 25.000." }],
          woorden: [{ woord: "schaal bepalen", uitleg: "Schaal-getal = echte afstand (in cm) ÷ kaart-afstand (in cm)." }],
          theorie: "Beide maten in dezelfde eenheid (cm). Dan delen. Echt ÷ kaart = schaal-getal.",
          voorbeelden: [{ type: "stappen", tekst: "2,5 km = 250.000 cm. Kaart = 10 cm. 250.000 ÷ 10 = 25.000. Schaal = 1:25.000." }],
          basiskennis: [{ onderwerp: "Schaal-formule", uitleg: "Schaal = 1 : (echte cm ÷ kaart cm). Beide in dezelfde eenheid!" }],
          niveaus: { basis: "250.000 ÷ 10 = 25.000 → 1:25.000. A.", simpeler: "Echt: 250.000 cm. Kaart: 10 cm. 250.000 ÷ 10 = 25.000. = A.", nogSimpeler: "1 : 25.000 = A." },
        },
      },
      {
        q: "Je wilt een slaapkamer van 4 m × 3 m tekenen op schaal 1 : 100. Hoe groot wordt de tekening?",
        options: ["4 cm × 3 cm", "40 cm × 30 cm", "0,4 cm × 0,3 cm", "4 mm × 3 mm"],
        answer: 0,
        wrongHints: [null, "Dat zou schaal 1:10 zijn.", "Dat is veel te klein.", "Dat is hetzelfde als C — veel te klein."],
        uitlegPad: {
          stappen: [{ titel: "Elke maat ÷ 100", tekst: "4 m = 400 cm ÷ 100 = 4 cm. 3 m = 300 cm ÷ 100 = 3 cm." }],
          woorden: [{ woord: "schaal toepassen", uitleg: "Pas de schaal op elke maat APART toe. Niet op de oppervlakte." }],
          theorie: "1:100 → delen door 100. 400 ÷ 100 = 4. 300 ÷ 100 = 3.",
          voorbeelden: [{ type: "check", tekst: "4 cm × 100 = 400 cm = 4 m. 3 cm × 100 = 300 cm = 3 m. ✓" }],
          basiskennis: [{ onderwerp: "Tekenen op schaal", uitleg: "Bij technisch tekenen: meet → reken om → teken met liniaal." }],
          niveaus: { basis: "4 m → 4 cm, 3 m → 3 cm. A.", simpeler: "÷100: 400 cm → 4 cm, 300 cm → 3 cm. = A.", nogSimpeler: "4 cm × 3 cm = A." },
        },
      },
      {
        q: "Op een plattegrond (schaal 1 : 250) is een zwembad 8 cm × 4 cm. Hoeveel **m²** is het in werkelijkheid?",
        options: ["200 m²", "20 m²", "2000 m²", "32 m²"],
        answer: 0,
        wrongHints: [null, "Reken eerst de maten om, dan oppervlakte.", "Dat is te veel.", "Dat is de oppervlakte van de tekening in cm², niet het echte zwembad."],
        uitlegPad: {
          stappen: [{ titel: "Maten eerst, dan L × B", tekst: "8 cm × 250 = 2000 cm = 20 m. 4 cm × 250 = 1000 cm = 10 m. 20 × 10 = 200 m²." }],
          woorden: [{ woord: "oppervlakte", uitleg: "Oppervlakte = lengte × breedte. Beide maten EERST omrekenen naar echt." }],
          theorie: "NIET 8 × 4 × 250! Wel: (8 × 250) × (4 × 250) = 20 m × 10 m = 200 m².",
          voorbeelden: [{ type: "fout", tekst: "FOUT: 32 cm² × 250 = 8000 cm² = 0,8 m². GOED: 20 m × 10 m = 200 m²." }],
          basiskennis: [{ onderwerp: "Waarom niet × schaal?", uitleg: "Oppervlakte heeft 2 dimensies. De schaal moet op BEIDE maten apart." }],
          niveaus: { basis: "20 m × 10 m = 200 m². A.", simpeler: "8→20 m, 4→10 m. 20 × 10 = 200 m². = A.", nogSimpeler: "200 m² = A." },
        },
      },
    ],
  },

  {
    title: "Doorstroomtoets-opgaven — schaal in context",
    explanation: "Op de Doorstroomtoets zie je schaal-opgaven in verschillende contexten:\n\n**1. Plattegronden** (huis, school, speelplaats)\n- Schaal 1:100 tot 1:500.\n- Vraag: 'Hoe lang is de gang in het echt?' of 'Wat is de oppervlakte van de tuin?'\n\n**2. Kaarten** (stad, provincie, land)\n- Schaal 1:25.000 tot 1:1.000.000.\n- Vraag: 'Hoeveel km is het van A naar B?' of 'Welke schaal is dit?'\n\n**3. Modellen / maquettes**\n- Schaal 1:10 tot 1:100.\n- Vraag: 'Hoe groot is het model?' of 'Hoe groot is het echt?'\n\n**Stappenplan bij elke schaal-opgave**:\n1. Wat is de schaal? (staat bij de tekening)\n2. Welke richting? (kaart→echt = ×, echt→kaart = ÷)\n3. Zijn alle maten in **cm**? Zo niet: eerst omrekenen.\n4. Bereken + reken om naar gevraagde eenheid (m, km, m²).",
    checks: [
      {
        q: "Op een plattegrond (1:300) is de woonkamer 2 cm × 1,5 cm. In het echt is dat 6 m × 4,5 m. Is dat **klopt**?",
        options: ["Ja, dat klopt", "Nee, het moet 6 m × 4,5 m zijn maar de berekening geeft iets anders", "Nee, het is 60 m × 45 m", "Nee, het is 0,6 m × 0,45 m"],
        answer: 0,
        wrongHints: [null, "Reken het zelf na: 2 × 300 = ? en 1,5 × 300 = ?", "Dat is schaal 1:3000.", "Dat is schaal 1:30 maar dan andersom gedeeld."],
        uitlegPad: {
          stappen: [{ titel: "Narekenen", tekst: "2 × 300 = 600 cm = 6 m ✓. 1,5 × 300 = 450 cm = 4,5 m ✓. Klopt!" }],
          woorden: [{ woord: "controleren", uitleg: "Op de Doorstroomtoets kan gevraagd worden: 'Klopt deze berekening?' Dan moet je het zelf narekenen." }],
          theorie: "2 cm × 300 = 600 cm = 6 m. 1,5 cm × 300 = 450 cm = 4,5 m. Beide kloppen.",
          voorbeelden: [{ type: "nacheck", tekst: "Terug: 6 m ÷ 300 = 0,02 m = 2 cm ✓. 4,5 m ÷ 300 = 0,015 m = 1,5 cm ✓." }],
          basiskennis: [{ onderwerp: "Controle-vraag", uitleg: "Als de toets vraagt 'klopt dit?': altijd zelf narekenen. Niet zomaar 'ja' kiezen." }],
          niveaus: { basis: "2×300=600cm=6m, 1,5×300=450cm=4,5m. Klopt. A.", simpeler: "Narekenen: 2cm→6m ✓, 1,5cm→4,5m ✓. = A.", nogSimpeler: "Ja, klopt = A." },
        },
      },
      {
        q: "Een wandelroute is 7,5 km. Op de kaart (1:50.000) is dat hoeveel cm?",
        options: ["15 cm", "150 cm", "1,5 cm", "7,5 cm"],
        answer: 0,
        wrongHints: [null, "7,5 km = 750.000 cm. ÷ 50.000 = ?", "Dat is te weinig.", "Dat klopt alleen bij schaal 1:100.000."],
        uitlegPad: {
          stappen: [{ titel: "km → cm, dan ÷ schaal", tekst: "7,5 km = 750.000 cm. 750.000 ÷ 50.000 = 15 cm." }],
          woorden: [{ woord: "wandelroute", uitleg: "Kaartafstand is de rechte lijn. Echte route kan langer zijn door bochten." }],
          theorie: "Of snelle truc: 1:50.000 → 1 cm = 0,5 km. 7,5 ÷ 0,5 = 15 cm.",
          voorbeelden: [{ type: "truc", tekst: "Bij 1:50.000: 2 cm = 1 km. Dus 7,5 km × 2 = 15 cm." }],
          basiskennis: [{ onderwerp: "Trucje: factor bepalen", uitleg: "1:50.000 → 100.000 ÷ 50.000 = 2 cm per km. Handig!" }],
          niveaus: { basis: "7,5 km ÷ 0,5 = 15 cm. A.", simpeler: "2 cm per km. 7,5 × 2 = 15 cm. = A.", nogSimpeler: "15 cm = A." },
        },
      },
      {
        q: "Op een maquette (schaal 1:20) is een deur 10 cm hoog. Hoe hoog is de echte deur?",
        options: ["2 meter", "20 meter", "0,2 meter", "200 cm"],
        answer: 0,
        wrongHints: [null, "10 × 20 = 200 cm. In meters?", "Veel te hoog voor een deur!", "Dat is 200 cm = 2 m, dus twee antwoorden zijn hetzelfde!"],
        uitlegPad: {
          stappen: [{ titel: "Kaart → echt: × schaal", tekst: "10 cm × 20 = 200 cm = 2 meter." }],
          woorden: [{ woord: "realiteitscheck", uitleg: "Een echte deur is ~2 meter hoog. Als je antwoord 20 meter is, weet je dat het fout is." }],
          theorie: "10 × 20 = 200 cm = 2 m. Logisch: een deur is ~2 m.",
          voorbeelden: [{ type: "check", tekst: "2 m ÷ 20 = 0,10 m = 10 cm op maquette. ✓" }],
          basiskennis: [{ onderwerp: "Logica-check", uitleg: "Na berekening: is het antwoord realistisch? Een deur van 20 m bestaat niet." }],
          niveaus: { basis: "10 × 20 = 200 cm = 2 m. A.", simpeler: "10 cm × 20 = 200 cm = 2 meter. = A.", nogSimpeler: "2 meter = A." },
        },
      },
      {
        q: "Een schoolplein is 50 m × 30 m. Je tekent het op schaal 1 : 500. Hoeveel cm² is de tekening?",
        options: ["60 cm²", "6 cm²", "600 cm²", "150 cm²"],
        answer: 0,
        wrongHints: [null, "Reken eerst elke maat om. Dan pas L × B.", "Dat is te weinig.", "Check: 10 cm × 6 cm = ?"],
        uitlegPad: {
          stappen: [{ titel: "Maten apart, dan oppervlakte", tekst: "50 m = 5000 cm ÷ 500 = 10 cm. 30 m = 3000 cm ÷ 500 = 6 cm. 10 × 6 = 60 cm²." }],
          woorden: [{ woord: "cm² op tekening", uitleg: "De oppervlakte van de tekening is in cm². De echte oppervlakte in m²." }],
          theorie: "Elke maat apart omrekenen: 50m→10cm, 30m→6cm. Dan pas vermenigvuldigen.",
          voorbeelden: [{ type: "check", tekst: "Controle: 10 × 6 = 60 cm² tekening. 50 × 30 = 1500 m² echt. 60 × 500² = 60 × 250.000 ≈ 15.000.000 cm² = 1500 m². ✓" }],
          basiskennis: [{ onderwerp: "Schaal × oppervlakte", uitleg: "Oppervlakte-schaal = schaal² (kwadratisch). Maar reken liever maten apart om." }],
          niveaus: { basis: "10 cm × 6 cm = 60 cm². A.", simpeler: "50m→10cm, 30m→6cm. 10×6=60. = A.", nogSimpeler: "60 cm² = A." },
        },
      },
      {
        q: "Op twee kaarten staat dezelfde stad. Kaart A heeft schaal 1:10.000, kaart B heeft schaal 1:50.000. Op welke kaart lijkt de stad **groter**?",
        options: ["Kaart A (1:10.000)", "Kaart B (1:50.000)", "Even groot op beide", "Hangt af van de stad"],
        answer: 0,
        wrongHints: [null, "Kleiner schaal-getal = groter op papier.", "De schalen zijn verschillend, dus de afbeelding is ook anders.", "De schaal bepaalt de grootte, niet de stad zelf."],
        uitlegPad: {
          stappen: [{ titel: "Klein getal = groter op papier", tekst: "1:10.000 → 1 cm = 100 m. 1:50.000 → 1 cm = 500 m. Op kaart A past er minder in 1 cm, dus de stad neemt MEER cm in beslag." }],
          woorden: [{ woord: "schaal vergelijken", uitleg: "Kleiner getal achter de : = grotere afbeelding. Groter getal = kleinere afbeelding." }],
          theorie: "1:10.000 vergroting is 5× meer dan 1:50.000. Dus de stad is 5× groter op kaart A.",
          voorbeelden: [{ type: "vergelijk", tekst: "Een straat van 500 m: op A = 5 cm, op B = 1 cm. A is groter." }],
          basiskennis: [{ onderwerp: "Groot vs klein schaal-getal", uitleg: "Klein getal = ingezoomd (detail). Groot getal = uitgezoomd (overzicht)." }],
          niveaus: { basis: "1:10.000 < 1:50.000 → groter op papier. A.", simpeler: "Kleiner getal = groter afbeelding. 10.000 < 50.000 → kaart A. = A.", nogSimpeler: "Kaart A = A." },
        },
      },
    ],
  },
];

export default {
  id: "schaal-plattegrond-po",
  title: "Schaal en plattegrond — kaart lezen en omrekenen (groep 7-8)",
  subject: "rekenen",
  level: "groep7-8",
  emoji: "🗺️",
  referentieNiveau: "1F-1S",
  sloThema: "Rekenen — schaal en plattegrond (Doorstroomtoets)",
  triggerKeywords: [
    "schaal",
    "plattegrond",
    "kaart lezen",
    "1 op",
    "schaalberekening",
    "maquette",
    "omrekenen kaart",
    "echte afstand",
    "doorstroomtoets rekenen"
  ],
  intro: "Leer werken met schaal: van kaart naar werkelijkheid (×) en terug (÷). Met plattegronden, kaarten en maquettes. Alles wat je nodig hebt voor de Doorstroomtoets rekenen.",
  prerequisites: [
    { id: "verhoudingen-po", title: "Verhoudingen", niveau: "groep 6-8" },
    { id: "maten-omtrek-oppervlakte-po", title: "Maten + omtrek + oppervlakte", niveau: "groep 6-8" },
  ],
  chapters,
  steps,
};
