// Leerpad: Verwijswoorden — groep 7-8 (Doorstroomtoets)
// 4 stappen: hij/zij/het, dit/dat/die/deze, waar/waarnaar, mix-oefening.
// Doorstroomtoets-taal vraagtype: "Naar welk woord verwijst '...' in regel X?"

const chapters = [
  { letter: "A", title: "Hij / zij / het / ze", emoji: "👆", from: 0, to: 0 },
  { letter: "B", title: "Dit / dat / die / deze", emoji: "🔗", from: 1, to: 1 },
  { letter: "C", title: "Waar / daarin / daarmee", emoji: "🧭", from: 2, to: 2 },
  { letter: "D", title: "Mix — alle verwijswoorden", emoji: "🏆", from: 3, to: 3 },
];

const steps = [
  {
    title: "Hij / zij / het / ze — naar wie of wat?",
    explanation: "Een **verwijswoord** verwijst terug naar een woord dat eerder in de tekst staat.\n\n**Hij / zij / ze / het** verwijzen naar een persoon of ding dat al genoemd is.\n\n**Hoe vind je waar het naar verwijst?**\n1. Zoek het verwijswoord in de zin.\n2. Lees de zin(nen) ervoor terug.\n3. Welk woord past als je het verwijswoord vervangt?\n\n**Voorbeeld**:\n• 'Lisa pakte haar fiets. **Ze** reed naar school.'\n• 'Ze' verwijst naar → **Lisa** (vrouw, eerder genoemd).\n\n**Meer voorbeelden**:\n• 'De hond blaft hard. **Hij** is boos.' → hij = de hond.\n• 'Het boek lag op tafel. Tom pakte **het** op.' → het = het boek.\n• 'De kinderen spelen buiten. **Ze** hebben het naar hun zin.' → ze = de kinderen.\n\n**Let op 'het'**:\n• 'Het' kan verwijzen naar een het-woord: 'het boek... het lag er'\n• 'Het' kan ook verwijzen naar een hele zin: 'We gaan verhuizen. **Het** is spannend.' → het = dat we gaan verhuizen.\n\n**Cito-tip**: Vervang het verwijswoord door het woord waar je aan denkt. Klopt de zin dan nog? Dan heb je het goed.",
    checks: [
      {
        q: "*'De kat sprong op de tafel. **Hij** likte zijn pootje.'*\n\nNaar welk woord verwijst 'hij'?",
        options: ["de kat", "de tafel", "zijn pootje", "de stoel"],
        answer: 0,
        wrongHints: [null, "Dat is een ding (de-woord), maar 'hij' verwijst naar iets dat iets DOET.", "Dat is wat gelikt wordt, niet wie likt.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Vervangtest", tekst: "Vervang 'hij' door 'de kat': 'De kat likte zijn pootje.' Klopt ✓." }],
          woorden: [{ woord: "verwijswoord", uitleg: "Een woord dat terugwijst naar iets dat eerder in de tekst staat." }],
          theorie: "Hij/zij verwijzen naar personen of dieren. Lees terug: wie/wat deed iets in de vorige zin?",
          voorbeelden: [{ type: "vervang", tekst: "Hij → de kat. 'De kat likte zijn pootje.' ✓ logisch." }],
          basiskennis: [{ onderwerp: "Terugwijzen", uitleg: "Het verwijswoord staat LATER, het woord waar het naar verwijst staat EERDER." }],
          niveaus: { basis: "Hij = de kat. A.", simpeler: "Wie likte? De kat (hij). = A.", nogSimpeler: "de kat = A." },
        },
      },
      {
        q: "*'Emma en Sanne fietsten naar het zwembad. **Ze** gingen elke woensdag.'*\n\nNaar wie verwijst 'ze'?",
        options: ["Emma en Sanne", "het zwembad", "de woensdag", "de fietsen"],
        answer: 0,
        wrongHints: [null, "Dat is een plaats, geen personen.", "Dat is een tijdsaanduiding.", "Staat niet in de tekst als zelfstandig iets."],
        uitlegPad: {
          stappen: [{ titel: "Wie gingen?", tekst: "'Ze gingen' — wie gingen? Emma en Sanne (meervoud = 'ze')." }],
          woorden: [{ woord: "ze (meervoud)", uitleg: "'Ze' kan verwijzen naar meerdere personen tegelijk." }],
          theorie: "'Ze' = meervoud. Zoek wie er meerdere zijn in de vorige zin.",
          voorbeelden: [{ type: "vervang", tekst: "Ze → Emma en Sanne. 'Emma en Sanne gingen elke woensdag.' ✓" }],
          basiskennis: [{ onderwerp: "Enkel vs meer", uitleg: "Hij/zij = enkelvoud. Ze/zij = kan meervoud zijn." }],
          niveaus: { basis: "Ze = Emma en Sanne. A.", simpeler: "Wie gingen? Emma en Sanne. Ze = meervoud. = A.", nogSimpeler: "Emma en Sanne = A." },
        },
      },
      {
        q: "*'Opa vertelde over de oorlog. **Het** was een spannend verhaal.'*\n\nWaar verwijst 'het' naar?",
        options: ["wat opa vertelde", "de oorlog", "opa", "het verhaal"],
        answer: 0,
        wrongHints: [null, "De oorlog is een onderwerp, maar 'het' slaat op het vertellen zelf.", "Opa is een persoon (hij, niet het).", "'Het verhaal' staat pas in de tweede zin — het verwijswoord kijkt terug."],
        uitlegPad: {
          stappen: [{ titel: "'Het' = hele vorige zin", tekst: "'Het' verwijst hier naar de hele actie: dat opa over de oorlog vertelde." }],
          woorden: [{ woord: "verwijzen naar een hele zin", uitleg: "'Het/dat' kan verwijzen naar een complete handeling of mededeling." }],
          theorie: "Soms verwijst 'het' niet naar één woord maar naar wat er in de vorige zin gebeurt.",
          voorbeelden: [{ type: "vervang", tekst: "'Wat opa vertelde was een spannend verhaal.' Klopt ✓." }],
          basiskennis: [{ onderwerp: "Hele zin als verwijzing", uitleg: "Dit is een Doorstroomtoets-valkuil. 'Het' kan terugslaan op een HANDELING, niet alleen op een ding." }],
          niveaus: { basis: "Het = wat opa vertelde. A.", simpeler: "'Het was spannend' = het vertellen van opa was spannend. = A.", nogSimpeler: "wat opa vertelde = A." },
        },
      },
      {
        q: "*'Mijn broer heeft een nieuwe telefoon. **Hij** is er heel blij mee.'*\n\nNaar wie verwijst 'hij'?",
        options: ["mijn broer", "een nieuwe telefoon", "er", "mee"],
        answer: 0,
        wrongHints: [null, "Een telefoon is een het-woord (het = de telefoon), niet hij.", "Dat is zelf een verwijswoord.", "Dat is een voorzetsel-achtig woordje."],
        uitlegPad: {
          stappen: [{ titel: "Hij = persoon", tekst: "'Hij is blij' — wie is blij? Mijn broer. Telefoon zou 'het' zijn (het-woord)." }],
          woorden: [{ woord: "de/het-verschil", uitleg: "De-woorden → hij/zij. Het-woorden → het. Telefoon = DE telefoon maar als ding = 'het'. Personen altijd hij/zij." }],
          theorie: "'Hij' verwijst naar een mannelijk persoon. Check: wie doet/voelt iets in zin 2?",
          voorbeelden: [{ type: "vervang", tekst: "'Mijn broer is er heel blij mee.' ✓ logisch." }],
          basiskennis: [{ onderwerp: "Dubbelzinnigheid", uitleg: "Soms lijkt 'hij' naar 2 woorden te verwijzen. Kies dan: wie DOET/VOELT iets?" }],
          niveaus: { basis: "Hij = mijn broer. A.", simpeler: "Wie is blij? Mijn broer (hij). = A.", nogSimpeler: "mijn broer = A." },
        },
      },
      {
        q: "*'De meester deelde de werkbladen uit. De leerlingen pakten **ze** aan.'*\n\nNaar welk woord verwijst 'ze'?",
        options: ["de werkbladen", "de leerlingen", "de meester", "de tafels"],
        answer: 0,
        wrongHints: [null, "De leerlingen doen het aanpakken — zij zijn het onderwerp, niet het voorwerp.", "De meester deelt uit, pakt niet aan.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Wat pakten ze aan?", tekst: "De leerlingen pakten ZE aan. Ze = de werkbladen (meervoud ding)." }],
          woorden: [{ woord: "ze (meervoud dingen)", uitleg: "'Ze' kan ook verwijzen naar meervoud DINGEN, niet alleen personen." }],
          theorie: "Wie pakt aan? De leerlingen (onderwerp). Wat pakken ze aan? De werkbladen (= ze).",
          voorbeelden: [{ type: "vervang", tekst: "'De leerlingen pakten de werkbladen aan.' ✓" }],
          basiskennis: [{ onderwerp: "Ze = ow of lv?", uitleg: "Let op positie: 'ze pakten' = ze is ow. 'pakten ze aan' = ze is lv (verwijswoord)." }],
          niveaus: { basis: "Ze = de werkbladen. A.", simpeler: "Wat werd aangepakt? De werkbladen. Ze = werkbladen. = A.", nogSimpeler: "de werkbladen = A." },
        },
      },
      {
        q: "*'Anna gaf haar vriendin een boek. **Zij** was jarig.'*\n\nNaar wie verwijst 'zij'?",
        options: ["haar vriendin", "Anna", "het boek", "de jarige"],
        answer: 0,
        wrongHints: [null, "Dan zou de zin zijn 'Anna was jarig' — maar Anna gaf iets WEG, ze ontving niet.", "Boek = het-woord, niet zij.", "Dat is hetzelfde als het antwoord maar dan onnodig abstract."],
        uitlegPad: {
          stappen: [{ titel: "Context gebruiken", tekst: "Wie was jarig? De vriendin — want zij KRIJGT een cadeau. Anna geeft." }],
          woorden: [{ woord: "context", uitleg: "Bij dubbelzinnigheid (Anna vs vriendin = allebei vrouw) helpt de INHOUD: wie is logisch jarig?" }],
          theorie: "Als twee personen allebei 'zij' kunnen zijn: lees de context. Wie krijgt een cadeau? De jarige.",
          voorbeelden: [{ type: "logica", tekst: "Je geeft cadeaus aan iemand die jarig IS. De vriendin krijgt → zij is jarig." }],
          basiskennis: [{ onderwerp: "Doorstroomtoets-truc", uitleg: "De toets test of je context kunt gebruiken bij dubbelzinnige verwijswoorden." }],
          niveaus: { basis: "Zij = haar vriendin (jarig → krijgt cadeau). A.", simpeler: "Wie is jarig? De vriendin ontvangt een cadeau → zij = vriendin. = A.", nogSimpeler: "haar vriendin = A." },
        },
      },
    ],
  },

  {
    title: "Dit / dat / die / deze — aanwijzend",
    explanation: "**Dit, dat, die, deze** zijn **aanwijzende voornaamwoorden** die terugwijzen naar iets dat al eerder genoemd is.\n\n**Wanneer welk?**\n• **Dit/deze** = dichtbij (in ruimte of tekst).\n• **Dat/die** = verder weg.\n\n• **Dit/dat** = verwijst naar het-woorden of naar een hele zin.\n• **Die/deze** = verwijst naar de-woorden of meervoud.\n\n**Voorbeelden**:\n• 'Ik zag een film. **Die** was heel spannend.' → die = de film (de-woord).\n• 'We gingen naar het museum. **Dat** was gratis.' → dat = het museum (het-woord).\n• 'De buurvrouw bakte koekjes. **Die** waren heerlijk.' → die = de koekjes (meervoud).\n• 'Het regent al drie dagen. **Dat** is vervelend.' → dat = dat het regent (hele zin).\n\n**Hoe herken je het?**\n1. Zie je 'dit/dat/die/deze' ZONDER zelfstandig naamwoord erachter? → het is een verwijswoord.\n2. Met zelfst. nw. erachter ('die hond', 'dat boek') → het is een aanwijzend bijvoeglijk naamwoord (ander type, niet 'verwijzen').\n\n**Cito-tip**: Lees terug. Zoek het laatste de-woord (voor 'die') of het-woord (voor 'dat') dat logisch past.",
    checks: [
      {
        q: "*'We bezochten het kasteel. **Dat** was meer dan 500 jaar oud.'*\n\nNaar welk woord verwijst 'dat'?",
        options: ["het kasteel", "we", "500 jaar", "het bezoek"],
        answer: 0,
        wrongHints: [null, "We = personen (die/zij), niet 'dat'.", "Dat is een getal, geen zelfstandig naamwoord.", "'Het bezoek' staat niet letterlijk in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Dat → het-woord", tekst: "'Dat' verwijst naar het-woorden. Het kasteel = het-woord. ✓" }],
          woorden: [{ woord: "dat (verwijzend)", uitleg: "'Dat' als verwijswoord wijst naar een het-woord of een hele zin." }],
          theorie: "Dat/dit → zoek een HET-woord of een hele zin. Het kasteel past.",
          voorbeelden: [{ type: "vervang", tekst: "'Het kasteel was meer dan 500 jaar oud.' ✓ klopt." }],
          basiskennis: [{ onderwerp: "Het-woord-regel", uitleg: "HET kasteel → DAT. DE school → DIE. Onthoud: het→dat, de→die." }],
          niveaus: { basis: "Dat = het kasteel (het-woord). A.", simpeler: "Het kasteel = het-woord → verwijzing met 'dat'. = A.", nogSimpeler: "het kasteel = A." },
        },
      },
      {
        q: "*'De lerares gaf uitleg. **Die** was heel duidelijk.'*\n\nNaar welk woord verwijst 'die'?",
        options: ["de uitleg", "de lerares", "de klas", "de les"],
        answer: 0,
        wrongHints: [null, "Dan zou je zeggen 'zij was duidelijk', niet 'die'.", "Staat niet in de tekst.", "Staat niet letterlijk in deze tekst."],
        uitlegPad: {
          stappen: [{ titel: "Die → de-woord", tekst: "'Die' verwijst naar een de-woord. 'De uitleg' is het dichtstbijzijnde de-woord dat logisch past." }],
          woorden: [{ woord: "die (verwijzend)", uitleg: "'Die' als verwijswoord wijst naar een de-woord (enkelvoud of meervoud)." }],
          theorie: "Die = verwijst naar een de-woord. Wat was duidelijk? De uitleg.",
          voorbeelden: [{ type: "vervang", tekst: "'De uitleg was heel duidelijk.' ✓" }],
          basiskennis: [{ onderwerp: "Lerares vs uitleg", uitleg: "Beide zijn de-woorden. Maar 'duidelijk' past bij uitleg, niet bij een persoon." }],
          niveaus: { basis: "Die = de uitleg. A.", simpeler: "Wat was duidelijk? De uitleg (de-woord → die). = A.", nogSimpeler: "de uitleg = A." },
        },
      },
      {
        q: "*'Ik las twee boeken in de vakantie. **Die** vond ik allebei leuk.'*\n\nNaar welk woord verwijst 'die'?",
        options: ["twee boeken", "de vakantie", "ik", "de bibliotheek"],
        answer: 0,
        wrongHints: [null, "De vakantie = enkelvoud, maar 'allebei' wijst op meervoud.", "Ik = persoon, verwijst niet met 'die'.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Die + allebei = meervoud", tekst: "'Allebei' wijst op twee dingen. 'Die' verwijst naar 'twee boeken' (meervoud)." }],
          woorden: [{ woord: "die (meervoud)", uitleg: "'Die' kan ook naar meervoud verwijzen: de boeken, de kinderen, etc." }],
          theorie: "Die = de-woord OF meervoud. 'Allebei' bevestigt: het gaat om twee dingen.",
          voorbeelden: [{ type: "vervang", tekst: "'Twee boeken vond ik allebei leuk.' ✓ (meervoud+allebei klopt)." }],
          basiskennis: [{ onderwerp: "Signaalwoord 'allebei'", uitleg: "'Allebei/beiden/alle' zijn hints dat het verwijswoord naar een meervoud slaat." }],
          niveaus: { basis: "Die = twee boeken (meervoud). A.", simpeler: "'Allebei' = twee dingen. Twee boeken = meervoud → die. = A.", nogSimpeler: "twee boeken = A." },
        },
      },
      {
        q: "*'Het schoolreisje was heel leuk. **Dat** vonden alle kinderen.'*\n\nWaar verwijst 'dat' naar?",
        options: ["dat het schoolreisje leuk was", "het schoolreisje", "alle kinderen", "de school"],
        answer: 0,
        wrongHints: [null, "Niet alleen het schoolreisje, maar het LEUK ZIJN ervan.", "Zij vonden iets — ze zijn het onderwerp, niet de verwijzing.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Dat = hele vorige zin", tekst: "'Dat vonden alle kinderen' = alle kinderen vonden DAT HET LEUK WAS. De hele mededeling." }],
          woorden: [{ woord: "dat (hele zin)", uitleg: "'Dat' verwijst hier naar de hele uitspraak 'het schoolreisje was leuk'." }],
          theorie: "Als 'dat' niet logisch naar één woord verwijst, verwijst het naar de hele vorige bewering.",
          voorbeelden: [{ type: "parafrase", tekst: "Alle kinderen vonden dat het schoolreisje heel leuk was. ✓" }],
          basiskennis: [{ onderwerp: "Valkuil", uitleg: "Niet kiezen voor 'het schoolreisje' alleen — het gaat om het OORDEEL (leuk)." }],
          niveaus: { basis: "Dat = dat het schoolreisje leuk was. A.", simpeler: "Wat vonden de kinderen? Dat het leuk was (hele zin). = A.", nogSimpeler: "dat het schoolreisje leuk was = A." },
        },
      },
      {
        q: "*'Mama kocht nieuwe schoenen. **Deze** waren in de aanbieding.'*\n\nNaar welk woord verwijst 'deze'?",
        options: ["nieuwe schoenen", "mama", "de aanbieding", "de winkel"],
        answer: 0,
        wrongHints: [null, "Mama = persoon (zij), niet 'deze'.", "Dat is waar ze in de aanbieding waren, niet WAT.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Deze = dichtbij + meervoud", tekst: "'Deze' verwijst naar meervoud dat dichtbij is (net genoemd): nieuwe schoenen." }],
          woorden: [{ woord: "deze vs die", uitleg: "'Deze' = dichtbij/net genoemd. 'Die' = verder weg. Beide voor de-woorden/meervoud." }],
          theorie: "Deze = net genoemd (recent). Schoenen = meervoud de-woord. Past perfect.",
          voorbeelden: [{ type: "vervang", tekst: "'Nieuwe schoenen waren in de aanbieding.' ✓" }],
          basiskennis: [{ onderwerp: "Nieuwe = bijv nw", uitleg: "'Nieuwe' hoort bij 'schoenen'. Het hele stuk 'nieuwe schoenen' is waar 'deze' naar verwijst." }],
          niveaus: { basis: "Deze = nieuwe schoenen. A.", simpeler: "Wat was in de aanbieding? Nieuwe schoenen (deze). = A.", nogSimpeler: "nieuwe schoenen = A." },
        },
      },
    ],
  },

  {
    title: "Waar / daarin / daarmee — voorzetsels + verwijzing",
    explanation: "Soms zit een verwijswoord **vast** aan een voorzetsel: daar**in**, daar**mee**, daar**over**, waar**van**, er**op**, etc.\n\n**Hoe werkt het?**\n• 'daar' of 'er' + voorzetsel = verwijzing naar iets eerder genoemds.\n• 'waar' + voorzetsel = vraagvorm.\n\n**Voorbeelden**:\n• 'Ik heb een tas. **Daarin** zit mijn lunch.' → daarin = in de tas.\n• 'We kregen een opdracht. **Daarmee** waren we een uur bezig.' → daarmee = met de opdracht.\n• 'De stoel is kapot. Je kunt **er** niet meer op zitten.' → erop = op de stoel.\n\n**Splitsen helpt begrijpen**:\n• daar**in** = in + dat (het-woord) / in + die (de-woord)\n• waar**over** = over + wat?\n• **er**op = op + het/dat\n\n**Doorstroomtoets-vraag**: 'Waar slaat \"daarmee\" op in regel 4?'\n→ Lees terug: zoek een ding/handeling + voorzetsel 'met'.\n\n**Tip**: splits het woord in twee delen. 'Daarmee' = daar + mee. Zoek dan: met WAT? Dat is je antwoord.",
    checks: [
      {
        q: "*'Ik kreeg een doos. **Daarin** zaten tien snoepjes.'*\n\nWaar verwijst 'daarin' naar?",
        options: ["in de doos", "in de snoepjes", "in de kamer", "in de tas"],
        answer: 0,
        wrongHints: [null, "De snoepjes zitten ergens IN, ze zijn niet de locatie.", "Staat niet in de tekst.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Splits: daar + in", tekst: "Daarin = daar + in. 'Daar' verwijst naar 'een doos'. Dus: IN de doos." }],
          woorden: [{ woord: "daarin", uitleg: "'Daar' = verwijswoord + 'in' = voorzetsel. Samen: in dat ding (de doos)." }],
          theorie: "Splits het samengestelde verwijswoord. 'Daar' = het ding. Voorzetsel = de relatie.",
          voorbeelden: [{ type: "vervang", tekst: "'In de doos zaten tien snoepjes.' ✓" }],
          basiskennis: [{ onderwerp: "Splitstechniek", uitleg: "daar+in, daar+mee, daar+over, er+op, er+aan → altijd splitsen om te begrijpen." }],
          niveaus: { basis: "Daarin = in de doos. A.", simpeler: "Daar (= doos) + in. Snoepjes zaten IN DE DOOS. = A.", nogSimpeler: "in de doos = A." },
        },
      },
      {
        q: "*'De school organiseerde een sponsorloop. **Daarmee** haalden ze €500 op.'*\n\nWaar verwijst 'daarmee' naar?",
        options: ["met de sponsorloop", "met de school", "met €500", "met de kinderen"],
        answer: 0,
        wrongHints: [null, "De school organiseerde, maar 'mee' gaat over het middel/de activiteit.", "Dat is het resultaat, niet het middel.", "Staat niet expliciet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Splits: daar + mee", tekst: "Daarmee = daar + mee (=met). 'Daar' verwijst naar 'een sponsorloop'. Dus: MET de sponsorloop." }],
          woorden: [{ woord: "daarmee", uitleg: "Daar + mee. Mee = met. Waarmee haalden ze geld op? Met de sponsorloop." }],
          theorie: "Daar = verwijst naar het vorige zelfst. nw. 'Mee' = voorzetsel 'met'.",
          voorbeelden: [{ type: "vervang", tekst: "'Met de sponsorloop haalden ze €500 op.' ✓" }],
          basiskennis: [{ onderwerp: "Mee = met", uitleg: "'Mee' is een verkorte vorm van 'met'. Daarmee = daar-met = met dat ding." }],
          niveaus: { basis: "Daarmee = met de sponsorloop. A.", simpeler: "Daar (=sponsorloop) + mee (=met). Met de sponsorloop. = A.", nogSimpeler: "met de sponsorloop = A." },
        },
      },
      {
        q: "*'Opa vertelde over de oorlog. **Daarover** wist hij veel.'*\n\nWaar verwijst 'daarover' naar?",
        options: ["over de oorlog", "over opa", "over het vertellen", "over het boek"],
        answer: 0,
        wrongHints: [null, "Opa is de persoon die iets weet — niet het onderwerp van het weten.", "Het vertellen is de actie, niet waar het OVER gaat.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Splits: daar + over", tekst: "Daarover = daar + over. 'Daar' verwijst naar 'de oorlog'. Over de oorlog wist hij veel." }],
          woorden: [{ woord: "daarover", uitleg: "Daar + over. Over WAT wist opa veel? Over de oorlog." }],
          theorie: "Splits altijd. 'Over' = het voorzetsel. Zoek waar 'over' logisch bij past.",
          voorbeelden: [{ type: "vervang", tekst: "'Over de oorlog wist hij veel.' ✓" }],
          basiskennis: [{ onderwerp: "Logica-check", uitleg: "Je weet iets OVER een onderwerp. Het onderwerp = de oorlog." }],
          niveaus: { basis: "Daarover = over de oorlog. A.", simpeler: "Daar (=oorlog) + over. Opa wist veel over de oorlog. = A.", nogSimpeler: "over de oorlog = A." },
        },
      },
      {
        q: "*'Er stond een ladder tegen de muur. Tom klom **erop**.'*\n\nWaar verwijst 'erop' naar?",
        options: ["op de ladder", "op de muur", "op Tom", "op de grond"],
        answer: 0,
        wrongHints: [null, "Je klimt niet op een muur via 'erop' — je klimt op iets waar je bovenop kunt staan.", "Tom is degene die klimt, niet waar hij op klimt.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Splits: er + op", tekst: "'Er' verwijst naar 'een ladder'. Op = voorzetsel. Tom klom OP DE LADDER." }],
          woorden: [{ woord: "erop", uitleg: "Er + op. 'Er' = het ding (ladder). Je klimt OP iets." }],
          theorie: "Er = verwijzing naar eerder genoemd ding. Op = richting/locatie.",
          voorbeelden: [{ type: "vervang", tekst: "'Tom klom op de ladder.' ✓ (logisch: je klimt op een ladder)." }],
          basiskennis: [{ onderwerp: "Er = eerder ding", uitleg: "'Er' in 'erop/erin/eraan' verwijst altijd naar iets eerder genoemds." }],
          niveaus: { basis: "Erop = op de ladder. A.", simpeler: "Er (=ladder) + op. Tom klom op de ladder. = A.", nogSimpeler: "op de ladder = A." },
        },
      },
      {
        q: "*'De kinderen maakten een werkstuk. Ze waren er twee weken mee bezig.'*\n\nWaar verwijst 'er...mee' naar?",
        options: ["met het werkstuk", "met de kinderen", "met twee weken", "met de school"],
        answer: 0,
        wrongHints: [null, "De kinderen ZIJN bezig (onderwerp), ze zijn niet het ding waarmee.", "Twee weken is de duur (hoe lang), niet waarmee.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Er...mee = ermee = daarmee", tekst: "'Er...mee' = met + eerder ding. Met WAT waren ze bezig? Met het werkstuk." }],
          woorden: [{ woord: "er...mee (gesplitst)", uitleg: "Soms staat er/daar los van het voorzetsel: 'er twee weken mee bezig'. Er+mee = ermee = met dat ding." }],
          theorie: "De delen kunnen gesplitst zijn door andere woorden. Zoek 'er' + voorzetsel verderop.",
          voorbeelden: [{ type: "vervang", tekst: "'Ze waren twee weken met het werkstuk bezig.' ✓" }],
          basiskennis: [{ onderwerp: "Gesplitst verwijswoord", uitleg: "Op de Doorstroomtoets staat 'er' soms ver van het voorzetsel. Herken beide delen." }],
          niveaus: { basis: "Er...mee = met het werkstuk. A.", simpeler: "Er (=werkstuk) + mee (=met). Met het werkstuk bezig. = A.", nogSimpeler: "met het werkstuk = A." },
        },
      },
    ],
  },

  {
    title: "Mix — alle verwijswoorden door elkaar",
    explanation: "Nu oefen je met **alle soorten verwijswoorden** door elkaar.\n\n**Samenvatting — welk type wijst hoe?**\n\n| Verwijswoord | Verwijst naar |\n|---|---|\n| hij/zij/ze | persoon of dier |\n| het | het-woord of hele zin |\n| die/deze | de-woord of meervoud |\n| dat/dit | het-woord of hele zin |\n| daarin/daarop/daarmee... | voorzetsel + eerder ding |\n| er...op/er...mee... | gesplitst: voorzetsel + eerder ding |\n\n**Stappenplan voor Doorstroomtoets-vragen**:\n1. Vind het verwijswoord.\n2. Bepaal het type (persoonlijk/aanwijzend/voorzetsels-combo).\n3. Lees 1-2 zinnen terug.\n4. Welk woord/welke zin past als je het verwijswoord vervangt?\n5. Check: klopt de zin nog inhoudelijk?\n\n**Doorstroomtoets-tip**: Het antwoord staat bijna altijd in de zin VOOR het verwijswoord. Lees terug, niet vooruit.",
    checks: [
      {
        q: "*'De buurman repareerde zijn auto. **Die** deed het al weken niet.'*\n\nNaar welk woord verwijst 'die'?",
        options: ["zijn auto", "de buurman", "de garage", "zijn gereedschap"],
        answer: 0,
        wrongHints: [null, "De buurman repareert — hij werkt wel. Het ding dat het niet 'deed' is de auto.", "Staat niet in de tekst.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Die → de-woord + logica", tekst: "'Die deed het niet' = wat werkte niet? De auto (de-woord). De buurman werkt wel (hij repareert)." }],
          woorden: [{ woord: "die = de-woord", uitleg: "'Die' wijst naar een de-woord. 'De auto' = de-woord. Klopt." }],
          theorie: "'Die' + 'deed het niet' → iets wat niet functioneert. Auto = logisch.",
          voorbeelden: [{ type: "vervang", tekst: "'Zijn auto deed het al weken niet.' ✓" }],
          basiskennis: [{ onderwerp: "Logica bij dubbelzinnigheid", uitleg: "Buurman (de) en auto (de) zijn allebei de-woorden. Inhoud beslist: wat 'doet het niet'?" }],
          niveaus: { basis: "Die = zijn auto (deed het niet). A.", simpeler: "Wat werkte niet? De auto. Die = auto. = A.", nogSimpeler: "zijn auto = A." },
        },
      },
      {
        q: "*'We hadden een proefwerk. **Dat** viel mee.'*\n\nWaar verwijst 'dat' naar?",
        options: ["het proefwerk", "we", "de klas", "de uitslag"],
        answer: 0,
        wrongHints: [null, "'We' = personen, verwijzen met zij/ze.", "Staat niet in de tekst.", "Staat niet in de tekst (alleen 'proefwerk')."],
        uitlegPad: {
          stappen: [{ titel: "Dat → het-woord", tekst: "'Dat' verwijst naar een het-woord. HET proefwerk. Wat viel mee? Het proefwerk." }],
          woorden: [{ woord: "dat (het-woord)", uitleg: "HET proefwerk → DAT. Onthoud: het→dat, de→die." }],
          theorie: "Dat = het-woord. Zoek het dichtstbijzijnde het-woord dat logisch past.",
          voorbeelden: [{ type: "vervang", tekst: "'Het proefwerk viel mee.' ✓" }],
          basiskennis: [{ onderwerp: "Meevallen", uitleg: "'Meevallen' = beter dan verwacht. Een proefwerk kan meevallen (niet te moeilijk)." }],
          niveaus: { basis: "Dat = het proefwerk. A.", simpeler: "HET proefwerk → dat. Wat viel mee? Het proefwerk. = A.", nogSimpeler: "het proefwerk = A." },
        },
      },
      {
        q: "*'Lisa oefende elke dag piano. **Daardoor** werd ze steeds beter.'*\n\nWaar verwijst 'daardoor' naar?",
        options: ["doordat Lisa elke dag oefende", "door de piano", "door Lisa", "door de muziekles"],
        answer: 0,
        wrongHints: [null, "De piano is het instrument, niet de oorzaak van beter worden.", "Lisa is de persoon die beter wordt, niet de oorzaak.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Daar + door = oorzaak", tekst: "'Daardoor' = door DAT. Door WAT werd ze beter? Door het oefenen (hele vorige zin)." }],
          woorden: [{ woord: "daardoor (oorzaak)", uitleg: "'Daardoor' wijst naar een OORZAAK. De oorzaak = het elke-dag-oefenen." }],
          theorie: "'Door' = oorzaak-voorzetsel. 'Daar' verwijst naar de hele vorige actie.",
          voorbeelden: [{ type: "vervang", tekst: "'Doordat Lisa elke dag oefende, werd ze steeds beter.' ✓" }],
          basiskennis: [{ onderwerp: "Hele zin als oorzaak", uitleg: "Net als 'dat' kan 'daar' naar een hele handeling verwijzen, niet alleen naar één woord." }],
          niveaus: { basis: "Daardoor = door het dagelijks oefenen. A.", simpeler: "Waardoor werd ze beter? Door elke dag te oefenen. = A.", nogSimpeler: "doordat Lisa elke dag oefende = A." },
        },
      },
      {
        q: "*'Tom vindt voetbal leuk. Zijn zus houdt er niet van.'*\n\nWaar verwijst 'er...van' naar?",
        options: ["van voetbal", "van Tom", "van zijn zus", "van het veld"],
        answer: 0,
        wrongHints: [null, "Tom is degene die het WEL leuk vindt — de zus houdt ergens niet van.", "Zij houdt ergens niet van — ze is het onderwerp.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Er...van = ervan = daarvan", tekst: "'Er...van' = van DAT. Van WAT houdt zijn zus niet? Van voetbal." }],
          woorden: [{ woord: "er...van (gesplitst)", uitleg: "'Er' en 'van' staan apart maar horen bij elkaar: ervan = van dat ding." }],
          theorie: "Houden van + er = ervan. Er verwijst naar voetbal.",
          voorbeelden: [{ type: "vervang", tekst: "'Zijn zus houdt niet van voetbal.' ✓" }],
          basiskennis: [{ onderwerp: "Vaste uitdrukking", uitleg: "'Houden van' is een vast werkwoord+voorzetsel. 'Er' vervangt het voorwerp." }],
          niveaus: { basis: "Er...van = van voetbal. A.", simpeler: "Waar houdt zijn zus niet van? Van voetbal. = A.", nogSimpeler: "van voetbal = A." },
        },
      },
      {
        q: "*'De kinderen kregen een verrassing. **Die** hadden ze niet verwacht.'*\n\nNaar welk woord verwijst 'die'?",
        options: ["een verrassing", "de kinderen", "de juf", "het feest"],
        answer: 0,
        wrongHints: [null, "De kinderen = 'ze' (onderwerp van zin 2). 'Die' is iets anders.", "Staat niet in de tekst.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Die = de-woord eerder", tekst: "'Die' verwijst naar een de-woord. 'Een verrassing' is een de-woord (de verrassing). 'Ze' = de kinderen." }],
          woorden: [{ woord: "dubbel verwijswoord", uitleg: "In één zin kunnen meerdere verwijswoorden staan: 'die' (=verrassing) + 'ze' (=kinderen)." }],
          theorie: "Die = lijdend voorwerp (wat hadden ze niet verwacht?). Ze = onderwerp (wie verwachtte niet?).",
          voorbeelden: [{ type: "vervang", tekst: "'De verrassing hadden de kinderen niet verwacht.' ✓" }],
          basiskennis: [{ onderwerp: "Twee verwijswoorden", uitleg: "Lees goed welk verwijswoord gevraagd wordt. Hier: 'die', niet 'ze'." }],
          niveaus: { basis: "Die = een verrassing. A.", simpeler: "Wat hadden ze niet verwacht? De verrassing (die). = A.", nogSimpeler: "een verrassing = A." },
        },
      },
      {
        q: "*'Het was mooi weer. **Daarom** gingen we naar het strand.'*\n\nWaar verwijst 'daarom' naar?",
        options: ["omdat het mooi weer was", "om het strand", "om ons", "om de zomer"],
        answer: 0,
        wrongHints: [null, "Het strand is de bestemming, niet de reden.", "'Ons' is wie er gaat, niet waarom.", "Staat niet in de tekst."],
        uitlegPad: {
          stappen: [{ titel: "Daarom = om die reden", tekst: "'Daarom' = om DIE REDEN. Welke reden? Het was mooi weer (hele vorige zin)." }],
          woorden: [{ woord: "daarom (reden)", uitleg: "'Daarom' verwijst naar een reden/oorzaak in de vorige zin." }],
          theorie: "Daar + om = om die reden. Verwijst bijna altijd naar een hele vorige zin.",
          voorbeelden: [{ type: "vervang", tekst: "'Omdat het mooi weer was, gingen we naar het strand.' ✓" }],
          basiskennis: [{ onderwerp: "Daardoor vs daarom", uitleg: "Daardoor = gevolg (het gebeurde door X). Daarom = besluit (we kozen om X). Beide verwijzen naar oorzaak/reden." }],
          niveaus: { basis: "Daarom = omdat het mooi weer was. A.", simpeler: "Waarom gingen we? Omdat het mooi weer was. = A.", nogSimpeler: "omdat het mooi weer was = A." },
        },
      },
    ],
  },
];

export default {
  id: "verwijswoorden-po",
  title: "Verwijswoorden — waar slaat het op? (groep 7-8)",
  subject: "taal",
  level: "groep7-8",
  emoji: "🔗",
  referentieNiveau: "1F-2F",
  sloThema: "Taal — verwijswoorden herkennen (Doorstroomtoets begrijpend lezen)",
  triggerKeywords: [
    "verwijswoorden",
    "waar verwijst",
    "waar slaat op",
    "hij zij het",
    "dit dat die deze",
    "daarin daarmee",
    "daarom daardoor",
    "doorstroomtoets taal",
    "begrijpend lezen verwijzing"
  ],
  intro: "Leer herkennen waar verwijswoorden (hij/zij/die/dat/daarin/daarmee) naar terugwijzen in een tekst. Dit is een van de meest gestelde vraagtypen op de Doorstroomtoets taal.",
  prerequisites: [
    { id: "woordsoorten-po", title: "Woordsoorten herkennen", niveau: "groep 5-8" },
    { id: "begrijpend-lezen-teksten-po", title: "Begrijpend lezen", niveau: "groep 6-8" },
  ],
  chapters,
  steps,
};
