// Leerpad: Zinsontleding — groep 7-8 (Doorstroomtoets)
// 5 stappen: persoonsvorm, onderwerp, lijdend voorwerp, meewerkend voorwerp, mix-oefening.
// Doel: leerling kan zinsdelen aanwijzen op Doorstroomtoets-niveau.

const chapters = [
  { letter: "A", title: "Persoonsvorm vinden", emoji: "🔍", from: 0, to: 0 },
  { letter: "B", title: "Onderwerp vinden", emoji: "👤", from: 1, to: 1 },
  { letter: "C", title: "Lijdend voorwerp", emoji: "🎯", from: 2, to: 2 },
  { letter: "D", title: "Meewerkend voorwerp", emoji: "🤝", from: 3, to: 3 },
  { letter: "E", title: "Mix — alle zinsdelen", emoji: "🏆", from: 4, to: 4 },
];

const steps = [
  {
    title: "Persoonsvorm — het werkwoord dat verandert",
    explanation: "De **persoonsvorm** (pv) is het werkwoord dat **verandert als je het onderwerp van enkelvoud naar meervoud zet** (of andersom).\n\n**Hoe vind je de persoonsvorm?**\n1. Zoek het werkwoord in de zin.\n2. Verander de zin van 'hij' naar 'zij' (meervoud). Het woord dat mee-verandert = persoonsvorm.\n\n**Voorbeeld**:\n• 'De hond **loopt** naar het park.' → 'De honden **lopen** naar het park.'\n• 'loopt' verandert in 'lopen' → **loopt** = persoonsvorm.\n\n**Meer voorbeelden**:\n• 'Juf **geeft** ons huiswerk.' → 'De juffen **geven** ons huiswerk.' → geeft = pv.\n• 'Ik **heb** honger.' → 'Wij **hebben** honger.' → heb = pv.\n\n**Let op — twee werkwoorden**:\n• 'Lisa **heeft** goed **geslapen**.' → 'Lisa en Tom **hebben** goed geslapen.'\n• 'heeft' verandert → heeft = pv. 'geslapen' verandert niet.\n\n**Cito-tip**: De persoonsvorm staat in gewone zinnen op plek 1 of 2. In een vraagzin staat de pv op plek 1 ('**Heb** jij honger?').",
    checks: [
      {
        q: "*'De kat springt op de tafel.'* — welk woord is de **persoonsvorm**?",
        options: ["springt", "kat", "tafel", "op"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie?).", "Dat is een zelfstandig naamwoord.", "Dat is een voorzetsel."],
        uitlegPad: {
          stappen: [{ titel: "Enkelvoud → meervoud", tekst: "De katten spring**en** op de tafel. 'springt' verandert → dat is de pv." }],
          woorden: [{ woord: "persoonsvorm", uitleg: "Het werkwoord dat verandert als je het onderwerp van enkel- naar meervoud zet." }],
          theorie: "Test: verander 'de kat' in 'de katten'. Welk woord verandert mee? Dat = persoonsvorm.",
          voorbeelden: [{ type: "test", tekst: "De kat springt → De katten springen. springt → pv." }],
          basiskennis: [{ onderwerp: "Werkwoord vs pv", uitleg: "Alle persoonsvorm-woorden zijn werkwoorden, maar niet elk werkwoord in een zin is de pv." }],
          niveaus: { basis: "springt verandert mee → springt = pv. A.", simpeler: "De katten springen (verandert). 'springt' → persoonsvorm. = A.", nogSimpeler: "springt = A." },
        },
      },
      {
        q: "*'Morgen gaan wij naar het strand.'* — wat is de persoonsvorm?",
        options: ["gaan", "morgen", "strand", "naar"],
        answer: 0,
        wrongHints: [null, "Dat zegt wanneer (bijwoord van tijd).", "Dat is een zelfstandig naamwoord.", "Dat is een voorzetsel."],
        uitlegPad: {
          stappen: [{ titel: "Wie/wat + werkwoord", tekst: "Wij gaan → ik ga. 'gaan' verandert → persoonsvorm." }],
          woorden: [{ woord: "inversie", uitleg: "Als de zin niet begint met het onderwerp, staat de pv op plek 2 (na 'morgen')." }],
          theorie: "Ook bij omgekeerde woordvolgorde: de pv is het werkwoord dat vervoegd is.",
          voorbeelden: [{ type: "test", tekst: "Morgen ga ik (enk.) / Morgen gaan wij (mv.) → gaan = pv." }],
          basiskennis: [{ onderwerp: "Plek pv", uitleg: "In een gewone zin staat de pv op plek 1 of 2." }],
          niveaus: { basis: "gaan = pv. A.", simpeler: "Wij gaan → ik ga. 'Gaan' verandert = persoonsvorm. A.", nogSimpeler: "gaan = A." },
        },
      },
      {
        q: "*'Tim en Sara hebben de hele middag gevoetbald.'* — wat is de persoonsvorm?",
        options: ["hebben", "gevoetbald", "Tim", "middag"],
        answer: 0,
        wrongHints: [null, "Dat is het voltooid deelwoord (verandert niet mee).", "Eigennaam, geen werkwoord.", "Zelfstandig naamwoord (tijd)."],
        uitlegPad: {
          stappen: [{ titel: "Twee werkwoorden — welke verandert?", tekst: "Tim heeft gevoetbald (enk.) / Tim en Sara hebben gevoetbald (mv.) → 'hebben' verandert." }],
          woorden: [{ woord: "voltooid deelwoord", uitleg: "'Gevoetbald' = voltooid deelwoord. Verandert NIET mee → is NIET de pv." }],
          theorie: "Bij twee werkwoorden: de pv is degene die WEL verandert bij enkel-/meervoud-wissel.",
          voorbeelden: [{ type: "vergelijk", tekst: "Tim HEEFT gevoetbald → Tim en Sara HEBBEN gevoetbald. hebben = pv." }],
          basiskennis: [{ onderwerp: "Hulpww = pv", uitleg: "Bij 'hebben/zijn + voltooid deelwoord' is het hulpww (hebben/zijn) bijna altijd de pv." }],
          niveaus: { basis: "hebben verandert → pv. A.", simpeler: "Tim heeft (enk) → Tim en Sara hebben (mv). 'hebben' = pv. A.", nogSimpeler: "hebben = A." },
        },
      },
      {
        q: "*'Waarom lach jij zo hard?'* — wat is de persoonsvorm?",
        options: ["lach", "waarom", "jij", "hard"],
        answer: 0,
        wrongHints: [null, "Dat is een vraagwoord.", "Dat is het onderwerp (wie lacht?).", "Dat is een bijwoord (hoe hard?)."],
        uitlegPad: {
          stappen: [{ titel: "Vraagzin", tekst: "In een vraagzin staat de pv vaak op plek 2 (na het vraagwoord). 'Lach' = werkwoord dat verandert." }],
          woorden: [{ woord: "vraagzin", uitleg: "Zin die begint met vraagwoord of pv. De pv komt vroeg." }],
          theorie: "Waarom lach jij? → Waarom lachen jullie? 'lach' verandert → pv.",
          voorbeelden: [{ type: "test", tekst: "Lach jij (enk.) → Lachen jullie (mv.) → lach = pv." }],
          basiskennis: [{ onderwerp: "Vraagzin-volgorde", uitleg: "Vraagwoord + pv + onderwerp. Dus pv op plek 2." }],
          niveaus: { basis: "lach = pv. A.", simpeler: "Jij lacht → jullie lachen. 'Lach' verandert → pv. = A.", nogSimpeler: "lach = A." },
        },
      },
      {
        q: "*'De kinderen zullen morgen vroeg opstaan.'* — wat is de persoonsvorm?",
        options: ["zullen", "opstaan", "kinderen", "morgen"],
        answer: 0,
        wrongHints: [null, "Dat is de infinitief (hele werkwoord, verandert niet).", "Dat is het onderwerp.", "Bijwoordelijke bepaling van tijd."],
        uitlegPad: {
          stappen: [{ titel: "Hulpww + infinitief", tekst: "'Zullen' is vervoegd (het kind ZAL / de kinderen ZULLEN). 'Opstaan' verandert niet." }],
          woorden: [{ woord: "infinitief", uitleg: "Het hele werkwoord: opstaan, lopen, eten. Verandert niet → NIET de pv." }],
          theorie: "Bij 'zullen/kunnen/mogen/willen + infinitief' is het modale hulpww de pv.",
          voorbeelden: [{ type: "vergelijk", tekst: "Het kind ZAL opstaan → De kinderen ZULLEN opstaan. zullen = pv." }],
          basiskennis: [{ onderwerp: "Modaal hulpww", uitleg: "Zullen, kunnen, mogen, willen, moeten = hulpwerkwoorden. Zij krijgen de pv-rol." }],
          niveaus: { basis: "zullen = pv. A.", simpeler: "Het kind zal → de kinderen zullen. 'Zullen' verandert = pv. A.", nogSimpeler: "zullen = A." },
        },
      },
    ],
  },

  {
    title: "Onderwerp — wie of wat doet het?",
    explanation: "Het **onderwerp** is het zinsdeel dat aangeeft **wie of wat** iets doet of is.\n\n**Hoe vind je het onderwerp?**\n1. Vind eerst de persoonsvorm.\n2. Stel de vraag: **'Wie/wat + persoonsvorm?'**\n3. Het antwoord = het onderwerp.\n\n**Voorbeeld**:\n• 'De hond loopt naar het park.'\n• Persoonsvorm = loopt.\n• Vraag: Wie loopt? → **De hond** = onderwerp.\n\n**Let op — het onderwerp kan meerdere woorden zijn**:\n• 'De grote bruine hond loopt.' → Wie loopt? → 'De grote bruine hond' = onderwerp.\n\n**Meer voorbeelden**:\n• 'Morgen gaan wij zwemmen.' → Wie gaan? → **wij** = onderwerp.\n• 'Op tafel ligt een boek.' → Wat ligt? → **een boek** = onderwerp.\n• 'Lisa en Tom spelen buiten.' → Wie spelen? → **Lisa en Tom** = onderwerp.\n\n**Cito-valkuil**: bij zinnen die niet met het onderwerp beginnen (inversie), staat het onderwerp NA de persoonsvorm.\n• 'Gisteren at ik een appel.' → Wie at? → **ik** = onderwerp (niet 'gisteren').\n\n**Cito-tip**: Het onderwerp bepaalt of de persoonsvorm enkelvoud of meervoud is. Ze horen bij elkaar.",
    checks: [
      {
        q: "*'De juf geeft de kinderen een opdracht.'* — wat is het **onderwerp**?",
        options: ["de juf", "de kinderen", "een opdracht", "geeft"],
        answer: 0,
        wrongHints: [null, "Aan wie? = meewerkend voorwerp.", "Wat geeft ze? = lijdend voorwerp.", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Wie + pv?", tekst: "Pv = geeft. Vraag: Wie geeft? → de juf." }],
          woorden: [{ woord: "onderwerp", uitleg: "Het zinsdeel dat aangeeft WIE of WAT iets doet." }],
          theorie: "Stap 1: vind pv. Stap 2: vraag 'wie/wat + pv?' → antwoord = onderwerp.",
          voorbeelden: [{ type: "stappen", tekst: "Pv = geeft. Wie geeft? De juf. → 'de juf' = onderwerp." }],
          basiskennis: [{ onderwerp: "Onderwerp ≠ eerste woord", uitleg: "Het onderwerp staat vaak vooraan, maar niet altijd." }],
          niveaus: { basis: "Wie geeft? De juf. A.", simpeler: "Pv = geeft. Wie geeft? → de juf = onderwerp. A.", nogSimpeler: "de juf = A." },
        },
      },
      {
        q: "*'Gisteren kocht mama een nieuwe fiets.'* — wat is het onderwerp?",
        options: ["mama", "gisteren", "een nieuwe fiets", "kocht"],
        answer: 0,
        wrongHints: [null, "Dat zegt wanneer (bijwoordelijke bepaling van tijd).", "Dat is het lijdend voorwerp (wat kocht ze?).", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Wie + pv?", tekst: "Pv = kocht. Wie kocht? → mama." }],
          woorden: [{ woord: "inversie", uitleg: "De zin begint met 'gisteren', niet met het onderwerp. Het onderwerp staat dan NA de pv." }],
          theorie: "Bij inversie (zin begint niet met onderwerp): pv op plek 2, onderwerp op plek 3.",
          voorbeelden: [{ type: "stappen", tekst: "Gisteren (1) kocht (2=pv) mama (3=ow). Wie kocht? Mama." }],
          basiskennis: [{ onderwerp: "Inversie-valkuil", uitleg: "Veel kinderen kiezen 'gisteren' omdat het vooraan staat. Maar 'gisteren' is geen persoon/ding." }],
          niveaus: { basis: "Wie kocht? Mama. A.", simpeler: "Pv = kocht. Wie kocht iets? Mama. = A.", nogSimpeler: "mama = A." },
        },
      },
      {
        q: "*'In de tuin spelen drie kinderen.'* — wat is het onderwerp?",
        options: ["drie kinderen", "in de tuin", "spelen", "de tuin"],
        answer: 0,
        wrongHints: [null, "Dat zegt waar (bijwoordelijke bepaling van plaats).", "Dat is de persoonsvorm.", "Deel van de plaatsbepaling."],
        uitlegPad: {
          stappen: [{ titel: "Wie/wat + pv?", tekst: "Pv = spelen. Wie spelen? → drie kinderen." }],
          woorden: [{ woord: "plaatsbepaling", uitleg: "'In de tuin' zegt WAAR iets gebeurt. Dat is een bijwoordelijke bepaling, geen onderwerp." }],
          theorie: "Het onderwerp kan ook achteraan staan. De 'wie/wat'-vraag werkt altijd.",
          voorbeelden: [{ type: "test", tekst: "Wie spelen? Drie kinderen (mv) → spelen (mv). Klopt!" }],
          basiskennis: [{ onderwerp: "Onderwerp + pv moeten matchen", uitleg: "Drie kinderen = meervoud → spelen (mv). Dat bevestigt: zij horen bij elkaar." }],
          niveaus: { basis: "Wie spelen? Drie kinderen. A.", simpeler: "Pv = spelen. Wie spelen? → drie kinderen. A.", nogSimpeler: "drie kinderen = A." },
        },
      },
      {
        q: "*'Er zwemmen vissen in de vijver.'* — wat is het onderwerp?",
        options: ["vissen", "er", "de vijver", "zwemmen"],
        answer: 0,
        wrongHints: [null, "'Er' is hier een plaatsaanduiding, geen onderwerp.", "Dat is deel van de plaatsbepaling.", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Wie/wat zwemmen?", tekst: "Pv = zwemmen. Wat zwemmen? → vissen." }],
          woorden: [{ woord: "er (schijnonderwerp)", uitleg: "'Er' lijkt het onderwerp maar is dat niet. Het echte onderwerp komt later in de zin." }],
          theorie: "'Er' is vaak een aanwijzing dat het echte onderwerp verderop staat. Altijd de wie/wat-vraag stellen.",
          voorbeelden: [{ type: "vergelijk", tekst: "Er zwemmen vissen. = Vissen zwemmen (in de vijver). Vissen = ow." }],
          basiskennis: [{ onderwerp: "Er-zinnen", uitleg: "In 'er is/zijn/zwemmen'-zinnen is 'er' NOOIT het onderwerp." }],
          niveaus: { basis: "Wat zwemmen? Vissen. A.", simpeler: "Pv = zwemmen. Wat zwemmen? Vissen. = A.", nogSimpeler: "vissen = A." },
        },
      },
      {
        q: "*'Mijn broer en ik fietsen naar school.'* — wat is het onderwerp?",
        options: ["mijn broer en ik", "school", "fietsen", "naar"],
        answer: 0,
        wrongHints: [null, "Dat is een zelfstandig naamwoord in de plaatsbepaling.", "Dat is de persoonsvorm.", "Dat is een voorzetsel."],
        uitlegPad: {
          stappen: [{ titel: "Wie fietsen?", tekst: "Pv = fietsen. Wie fietsen? → mijn broer en ik (twee personen = meervoud)." }],
          woorden: [{ woord: "samengesteld onderwerp", uitleg: "Het onderwerp kan uit meerdere personen/dingen bestaan: 'A en B'." }],
          theorie: "Bij 'X en Y' als onderwerp → meervoud pv. Beide samen zijn het onderwerp.",
          voorbeelden: [{ type: "check", tekst: "Mijn broer en ik (mv) → fietsen (mv). Klopt, ze horen bij elkaar." }],
          basiskennis: [{ onderwerp: "Meerdelig onderwerp", uitleg: "Het hele stuk 'mijn broer en ik' is samen het onderwerp." }],
          niveaus: { basis: "Wie fietsen? Mijn broer en ik. A.", simpeler: "Pv = fietsen. Wie fietsen? Mijn broer en ik. = A.", nogSimpeler: "mijn broer en ik = A." },
        },
      },
    ],
  },

  {
    title: "Lijdend voorwerp — wie of wat ondergaat de actie?",
    explanation: "Het **lijdend voorwerp** (lv) is het zinsdeel dat aangeeft **wie of wat de actie ondergaat**.\n\n**Hoe vind je het lijdend voorwerp?**\n1. Vind de persoonsvorm + het onderwerp.\n2. Stel de vraag: **'Wie/wat + pv + onderwerp?'**\n3. Het antwoord = lijdend voorwerp.\n\n**Voorbeeld**:\n• 'Tom leest een boek.'\n• Pv = leest. Onderwerp = Tom (wie leest?).\n• Vraag: Wat leest Tom? → **een boek** = lijdend voorwerp.\n\n**Meer voorbeelden**:\n• 'De hond bijt de postbode.' → Wie bijt de hond? → **de postbode** = lv.\n• 'Ik heb mijn huiswerk vergeten.' → Wat heb ik vergeten? → **mijn huiswerk** = lv.\n\n**Niet elke zin heeft een lijdend voorwerp**:\n• 'De baby slaapt.' → Wat slaapt de baby? → ??? Past niet. Geen lv.\n• 'Ik loop naar huis.' → Wat loop ik? → ??? Past niet. Geen lv.\n\n**Cito-valkuil**: verwar het lv niet met een plaatsbepaling.\n• 'Ik ga naar school.' → 'naar school' = bijw. bepaling van plaats, NIET lv.\n• Test: 'Wat ga ik?' → slaat nergens op → geen lv.\n\n**Cito-tip**: Het lijdend voorwerp kun je vervangen door 'het/hem/haar'. 'Tom leest een boek' → 'Tom leest **het**.' ✓",
    checks: [
      {
        q: "*'De kok snijdt de groenten.'* — wat is het **lijdend voorwerp**?",
        options: ["de groenten", "de kok", "snijdt", "de keuken"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie snijdt?).", "Dat is de persoonsvorm.", "Staat niet in deze zin."],
        uitlegPad: {
          stappen: [{ titel: "Wat + pv + ow?", tekst: "Pv = snijdt. Ow = de kok. Wat snijdt de kok? → de groenten = lv." }],
          woorden: [{ woord: "lijdend voorwerp", uitleg: "Het ding/persoon dat de actie ONDERGAAT. De groenten worden gesneden." }],
          theorie: "Vraag: wie/wat + pv + ow? → antwoord = lv.",
          voorbeelden: [{ type: "vervang", tekst: "De kok snijdt de groenten → De kok snijdt ZE. Werkt ✓ → lv." }],
          basiskennis: [{ onderwerp: "Ondergaan", uitleg: "De groenten 'ondergaan' het snijden. Ze doen niet zelf iets." }],
          niveaus: { basis: "Wat snijdt de kok? De groenten. A.", simpeler: "Pv=snijdt, ow=de kok. Wat snijdt de kok? De groenten. = A.", nogSimpeler: "de groenten = A." },
        },
      },
      {
        q: "*'Lisa heeft haar tas vergeten.'* — wat is het lijdend voorwerp?",
        options: ["haar tas", "Lisa", "heeft", "vergeten"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie vergeet?).", "Dat is de persoonsvorm.", "Dat is het voltooid deelwoord."],
        uitlegPad: {
          stappen: [{ titel: "Wat + pv + ow?", tekst: "Pv = heeft. Ow = Lisa. Wat heeft Lisa vergeten? → haar tas." }],
          woorden: [{ woord: "voltooid deelwoord", uitleg: "'Vergeten' = deel van het werkwoord. Het lv is het DING dat vergeten is." }],
          theorie: "Bij 'hebben + voltooid deelwoord': het lv is wat er ge-[actie]-d is.",
          voorbeelden: [{ type: "vervang", tekst: "Lisa heeft haar tas vergeten → Lisa heeft HET vergeten. Werkt ✓ → lv." }],
          basiskennis: [{ onderwerp: "Haar = bezittelijk", uitleg: "'Haar' hoort bij 'tas' (haar tas). Samen zijn ze het lv." }],
          niveaus: { basis: "Wat vergeet Lisa? Haar tas. A.", simpeler: "Pv=heeft. Ow=Lisa. Wat heeft Lisa vergeten? Haar tas. = A.", nogSimpeler: "haar tas = A." },
        },
      },
      {
        q: "*'De baby slaapt al twee uur.'* — heeft deze zin een lijdend voorwerp?",
        options: ["Nee, er is geen lv", "al twee uur", "de baby", "slaapt"],
        answer: 0,
        wrongHints: [null, "Dat is een tijdsbepaling (hoe lang?).", "Dat is het onderwerp.", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Test: wat slaapt de baby?", tekst: "Wat slaapt de baby? → slaat nergens op. Dus: geen lv." }],
          woorden: [{ woord: "onovergankelijk werkwoord", uitleg: "Sommige werkwoorden (slapen, lopen, vallen) kunnen GEEN lv hebben." }],
          theorie: "Als 'wie/wat + pv + ow?' geen logisch antwoord geeft → geen lv in de zin.",
          voorbeelden: [{ type: "test", tekst: "Wat slaapt de baby? ✗ (onlogisch). De baby rennt. Wat rent de baby? ✗. Geen lv." }],
          basiskennis: [{ onderwerp: "Niet elke zin heeft lv", uitleg: "Bij slapen, lopen, groeien, vallen, lachen → meestal geen lv." }],
          niveaus: { basis: "Geen lv — 'wat slaapt de baby?' past niet. A.", simpeler: "Test: wat slaapt de baby? Onzin. → geen lv. = A.", nogSimpeler: "Nee = A." },
        },
      },
      {
        q: "*'Wij bouwen een zandkasteel op het strand.'* — wat is het lijdend voorwerp?",
        options: ["een zandkasteel", "op het strand", "wij", "bouwen"],
        answer: 0,
        wrongHints: [null, "Dat zegt WAAR (plaatsbepaling).", "Dat is het onderwerp.", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Wat bouwen wij?", tekst: "Pv = bouwen. Ow = wij. Wat bouwen wij? → een zandkasteel." }],
          woorden: [{ woord: "plaatsbepaling vs lv", uitleg: "'Op het strand' zegt WAAR. Het lv is WAT gebouwd wordt." }],
          theorie: "Het lv ondergaat de actie. Het zandkasteel wordt gebouwd. Het strand niet.",
          voorbeelden: [{ type: "vervang", tekst: "Wij bouwen een zandkasteel → Wij bouwen HET. Werkt ✓ → lv." }],
          basiskennis: [{ onderwerp: "Lv vs plaatsbepaling", uitleg: "Plaatsbepaling = waar. Lv = wat/wie ondergaat actie. Twee verschillende dingen." }],
          niveaus: { basis: "Wat bouwen wij? Een zandkasteel. A.", simpeler: "Pv=bouwen, ow=wij. Wat bouwen wij? Een zandkasteel. = A.", nogSimpeler: "een zandkasteel = A." },
        },
      },
      {
        q: "*'De leraar waarschuwt de leerlingen.'* — wat is het lijdend voorwerp?",
        options: ["de leerlingen", "de leraar", "waarschuwt", "de klas"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie waarschuwt?).", "Dat is de persoonsvorm.", "Staat niet in de zin."],
        uitlegPad: {
          stappen: [{ titel: "Wie waarschuwt de leraar?", tekst: "Pv = waarschuwt. Ow = de leraar. Wie waarschuwt de leraar? → de leerlingen." }],
          woorden: [{ woord: "persoon als lv", uitleg: "Het lv kan ook een persoon zijn. De leerlingen ONDERGAAN de waarschuwing." }],
          theorie: "Wie/wat + pv + ow? werkt ook voor personen: 'wie waarschuwt de leraar?' → de leerlingen.",
          voorbeelden: [{ type: "vervang", tekst: "De leraar waarschuwt de leerlingen → De leraar waarschuwt HEN. Werkt ✓." }],
          basiskennis: [{ onderwerp: "Persoon-lv", uitleg: "Verwar niet: de leraar DOET (ow), de leerlingen ONDERGAAN (lv)." }],
          niveaus: { basis: "Wie waarschuwt de leraar? De leerlingen. A.", simpeler: "De leerlingen ondergaan de waarschuwing. Zij = lv. = A.", nogSimpeler: "de leerlingen = A." },
        },
      },
    ],
  },

  {
    title: "Meewerkend voorwerp — aan/voor wie?",
    explanation: "Het **meewerkend voorwerp** (mv) is het zinsdeel dat aangeeft **aan wie of voor wie** iets gedaan wordt.\n\n**Hoe vind je het meewerkend voorwerp?**\n1. Vind pv + onderwerp + lijdend voorwerp.\n2. Stel de vraag: **'Aan/voor wie + pv + onderwerp + lv?'**\n3. Het antwoord = meewerkend voorwerp.\n\n**Voorbeeld**:\n• 'Oma geeft de kinderen een cadeautje.'\n• Pv = geeft. Ow = oma. Lv = een cadeautje (wat geeft oma?).\n• Vraag: Aan wie geeft oma een cadeautje? → **de kinderen** = meewerkend voorwerp.\n\n**Meer voorbeelden**:\n• 'De juf leest de klas een verhaal voor.' → Aan wie leest de juf voor? → **de klas** = mv.\n• 'Ik stuur mijn vriend een berichtje.' → Aan wie stuur ik een berichtje? → **mijn vriend** = mv.\n\n**Let op — 'aan' of 'voor' kan erbij staan of weggelaten zijn**:\n• 'Ik geef het boek **aan Lisa**.' → aan Lisa = mv.\n• 'Ik geef **Lisa** het boek.' → Lisa = mv (zonder 'aan', zelfde betekenis).\n\n**Niet elke zin heeft een meewerkend voorwerp**:\n• 'Tom leest een boek.' → Aan wie leest Tom een boek? → ??? Niet duidelijk → geen mv.\n\n**Cito-tip**: Het mv kun je vervangen door 'aan hem/haar'. 'Oma geeft de kinderen een cadeautje' → 'Oma geeft **aan hen** een cadeautje.' ✓",
    checks: [
      {
        q: "*'Papa geeft de hond een koekje.'* — wat is het **meewerkend voorwerp**?",
        options: ["de hond", "papa", "een koekje", "geeft"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie geeft?).", "Dat is het lijdend voorwerp (wat geeft papa?).", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Aan wie + pv + ow + lv?", tekst: "Aan wie geeft papa een koekje? → de hond." }],
          woorden: [{ woord: "meewerkend voorwerp", uitleg: "Zinsdeel dat aangeeft AAN WIE of VOOR WIE de actie is." }],
          theorie: "Het mv is de ontvanger. De hond ontvangt het koekje.",
          voorbeelden: [{ type: "vervang", tekst: "Papa geeft de hond een koekje → Papa geeft AAN HEM een koekje. ✓ mv." }],
          basiskennis: [{ onderwerp: "Lv vs mv", uitleg: "Lv = WAT gegeven wordt (koekje). Mv = AAN WIE (de hond)." }],
          niveaus: { basis: "Aan wie geeft papa een koekje? De hond. A.", simpeler: "De hond ontvangt het koekje → meewerkend voorwerp. = A.", nogSimpeler: "de hond = A." },
        },
      },
      {
        q: "*'Ik schrijf mijn oma een brief.'* — wat is het meewerkend voorwerp?",
        options: ["mijn oma", "ik", "een brief", "schrijf"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie schrijft?).", "Dat is het lijdend voorwerp (wat schrijf je?).", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Aan wie schrijf ik een brief?", tekst: "Pv=schrijf, ow=ik, lv=een brief. Aan wie? → mijn oma." }],
          woorden: [{ woord: "ontvanger", uitleg: "Mijn oma ontvangt de brief. Zij is de 'ontvanger' = meewerkend voorwerp." }],
          theorie: "Aan wie/voor wie + pv + ow + lv? → mv.",
          voorbeelden: [{ type: "vervang", tekst: "Ik schrijf mijn oma een brief → Ik schrijf AAN HAAR een brief. ✓" }],
          basiskennis: [{ onderwerp: "Zonder 'aan'", uitleg: "Het woordje 'aan' staat er niet altijd bij. De vraag 'aan wie?' helpt toch." }],
          niveaus: { basis: "Aan wie schrijf ik een brief? Mijn oma. A.", simpeler: "Oma ontvangt de brief → mijn oma = mv. = A.", nogSimpeler: "mijn oma = A." },
        },
      },
      {
        q: "*'De juf vertelt aan de kinderen een grappig verhaal.'* — wat is het meewerkend voorwerp?",
        options: ["aan de kinderen", "de juf", "een grappig verhaal", "vertelt"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp.", "Dat is het lijdend voorwerp.", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "'Aan' staat erbij", tekst: "Hier staat 'aan' al in de zin: 'aan de kinderen'. Dat maakt het makkelijk → mv." }],
          woorden: [{ woord: "voorzetsel 'aan'", uitleg: "Als 'aan' of 'voor' erbij staat, is het mv extra duidelijk herkenbaar." }],
          theorie: "Aan wie vertelt de juf een verhaal? → aan de kinderen. Met of zonder 'aan': het hele stuk = mv.",
          voorbeelden: [{ type: "vergelijk", tekst: "De juf vertelt de kinderen een verhaal = De juf vertelt AAN de kinderen een verhaal. Zelfde mv." }],
          basiskennis: [{ onderwerp: "Met/zonder 'aan'", uitleg: "Beide vormen komen voor. De Doorstroomtoets kan het op beide manieren vragen." }],
          niveaus: { basis: "'Aan de kinderen' = mv. A.", simpeler: "'Aan' + persoon = meewerkend voorwerp. Aan de kinderen. = A.", nogSimpeler: "aan de kinderen = A." },
        },
      },
      {
        q: "*'Tom leent zijn vriend een pen.'* — wat is het lijdend voorwerp en wat het meewerkend voorwerp?",
        options: ["lv = een pen, mv = zijn vriend", "lv = zijn vriend, mv = een pen", "lv = Tom, mv = een pen", "Er is geen meewerkend voorwerp"],
        answer: 0,
        wrongHints: [null, "Denk: WAT leent Tom? En AAN WIE?", "Tom is het onderwerp.", "Er zijn twee ontvangers/objecten in deze zin."],
        uitlegPad: {
          stappen: [{ titel: "Wat leent Tom? + Aan wie?", tekst: "Wat leent Tom? → een pen (lv). Aan wie leent Tom een pen? → zijn vriend (mv)." }],
          woorden: [{ woord: "dubbel voorwerp", uitleg: "Sommige zinnen hebben zowel een lv (het ding) als een mv (de persoon)." }],
          theorie: "De pen is het DING (lv, ondergaat de actie). Zijn vriend is de ONTVANGER (mv).",
          voorbeelden: [{ type: "schema", tekst: "Tom (ow) leent (pv) zijn vriend (mv) een pen (lv). Ding=lv, persoon=mv." }],
          basiskennis: [{ onderwerp: "Ezelsbruggetje", uitleg: "Lv = het DING. Mv = de PERSOON aan wie je het ding geeft/leent/stuurt." }],
          niveaus: { basis: "Pen=lv (wat?), vriend=mv (aan wie?). A.", simpeler: "Wat leent Tom? Een pen (lv). Aan wie? Zijn vriend (mv). = A.", nogSimpeler: "pen=lv, vriend=mv. A." },
        },
      },
      {
        q: "*'Zij koopt een cadeau voor haar zus.'* — wat is het meewerkend voorwerp?",
        options: ["voor haar zus", "zij", "een cadeau", "koopt"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp.", "Dat is het lijdend voorwerp (wat koopt ze?).", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "'Voor wie' = mv", tekst: "Voor wie koopt zij een cadeau? → voor haar zus = meewerkend voorwerp." }],
          woorden: [{ woord: "voor wie", uitleg: "'Voor' + persoon kan ook meewerkend voorwerp zijn (niet alleen 'aan')." }],
          theorie: "Aan wie / voor wie + pv + ow + lv? → mv. Hier met 'voor'.",
          voorbeelden: [{ type: "vervang", tekst: "Zij koopt een cadeau voor haar zus → Zij koopt VOOR HAAR een cadeau. ✓ mv." }],
          basiskennis: [{ onderwerp: "Aan OF voor", uitleg: "Meewerkend voorwerp kan zowel met 'aan' als met 'voor' worden ingeleid." }],
          niveaus: { basis: "Voor wie koopt zij? Voor haar zus = mv. A.", simpeler: "Haar zus ontvangt het cadeau → mv. = A.", nogSimpeler: "voor haar zus = A." },
        },
      },
    ],
  },

  {
    title: "Mix — alle zinsdelen door elkaar",
    explanation: "Nu oefen je met **alle zinsdelen door elkaar**: persoonsvorm, onderwerp, lijdend voorwerp en meewerkend voorwerp in dezelfde oefening.\n\n**Stappenplan voor elke zin**:\n1. **Persoonsvorm**: welk werkwoord verandert bij enkel-/meervoud-wissel?\n2. **Onderwerp**: wie/wat + pv?\n3. **Lijdend voorwerp**: wie/wat + pv + ow? (als het past)\n4. **Meewerkend voorwerp**: aan/voor wie + pv + ow + lv? (als het past)\n\n**Niet elke zin heeft alles**:\n• Sommige zinnen hebben alleen pv + ow (geen lv, geen mv).\n• De meeste zinnen hebben géén mv.\n\n**Bijwoordelijke bepaling (bonus)**:\nAlles wat overblijft na pv + ow + lv + mv is meestal een bijwoordelijke bepaling:\n• Van **tijd**: wanneer? (gisteren, morgen, om 3 uur)\n• Van **plaats**: waar? (in de tuin, op school, thuis)\n• Van **wijze**: hoe? (snel, voorzichtig, met plezier)\n\n**Cito-tip**: Werk altijd in vaste volgorde (pv → ow → lv → mv). Dan vergeet je niets.",
    checks: [
      {
        q: "*'De bakker verkoopt brood aan de klanten.'* — wat is het **onderwerp**?",
        options: ["de bakker", "brood", "de klanten", "verkoopt"],
        answer: 0,
        wrongHints: [null, "Dat is het lijdend voorwerp.", "Dat is het meewerkend voorwerp.", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Wie verkoopt?", tekst: "Pv = verkoopt. Wie verkoopt? → de bakker = onderwerp." }],
          woorden: [{ woord: "ontleedvolgorde", uitleg: "Altijd: 1) pv 2) ow 3) lv 4) mv. Stap voor stap." }],
          theorie: "Wie/wat + pv? → ow. In deze zin: wie verkoopt? De bakker.",
          voorbeelden: [{ type: "volledig", tekst: "Pv=verkoopt. Ow=de bakker. Lv=brood. Mv=aan de klanten." }],
          basiskennis: [{ onderwerp: "Vaste volgorde", uitleg: "Begin altijd met de pv, dan het onderwerp. De rest volgt." }],
          niveaus: { basis: "Wie verkoopt? De bakker. A.", simpeler: "Pv=verkoopt. Wie verkoopt? De bakker = ow. A.", nogSimpeler: "de bakker = A." },
        },
      },
      {
        q: "*'Vorige week stuurde ik mijn tante een kaart.'* — wat is het **lijdend voorwerp**?",
        options: ["een kaart", "mijn tante", "ik", "vorige week"],
        answer: 0,
        wrongHints: [null, "Dat is het meewerkend voorwerp (aan wie?).", "Dat is het onderwerp.", "Dat is een tijdsbepaling."],
        uitlegPad: {
          stappen: [{ titel: "Wat stuurde ik?", tekst: "Pv=stuurde. Ow=ik. Wat stuurde ik? → een kaart = lv." }],
          woorden: [{ woord: "tijdsbepaling", uitleg: "'Vorige week' = bijw. bepaling van tijd. Geen zinsdeel-functie als ow/lv/mv." }],
          theorie: "Wat + pv + ow? → lv. Aan wie + pv + ow + lv? → mv.",
          voorbeelden: [{ type: "schema", tekst: "Vorige week (tijd) stuurde (pv) ik (ow) mijn tante (mv) een kaart (lv)." }],
          basiskennis: [{ onderwerp: "Inversie-zin", uitleg: "Zin begint met 'vorige week' → onderwerp ('ik') staat na de pv." }],
          niveaus: { basis: "Wat stuurde ik? Een kaart = lv. A.", simpeler: "Pv=stuurde, ow=ik. Wat stuurde ik? Een kaart. = A.", nogSimpeler: "een kaart = A." },
        },
      },
      {
        q: "*'De kinderen rennen snel naar buiten.'* — heeft deze zin een lijdend voorwerp?",
        options: ["Nee", "naar buiten", "de kinderen", "snel"],
        answer: 0,
        wrongHints: [null, "Dat is een plaatsbepaling (waarheen?).", "Dat is het onderwerp.", "Dat is een bijwoord van wijze."],
        uitlegPad: {
          stappen: [{ titel: "Wat rennen de kinderen?", tekst: "Pv=rennen. Ow=de kinderen. Wat rennen de kinderen? → onzin. Geen lv." }],
          woorden: [{ woord: "bijw. bepaling", uitleg: "'Naar buiten' = plaatsbepaling. 'Snel' = wijze-bepaling. Geen van beide is lv." }],
          theorie: "Rennen = onovergankelijk werkwoord. Je kunt niets 'rennen'. Dus geen lv.",
          voorbeelden: [{ type: "test", tekst: "Wat rennen de kinderen? ✗ onlogisch. Vergelijk: wat ETEN de kinderen? Dat kan wél → die zin zou lv hebben." }],
          basiskennis: [{ onderwerp: "Onovergankelijk", uitleg: "Rennen, lopen, slapen, lachen, groeien → kunnen geen lv bij hebben." }],
          niveaus: { basis: "Geen lv (rennen = onovergankelijk). A.", simpeler: "Wat rennen de kinderen? Past niet. Geen lv. = A.", nogSimpeler: "Nee = A." },
        },
      },
      {
        q: "*'Morgen brengt de postbode ons een pakketje.'* — wat is het **meewerkend voorwerp**?",
        options: ["ons", "de postbode", "een pakketje", "morgen"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie brengt?).", "Dat is het lijdend voorwerp (wat brengt hij?).", "Dat is een tijdsbepaling."],
        uitlegPad: {
          stappen: [{ titel: "Aan wie brengt de postbode een pakketje?", tekst: "Pv=brengt. Ow=de postbode. Lv=een pakketje. Aan wie? → ons = mv." }],
          woorden: [{ woord: "ons = mv", uitleg: "'Ons' is hier de ontvanger van het pakketje → meewerkend voorwerp." }],
          theorie: "Ons/mij/hem/haar/hen kunnen meewerkend voorwerp zijn als ze de ontvanger aanduiden.",
          voorbeelden: [{ type: "vervang", tekst: "De postbode brengt ons een pakketje → De postbode brengt AAN ONS een pakketje. ✓ mv." }],
          basiskennis: [{ onderwerp: "Voornaamwoord als mv", uitleg: "Ons/mij/jou/hem/haar/hen → vaak mv als ze de ontvanger van iets zijn." }],
          niveaus: { basis: "Aan wie brengt hij het? Ons = mv. A.", simpeler: "Wij ontvangen het pakketje → 'ons' = mv. = A.", nogSimpeler: "ons = A." },
        },
      },
      {
        q: "*'Op het schoolplein speelt een meisje met een bal.'* — wat is het **onderwerp**?",
        options: ["een meisje", "op het schoolplein", "een bal", "speelt"],
        answer: 0,
        wrongHints: [null, "Dat is een plaatsbepaling (waar?).", "Deel van 'met een bal' (wijze-bepaling).", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Wie speelt?", tekst: "Pv = speelt. Wie speelt? → een meisje = onderwerp." }],
          woorden: [{ woord: "inversie", uitleg: "De zin begint met 'op het schoolplein'. Het onderwerp staat verderop." }],
          theorie: "Bij inversie staat het ow na de pv. Wie/wat + pv? → ow.",
          voorbeelden: [{ type: "check", tekst: "Een meisje (enk.) speelt (enk.). Past! → ow + pv matchen." }],
          basiskennis: [{ onderwerp: "Met een bal", uitleg: "'Met een bal' = bepaling van wijze (hoe speelt ze?). Geen lv want 'spelen' is onovergankelijk." }],
          niveaus: { basis: "Wie speelt? Een meisje. A.", simpeler: "Pv=speelt. Wie speelt? Een meisje. = A.", nogSimpeler: "een meisje = A." },
        },
      },
      {
        q: "*'De directeur overhandigt de winnaar de beker.'* — wat is het **meewerkend voorwerp**?",
        options: ["de winnaar", "de directeur", "de beker", "overhandigt"],
        answer: 0,
        wrongHints: [null, "Dat is het onderwerp (wie overhandigt?).", "Dat is het lijdend voorwerp (wat overhandigt hij?).", "Dat is de persoonsvorm."],
        uitlegPad: {
          stappen: [{ titel: "Aan wie overhandigt de directeur de beker?", tekst: "Pv=overhandigt. Ow=de directeur. Lv=de beker. Aan wie? → de winnaar = mv." }],
          woorden: [{ woord: "overhandigen", uitleg: "Geven/overhandigen/schenken = werkwoorden die vaak zowel lv als mv bij zich hebben." }],
          theorie: "Bij 'geven/overhandigen/schenken/lenen': DING=lv, PERSOON=mv.",
          voorbeelden: [{ type: "schema", tekst: "De directeur (ow) overhandigt (pv) de winnaar (mv) de beker (lv)." }],
          basiskennis: [{ onderwerp: "Volgorde herkennen", uitleg: "Na ow + pv: eerst mv (persoon), dan lv (ding). Of: eerst lv, dan 'aan' + mv." }],
          niveaus: { basis: "Aan wie? De winnaar = mv. A.", simpeler: "De winnaar ontvangt de beker. Winnaar = mv, beker = lv. = A.", nogSimpeler: "de winnaar = A." },
        },
      },
    ],
  },
];

export default {
  id: "zinsontleding-po",
  title: "Zinsontleding — zinsdelen herkennen (groep 7-8)",
  subject: "taal",
  level: "groep7-8",
  emoji: "🧩",
  referentieNiveau: "1F-2F",
  sloThema: "Taal — zinsontleding (zinsdelen aanwijzen) Doorstroomtoets",
  triggerKeywords: [
    "zinsontleding",
    "zinsdelen",
    "persoonsvorm",
    "onderwerp",
    "lijdend voorwerp",
    "meewerkend voorwerp",
    "ontleden",
    "pv vinden",
    "gezegde",
    "doorstroomtoets taal"
  ],
  intro: "Leer zinsdelen herkennen: persoonsvorm, onderwerp, lijdend voorwerp en meewerkend voorwerp. Met de vaste stappen (pv → ow → lv → mv) kun je elke zin ontleden op de Doorstroomtoets.",
  prerequisites: [
    { id: "woordsoorten-po", title: "Woordsoorten herkennen", niveau: "groep 5-8" },
    { id: "werkwoord-tijden-po", title: "Werkwoordtijden", niveau: "groep 5-8" },
  ],
  chapters,
  steps,
};
