// versieF.js — Leesladder 2 ("de zware ladder"), VERSIE F (20 aug 2026).
// Niveau 2: stevige groep 7-8 tot begin brugklas. Versie F bestaat naast D en E
// zodat een kind hetzelfde begrip met vérse teksten opnieuw kan oefenen.
// Format identiek aan leesladderData.js: goed antwoord ALTIJD op plek 0
// (de pagina husselt zelf). WOORDHULP_F volgt de spelregels uit
// leesladderWoorden.js: nooit een woord waar een vraag over gaat.

export const VERSIE_F = [
  // ── TREDE 1 — vier teksten van ±8 zinnen, elk 3 vragen ──────────
  [
    {
      titel: "Kippenvel",
      tekst: "Als je het koud hebt, verschijnen er ineens bultjes op je armen. Rondom elk haartje trekt dan een piepklein spiertje samen, waardoor het haartje rechtop gaat staan. Bij dieren met een dikke vacht is dat heel nuttig: tussen de rechtopstaande haren blijft een laagje warme lucht hangen. Mensen hebben die dikke vacht al heel lang niet meer. Desondanks doen onze spiertjes nog altijd braaf hun werk. Kippenvel is dus eigenlijk een aandenken aan onze harige voorouders. Je krijgt het trouwens ook bij mooie muziek of bij spanning. Het lichaam maakt dan geen warmte, maar laat zien dat je iets sterk voelt.",
      vragen: [
        { q: "In zin 5 staat: 'Desondanks doen onze spiertjes nog altijd braaf hun werk.' Waar wijst 'desondanks' naar terug?", options: ["Mensen hebben geen dikke vacht meer", "Het laagje warme lucht", "De mooie muziek", "De bultjes op je armen"], answer: 0, type: "signaalwoord", uitleg: "'Desondanks' betekent: ook al is dát zo, tóch gebeurt dit. Kijk dus één stap terug: wat is er zo? Mensen hebben geen vacht meer — en tóch werken de spiertjes door." },
        { q: "Waarom was kippenvel voor dieren met een vacht nuttig?", options: ["Tussen de rechtopstaande haren blijft warme lucht hangen", "De bultjes zien er stoer uit", "De spiertjes worden er sterker van", "Ze krijgen het bij mooie muziek"], answer: 0, type: "oorzaak & gevolg", uitleg: "Na de dubbele punt in zin 3 staat de reden. Pas op: 'mooie muziek' staat óók in de tekst, maar gaat over mensen — niet over dieren met een vacht." },
        { q: "Welke zin past het best als hoofdgedachte van deze tekst?", options: ["Kippenvel is een overblijfsel uit de tijd dat mensen een vacht hadden", "Kippenvel krijg je alleen als je het koud hebt", "Dieren hebben last van kippenvel", "Van muziek word je warm"], answer: 0, type: "hoofdgedachte", uitleg: "De hoofdgedachte staat hier nergens létterlijk — je zoekt de paraplu waar alle zinnen onder passen. 'Alleen bij kou' klopt zelfs niet: de tekst noemt ook muziek en spanning." },
      ],
    },
    {
      titel: "De rat verdient beter",
      tekst: "Veel mensen vinden ratten vies, maar dat beeld klopt niet met wat onderzoekers zien. Een rat poetst zichzelf wel zes keer per dag, vaker dan een huiskat. Ratten zijn bovendien bijzonder slim: ze kennen de weg in een doolhof soms al na twee pogingen. Onderzoekers ontdekten zelfs dat ratten een soort lachgeluidje maken als je ze zachtjes kietelt. Dat geluid is zó hoog dat mensen het alleen met speciale apparaten kunnen horen. Ook helpen ratten elkaar: een rat maakt een vastzittende soortgenoot los, zelfs als hij daar niets voor terugkrijgt. Hoewel ratten dus een slecht imago hebben, verdienen ze dat eigenlijk niet. Wie goed kijkt, ziet een schoon, slim en behulpzaam dier.",
      vragen: [
        { q: "Welke uitspraak uit de tekst is een feit (iets dat je kunt controleren)?", options: ["Een rat poetst zichzelf wel zes keer per dag", "Ratten verdienen hun slechte naam eigenlijk niet", "Wie goed kijkt, ziet een behulpzaam dier", "Ratten zijn leuker dan katten"], answer: 0, type: "mening vs feit", uitleg: "Een feit kun je natellen of nameten — hoe vaak een rat poetst, kun je turven. 'Verdienen ze niet' is wat de schríjver vindt; dat is een mening, ook al staat hij letterlijk in de tekst." },
        { q: "Na hoeveel pogingen kent een rat soms al de weg in een doolhof?", options: ["Na twee pogingen", "Na zes pogingen", "Na tien pogingen", "Na één poging"], answer: 0, type: "detail opzoeken", uitleg: "Er staan meer getallen in de tekst: zes hoort bij het poetsen, twee bij het doolhof. Lees bij een getallen-vraag altijd precies terug welk getal bij wélk onderwerp hoort." },
        { q: "Wat wil de schrijver met deze tekst vooral bereiken?", options: ["Dat je anders over ratten gaat denken", "Dat je een rat als huisdier neemt", "Dat je ratten leert kietelen", "Dat je bang wordt voor ratten"], answer: 0, type: "doel van de schrijver", uitleg: "De eerste en laatste zin verklappen het doel: het beeld 'vies' klopt niet, kijk nog eens goed. De schrijver wil je mening bijstellen — niet dat je iets gaat dóén." },
      ],
    },
    {
      titel: "De generale repetitie",
      tekst: "Morgen voert groep 7 de musical op, en vanmiddag is de allerlaatste oefening. Halverwege het tweede liedje gaat het mis: de muziekbox valt uit en blijft stil, hoe vaak meester Bas ook op de knoppen drukt. Een paar kinderen kijken elkaar geschrokken aan. Dan staat Yusuf op, die anders nooit vooraan durft te staan. Hij begint het liedje gewoon zelf te zingen, eerst zachtjes, daarna steeds steviger. Eén voor één zingen de anderen mee, tot de hele zaal klinkt als een echt koor. Meester Bas besluit ter plekke dat de box morgen uit mag blijven. Soms is een plan dat mislukt het begin van iets beters.",
      vragen: [
        { q: "Wat kom je in dit verhaal over Yusuf te weten?", options: ["Hij doet iets wat hij normaal niet durft", "Hij staat elke dag vooraan te zingen", "Hij heeft de muziekbox gerepareerd", "Hij vindt de musical stom"], answer: 0, type: "conclusie trekken", uitleg: "Plak twee stukjes aan elkaar: 'die anders nooit vooraan durft te staan' + hij gaat tóch staan en zingt. Dat samen vertelt je iets wat nergens letterlijk staat: hij overwint zichzelf." },
        { q: "Wat gebeurt er net vóórdat de anderen gaan meezingen?", options: ["Yusuf zingt steeds steviger", "De muziekbox valt uit", "Meester Bas drukt op de knoppen", "De musical van morgen begint"], answer: 0, type: "volgorde", uitleg: "Zet de gebeurtenissen op een tijdlijn: box valt uit → Yusuf staat op → hij zingt steeds steviger → de rest doet mee. De vraag vraagt naar de stap er direct vóór, niet naar het begin." },
        { q: "Welke les past het best bij dit verhaal?", options: ["Als iets misgaat, kan er iets moois voor in de plaats komen", "Een musical lukt alleen met een muziekbox", "Zachtjes zingen is beter dan hard zingen", "Oefenen is eigenlijk niet nodig"], answer: 0, type: "hoofdgedachte", uitleg: "De slotzin vat de les samen, maar in andere woorden. Zoek het antwoord dat hetzelfde betékent — niet het antwoord dat toevallig woorden uit de tekst herhaalt." },
      ],
    },
    {
      titel: "Eerst de spaarpot",
      tekst: "Wie wil sparen, geeft zijn geld vaak eerst uit en spaart wat er overblijft. Meestal blijft er dan niets over, want leuke dingen zijn er altijd. Slimme spaarders draaien het daarom om. Zodra ze geld krijgen, stoppen ze er meteen een vast deel van in de spaarpot. Pas daarna mag de rest worden uitgegeven, zonder schuldgevoel. Dit trucje heet ook wel: jezelf eerst betalen. Het werkt bij zakgeld net zo goed als bij een echt salaris. Zo komt je spaardoel elke week een stukje dichterbij, tenzij je stiekem toch in de spaarpot graait.",
      vragen: [
        { q: "'…tenzij je stiekem toch in de spaarpot graait.' Wat betekent 'tenzij' hier?", options: ["Behalve als dat gebeurt — dan lukt het niet", "Omdat dat gebeurt", "Nadat dat gebeurd is", "Net zoals dat gebeurt"], answer: 0, type: "signaalwoord", uitleg: "'Tenzij' = 'behalve als'. De zin belooft dus iets goeds, mét één uitzondering erachteraan. Wie dat woordje mist, leest de belofte verkeerd." },
        { q: "Wat betekent 'jezelf eerst betalen' in deze tekst?", options: ["Meteen een deel van je geld sparen voordat je iets koopt", "Jezelf een cadeautje geven", "Je zakgeld aan een ander geven", "Al je geld meteen uitgeven"], answer: 0, type: "woord uit de zin halen", uitleg: "De zinnen vóór het trucje leggen het al uit: eerst een vast deel in de spaarpot, pas daarna uitgeven. Een moeilijke uitdrukking wordt bijna altijd vlak ervoor of erna uitgelegd." },
        { q: "Wat wil de schrijver je vooral leren?", options: ["Draai het om: spaar eerst en geef daarna pas uit", "Leuke dingen kopen is altijd fout", "Zakgeld is beter dan salaris", "Een spaarpot moet op slot kunnen"], answer: 0, type: "hoofdgedachte", uitleg: "'Slimme spaarders draaien het om' is de kern; de rest van de tekst legt uit hóé. Let op: de tekst zegt nergens dat leuke dingen kopen fout is — dat is een valstrik die strenger klinkt dan de tekst." },
      ],
    },
  ],

  // ── TREDE 2 — drie teksten van ±150 woorden, elk 3 vragen ───────
  [
    {
      titel: "Monsters op de zeekaart",
      tekst: "Op oude zeekaarten uit de tijd van de grote ontdekkingsreizen zie je vreemde dingen staan: zeeslangen, draken en vissen zo groot als schepen. Kaartenmakers tekenden die monsters niet voor de grap. Van grote delen van de oceaan wist men destijds vrijwel niets, en een lege plek op de kaart zou zeelieden kunnen laten denken dat daar niets kon gebeuren. Een monster daarentegen was een duidelijke waarschuwing: hier is het onbekend, blijf waakzaam.\n\nSommige monsters waren bovendien gebaseerd op echte dieren. Een zeeman die voor het eerst een walvis of een reuzeninktvis zag, kwam thuis met een verhaal dat bij elke haven wilder werd. De kaartenmaker, die die dieren zelf nooit had gezien, moest het met zulke verhalen doen. Zo kroop er langzaam een dierentuin vol fantasie de kaarten op. Wie zo'n kaart nu bekijkt, ziet dus niet alleen aardrijkskunde, maar ook de angsten en dromen van toen.",
      vragen: [
        { q: "Waarom tekenden kaartenmakers monsters op de kaart?", options: ["Om te waarschuwen voor onbekende, misschien gevaarlijke plekken", "Voor de grap", "Omdat ze walvissen mooi vonden", "Om de kaart duurder te maken"], answer: 0, type: "oorzaak & gevolg", uitleg: "'Voor de grap' staat letterlijk in de tekst — maar mét het woordje 'niet' ervoor! Lees bij zo'n bekende optie altijd de hele zin terug. De echte reden staat na 'daarentegen': een monster was een waarschuwing." },
        { q: "'…moest het met zulke verhalen doen.' Over welke verhalen gaat dit?", options: ["De steeds wildere verhalen van zeemannen over echte dieren", "De verhalen die de kaartenmaker zelf verzon", "Verhalen over lege plekken op de kaart", "Sprookjes over draken en ridders"], answer: 0, type: "verwijswoord", uitleg: "'Zulke verhalen' wijst hier niet naar de zin ervóór, maar twee zinnen terug: het verhaal van de zeeman dat bij elke haven wilder werd. Verwijswoorden kunnen verder terugspringen dan je denkt." },
        { q: "Welke samenvatting past het best bij deze tekst?", options: ["Monsters op oude zeekaarten waren waarschuwingen én groeiden uit wilde verhalen over echte dieren", "Zeemannen zagen vroeger vaak draken en zeeslangen", "Kaartenmakers reisden zelf de hele oceaan over", "Oude kaarten kloppen precies met de aardrijkskunde van nu"], answer: 0, type: "samenvatten", uitleg: "Een goede samenvatting dekt béíde alinea's: de waarschuwing (alinea 1) en de wilde verhalen (alinea 2). De andere opties pakken maar een stukje — of zeggen zelfs het omgekeerde van de tekst." },
      ],
    },
    {
      titel: "De laatste ronde",
      tekst: "Op de sportdag loopt Jill de slotronde van de estafette, het allerlaatste onderdeel van de middag. Haar team staat ruim voor, en langs de kant wordt haar naam gescandeerd. Vlak voor de bocht struikelt Nora van het andere team en schuift ze over het gras; haar estafettestokje stuitert weg. Jill kijkt heel even opzij, en in dat ene moment gebeurt er van alles in haar hoofd: winnen is dichtbij, maar Nora huilt.\n\nHoewel haar benen door willen, stopt Jill en trekt ze Nora overeind. Samen joggen ze het laatste stuk, terwijl het publiek eerst muisstil is en dan juist keihard begint te klappen. Jills team wordt tweede. In de kring, als iedereen een beker limonade heeft gekregen, zegt de meester dat er vandaag maar één iemand écht gewonnen heeft, en iedereen kijkt dezelfde kant op. Jill voelt haar wangen gloeien, en dat komt heus niet alleen van het rennen.",
      vragen: [
        { q: "Wie bedoelt de meester met 'de enige die vandaag écht gewonnen heeft'?", options: ["Jill", "Nora", "Het team dat eerste werd", "Het publiek"], answer: 0, type: "conclusie trekken", uitleg: "Het staat er niet letterlijk. Combineer: iedereen kijkt dezelfde kant op + meteen daarna gaan Jills wangen gloeien. Twee aanwijzingen die samen naar één persoon wijzen." },
        { q: "'Hoewel haar benen door willen, stopt Jill.' Wat laat het woord 'hoewel' zien?", options: ["Jill doet iets dat ingaat tegen wat haar lichaam wil", "Jill is te moe om door te rennen", "Waarom Jill de wedstrijd wint", "Dat de wedstrijd bijna voorbij is"], answer: 0, type: "signaalwoord", uitleg: "'Hoewel' zet twee dingen tegenover elkaar die niet bij elkaar passen: benen zeggen dóór, Jill kiest stóppen. Zo'n woord verklapt dat er een botsing in de zin zit." },
        { q: "Hoe voelt Jill zich aan het einde vooral?", options: ["Trots en een beetje verlegen tegelijk", "Boos dat haar team tweede werd", "Bang voor de meester", "Jaloers op Nora"], answer: 0, type: "gevoel afleiden", uitleg: "De schrijver noemt het gevoel niet, maar laat het zien: gloeiende wangen die 'heus niet alleen van het rennen' komen. Blozen bij een compliment = verlegen én trots. Over boosheid staat er niets." },
      ],
    },
    {
      titel: "Waarom een boog zo sterk is",
      tekst: "Al meer dan tweeduizend jaar geleden bouwden de Romeinen bruggen die er nu nog staan. Hun geheim was de boog. Een platte plank over een sloot buigt door zodra je erop stapt: al het gewicht drukt op het midden. Een boog daarentegen geeft het gewicht dóór. Elke steen duwt tegen zijn buurman, en zo glijdt de druk langs de ronding naar beneden, tot in de stevige grond. Je kunt het vergelijken met een rij vrienden die een zware tas doorgeven, in plaats van dat één iemand hem de hele weg draagt.\n\nDe belangrijkste steen zit bovenin: de sluitsteen. Haal je die weg, dan stort de hele boog in; zit hij op zijn plek, dan wordt de boog juist sterker als er méér gewicht op komt. Daarom zie je bogen overal terug: onder oude stenen bruggen, in kerkramen en zelfs in het gewelf van je eigen voet.",
      vragen: [
        { q: "Waarom staat de rij vrienden met de zware tas in de tekst?", options: ["Om te laten zien hoe een boog gewicht doorgeeft", "Omdat vrienden vroeger samen bruggen bouwden", "Om te vertellen dat tassen zwaar zijn", "Omdat de Romeinen zo werkten"], answer: 0, type: "vergelijking begrijpen", uitleg: "Stenen die druk doorgeven kun je niet zien — daarom pakt de schrijver iets dat je wél kent: een tas die van hand tot hand gaat. Een vergelijking legt het moeilijke uit met het bekende." },
        { q: "Wat gebeurt er als de sluitsteen op zijn plek zit en er méér gewicht op de boog komt?", options: ["De boog wordt juist sterker", "De hele boog stort in", "De boog buigt door zoals een plank", "De stenen glijden weg"], answer: 0, type: "detail opzoeken", uitleg: "'Stort in' staat óók in de tekst, maar hoort bij het andere geval: sluitsteen wéggehaald. De puntkomma verdeelt de zin in twee situaties — lees precies welke helft bij de vraag past." },
        { q: "Waar gaat deze tekst vooral over?", options: ["Hoe een boog gewicht doorgeeft en daardoor heel sterk is", "Hoe de Romeinen vroeger leefden", "Waarom planken doorbuigen", "Hoe je een kerkraam maakt"], answer: 0, type: "hoofdgedachte", uitleg: "De Romeinen, de plank, het kerkraam: het zijn allemaal hulpjes bij één onderwerp — de kracht van de boog. Vraag jezelf af: waar gaan de mééste zinnen over?" },
      ],
    },
  ],

  // ── TREDE 3 — drie teksten van ±230 woorden, elk 4 vragen ───────
  [
    {
      titel: "Je skelet is een bouwplaats",
      tekst: "Een skelet in een museum hangt stil en droog aan een haakje. Daardoor denken veel mensen dat botten dode, harde staven zijn. Niets is minder waar: in je botten is het elke dag zo druk als op een bouwplaats. Speciale sloopcellen breken oud bot af, terwijl bouwcellen op dezelfde plek nieuw bot metselen. Zo wordt je skelet voortdurend vernieuwd; na ongeveer tien jaar is bijna al je bot een keer vervangen.\n\nDie bouwplaats luistert bovendien naar wat jij doet. Spring je veel, ren je veel? Dan maken de bouwcellen extra stevig bot, precies op de plekken die veel te verduren krijgen. Wie daarentegen wekenlang stil ligt, verliest botsterkte; het lichaam breekt immers af wat niet gebruikt wordt. Astronauten merken dat als geen ander: na een lange reis door de ruimte zijn hun botten meetbaar lichter en brozer geworden. Daarboven weegt hun lichaam immers niets, en dus krijgen hun botten er nauwelijks werk te doen. Om sterk te blijven, moeten astronauten daarom zo'n twee uur per dag sporten aan speciale apparaten.\n\nNog een paar weetjes voor erbij: een volwassene heeft 206 botten, maar een baby wordt geboren met ongeveer 300 — een flink aantal botjes groeit later aan elkaar vast. En het kleinste botje van je lichaam, de stijgbeugel, zit diep in je oor en is kleiner dan een rijstkorrel. Zonder dat mini-botje zou je bijna niets kunnen horen.",
      vragen: [
        { q: "Met hoeveel botten wordt een baby ongeveer geboren?", options: ["Ongeveer 300", "206", "Tien", "Twee"], answer: 0, type: "detail opzoeken", uitleg: "Deze tekst staat vól getallen: 206 hoort bij volwassenen, tien jaar bij het vernieuwen, twee uur bij het sporten. Zoek het getal dat écht naast het woord 'baby' staat." },
        { q: "Waarom verliezen astronauten in de ruimte botsterkte?", options: ["Hun botten krijgen daar nauwelijks werk te doen", "Ze sporten twee uur per dag", "Sloopcellen bestaan alleen in de ruimte", "Hun skelet is al tien jaar oud"], answer: 0, type: "oorzaak & gevolg", uitleg: "De regel staat een zin eerder: het lichaam breekt af wat niet gebruikt wordt. In de ruimte weegt alles niets → botten hoeven niets te dragen. Het sporten is juist de oplóssing, niet de oorzaak." },
        { q: "Welke samenvatting past het best bij deze tekst?", options: ["Botten leven: ze worden steeds vernieuwd en passen hun sterkte aan aan wat je doet", "Een skelet in een museum is droog en stil", "Astronauten hebben de sterkste botten van iedereen", "Baby's hebben minder botten dan volwassenen"], answer: 0, type: "samenvatten", uitleg: "Een samenvatting moet de hele tekst dekken: het vernieuwen (alinea 1) én het aanpassen (alinea 2). De museumzin is alleen het begin, en de baby-optie zegt precies het omgekeerde van de tekst." },
        { q: "'Die bouwplaats luistert bovendien naar wat jij doet.' Wat wordt met 'die bouwplaats' bedoeld?", options: ["De sloop- en bouwcellen in je botten", "Het museum", "De speciale sportapparaten", "De ruimte"], answer: 0, type: "verwijswoord", uitleg: "Dit verwijswoord wijst niet naar de zin ervoor, maar helemaal terug naar de vorige alinea, waar je botten met een bouwplaats werden vergeleken. Bij 'die' of 'dat' mag je gerust een alinea terugbladeren." },
      ],
    },
    {
      titel: "Het eiland dat er nooit was",
      tekst: "Op kaarten van de grote oceaan tussen Australië en zijn buureilanden stond ruim een eeuw lang een langwerpig eiland getekend, ongeveer zo groot als Texel. Het had een naam, het stond in schoolatlassen en zelfs in moderne computerkaarten. Er was alleen één probleem: het eiland bestond niet.\n\nIn 2012 voer een onderzoeksschip naar de plek om de zeebodem te bestuderen. De wetenschappers aan boord verwachtten land te zien, maar vonden alleen golven; de zee bleek er bovendien ruim een kilometer diep. Een heel eiland kan daar onmogelijk zomaar in verdwijnen. De conclusie was even simpel als gek: het eiland had er nooit gelegen. Waarschijnlijk had een schip in de negentiende eeuw iets drijvends gezien — misschien een groot veld puimsteen, een steen uit een vulkaan die zo licht is dat hij blijft drijven. De bemanning noteerde 'land gezien', en die aantekening werd overgenomen op kaart na kaart. Niemand controleerde het; de plek lag immers ver van alle drukke vaarroutes.\n\nDit voorval leert iets belangrijks, en niet alleen over kaarten. Informatie wordt niet waar doordat veel mensen haar overschrijven. Eén slordige waarneming kan meer dan honderd jaar meereizen, van boek naar boek en van scherm naar scherm, tenzij iemand de moeite neemt om zelf te gaan kijken. De wetenschappers gaven het niet-bestaande eiland daarom een bijzonder einde: ze gumden het van de kaart.",
      vragen: [
        { q: "Hoe wisten de wetenschappers zeker dat het eiland er nooit gelegen had?", options: ["De zee bleek er ruim een kilometer diep — daar kan een eiland niet zomaar in verdwijnen", "Het eiland stond in schoolatlassen", "Een schip had daar ooit land gezien", "Het eiland was ongeveer zo groot als Texel"], answer: 0, type: "conclusie trekken", uitleg: "Alleen golven zien is nog geen bewijs — het eiland had ook gezonken kunnen zijn. Pas mét de diepte-meting klopt de redenering: zó diep verdwijnt een eiland niet. Twee zinnen samen vormen het bewijs." },
        { q: "'Niemand controleerde het; de plek lag immers ver van alle drukke vaarroutes.' Wat doet het woord 'immers'?", options: ["Het geeft de reden waarom niemand controleerde", "Het geeft een tegenstelling aan", "Het kondigt een opsomming aan", "Het laat zien dat de tekst bijna klaar is"], answer: 0, type: "signaalwoord", uitleg: "'Immers' zegt: logisch toch, wánt… Er kwam daar bijna nooit een schip langs, dus niemand kon het nakijken. Het is familie van 'want' en 'omdat', niet van 'maar'." },
        { q: "Wat is de belangrijkste les van deze tekst?", options: ["Controleer informatie zelf, want een fout kan heel lang worden overgeschreven", "Puimsteen kan op zee blijven drijven", "Kaarten van de oceaan zijn altijd fout", "Wetenschappers gummen graag dingen uit"], answer: 0, type: "hoofdgedachte", uitleg: "De schrijver zegt het zelf: dit gaat 'niet alleen over kaarten'. De puimsteen is een detail; 'altijd fout' is véél te sterk — de tekst gaat over één fout die bleef rondreizen." },
        { q: "Wat gebeurde er het éérst?", options: ["Een schip noteerde in de negentiende eeuw 'land gezien'", "Wetenschappers gumden het eiland van de kaart", "Een onderzoeksschip voer in 2012 naar de plek", "De zee bleek ruim een kilometer diep"], answer: 0, type: "volgorde", uitleg: "Let op: de tekst vertelt het níét op volgorde — de oude notitie komt pas ná het verhaal over 2012. Gebruik de jaartallen als ankers: negentiende eeuw komt vóór 2012." },
      ],
    },
    {
      titel: "Het bouwplan van Fedde",
      tekst: "Groep 8 mag dit jaar zelf de kraam bouwen voor de voorjaarsmarkt op het schoolplein. Fedde heeft er een tekening voor gemaakt, met maten erbij en zelfs een klein dak. Op die tekening staat precies hoeveel hout er nodig is: veertien planken voor de wanden en acht voor het dak. Wekenlang spaart de klas daarom planken die ouders en verzorgers over hebben. Toch gaat het op de bouwdag meteen mis: als alles is uitgeteld, blijkt er lang niet genoeg hout voor het dak te zijn. Fedde staart naar zijn tekening en voelt zijn goede humeur wegzakken. Zonder dak is het geen echte kraam, vindt hij.\n\nDan komt de conciërge, meneer Ali, aanlopen met zijn karretje. Achter het schuurtje liggen nog twee oude deuren, zegt hij, van de verbouwing van vorig jaar. Ze zijn krom en de verf bladdert, maar ze zijn groot. De klas schuurt de deuren glad en schildert er golven op, zodat het net een marktdak uit een ver land lijkt. Als de kraam klaarstaat, is hij heel anders dan op de tekening — schever, kleuriger, en volgens juf Petra 'precies goed'.\n\nOp de markt vraagt bijna iedereen wie dat bijzondere dak heeft bedacht. Fedde wijst dan eerlijk naar meneer Ali én naar zijn klasgenoten. Zijn tekening bewaart hij toch, als aandenken. Onderaan heeft hij er iets bij geschreven: een plan is een beginpunt, geen eindpunt.",
      vragen: [
        { q: "Hoe voelt Fedde zich als er niet genoeg hout blijkt te zijn?", options: ["Teleurgesteld", "Woedend op zijn klasgenoten", "Opgelucht", "Trots"], answer: 0, type: "gevoel afleiden", uitleg: "Het woord 'teleurgesteld' staat er niet — de schrijver laat het zien: Fedde staart naar zijn tekening en zijn goede humeur zakt weg. Zo'n beschrijving is de aanwijzing waar je op moet letten." },
        { q: "Waardoor lijkt het dak op een marktdak uit een ver land?", options: ["De klas schildert golven op de gladgeschuurde deuren", "Het hout was op", "Meneer Ali heeft een karretje", "De kraam staat een beetje scheef"], answer: 0, type: "oorzaak & gevolg", uitleg: "Het woordje 'zodat' verbindt oorzaak en gevolg in één zin: golven schilderen → het lijkt een marktdak. De andere opties staan wel in de tekst, maar horen niet bij dit gevolg." },
        { q: "Wat gebeurt er direct nadat meneer Ali over de deuren vertelt?", options: ["De klas schuurt de deuren glad en schildert ze", "Fedde maakt zijn tekening", "De klas spaart wekenlang planken", "De voorjaarsmarkt begint"], answer: 0, type: "volgorde", uitleg: "De tekening en het planken-sparen gebeurden al vóór de bouwdag. Zoek in de tekst de zin die op het vertellen vólgt — daar begint het schuren en schilderen." },
        { q: "Wat betekent de zin 'een plan is een beginpunt, geen eindpunt' hier?", options: ["Een plan mag onderweg veranderen en toch iets moois opleveren", "Je moet je plan altijd precies volgen", "Plannen maken heeft geen zin", "Een tekening is belangrijker dan een kraam"], answer: 0, type: "hoofdgedachte", uitleg: "Kijk wat er in het verhaal gebeurde: het plan mislukte, het eindresultaat werd anders — en juist 'precies goed'. De slotzin vat dat samen als een soort spreuk. Het hele verhaal is het bewijs erbij." },
      ],
    },
  ],

  // ── TREDE 4 — twee teksten van ±320-350 woorden, elk 5 vragen ───
  [
    {
      titel: "Geld dat groeit terwijl jij slaapt",
      tekst: "Wie geld op een spaarrekening zet, krijgt daar meestal een kleine beloning voor: rente. De bank mag jouw geld zolang gebruiken en betaalt daar een vergoeding voor. Stel dat je 100 euro spaart en de rente is 2 procent per jaar, dan krijg je na een jaar 2 euro erbij. Dat klinkt eerlijk gezegd niet als iets om over naar huis te schrijven.\n\nHet wordt pas interessant in het tweede jaar. Je krijgt dan namelijk geen rente over 100 euro, maar over 102 euro — dus ook rente over je rente. Dit heet het sneeuwbal-effect: een sneeuwbal die van een berg rolt, wordt steeds groter, en hoe groter hij wordt, hoe sneller hij groeit. In het begin merk je er bijna niets van. Na tien of twintig jaar daarentegen kan het verschil verrassend groot zijn. Daarom zeggen mensen die veel van geld weten: de beste spaarder is niet degene met het meeste geld, maar degene die het vroegst begint.\n\nRente heeft echter ook een andere kant. Wie geld leent, bijvoorbeeld voor een telefoon die hij nu wil hebben maar nog niet kan betalen, draait de rollen om: dan ben jíj degene die rente betaalt, elke maand opnieuw. 'Nu kopen, later betalen' klinkt aantrekkelijk, zeker als iedereen om je heen dat nieuwe ding al heeft. Desondanks betaal je uiteindelijk vaak tientallen euro's méér dan er op het prijskaartje stond, en rolt dezelfde sneeuwbal ineens tégen je in plaats van met je mee.\n\nRente heeft dus twee gezichten. Voor de spaarder is het een stille hulp die elk jaar een beetje meeduwt; voor de lener is het een stille tegenstander die er elke maand een stukje bij optelt. Wie dat eenmaal doorheeft, kijkt anders naar zijn zakgeld. Sparen voelt traag, zeker in het begin, en wachten op iets leuks is nooit leuk. Maar onthoud de sneeuwbal: alles wat hij nodig heeft, is een klein duwtje en heel veel tijd — en tijd heeft niemand zoveel als iemand die nog jong is.",
      vragen: [
        { q: "Wat is volgens de tekst het verschil tussen sparen en lenen als het om rente gaat?", options: ["Bij sparen krijg jij rente van de bank, bij lenen betaal jij juist rente", "Bij sparen betaal je elke maand rente aan de bank", "Bij lenen groeit jouw spaargeld vanzelf", "Er is geen verschil: rente is altijd een beloning"], answer: 0, type: "informatie combineren", uitleg: "Dit antwoord staat niet in één alinea. Alinea 1 vertelt dat de spaarder rente kríjgt, alinea 3 dat de lener rente betáált. Bij grote teksten moet je vaker twee alinea's aan elkaar knopen." },
        { q: "Waarom vergelijkt de schrijver rente met een sneeuwbal?", options: ["Omdat het bedrag steeds sneller groeit naarmate het groter wordt", "Omdat sparen koud en saai aanvoelt", "Omdat banken vaak in de bergen staan", "Omdat een sneeuwbal snel smelt"], answer: 0, type: "vergelijking begrijpen", uitleg: "Direct na de dubbele punt legt de tekst de vergelijking zelf uit: hoe groter de bal, hoe sneller hij groeit — precies wat er met rente-over-rente gebeurt. Een vergelijking kiest altijd één eigenschap, niet alles wat op een sneeuwbal lijkt." },
        { q: "Over welk bedrag krijg je in het voorbeeld in het tweede jaar rente?", options: ["Over 102 euro", "Over 100 euro", "Over 2 euro", "Over 20 euro"], answer: 0, type: "detail opzoeken", uitleg: "De tekst zegt het met nadruk: 'geen rente over 100 euro, maar over 102 euro'. De valstrik-getallen 100 en 2 staan vlakbij — lees dus de hele zin, niet alleen het eerste getal dat je herkent." },
        { q: "Welke uitspraak uit de tekst is een mening?", options: ["Wachten op iets leuks is nooit leuk", "Bij 2 procent rente krijg je over 100 euro na een jaar 2 euro", "Wie leent, betaalt rente", "In het tweede jaar krijg je rente over 102 euro"], answer: 0, type: "mening vs feit", uitleg: "De reken-zinnen kun je narekenen: dat zijn feiten. Of wachten 'nooit leuk' is, kun je niet nameten — sommige mensen vinden wachten prima. Een mening kan dus gewoon tussen de feiten staan, zonder 'ik vind' ervoor." },
        { q: "Welke samenvatting past het best bij deze tekst?", options: ["Rente laat spaargeld langzaam steeds sneller groeien, maar maakt lenen juist duurder; vroeg beginnen met sparen loont het meest", "Banken betalen 2 euro aan iedereen die spaart", "Lenen voor een telefoon is verboden", "Een sneeuwbal die van een berg rolt, wordt steeds groter"], answer: 0, type: "samenvatten", uitleg: "Check bij elke samenvatting: dekt hij álle alinea's? De sneeuwbal-optie is maar een hulp-vergelijking, en 'verboden' staat nergens — de tekst zegt alleen dat lenen extra kost." },
      ],
    },
    {
      titel: "De torenwedstrijd",
      tekst: "Op de laatste dag voor de vakantie houdt meester Timo een bouwwedstrijd. Elk groepje krijgt twintig droge spaghettistokjes, een rolletje plakband en één spekje. De opdracht klinkt simpel: bouw de hoogste toren, met het spekje bovenop. De tafels worden tegen elkaar geschoven en overal klinkt meteen druk overleg. Meester Timo leest ondertussen de regels voor, en bijna niemand luistert nog als hij bij de laatste regel is aangekomen: de toren moet, zodra het meetlint erbij komt, tien tellen blijven staan.\n\nSanne's groepje begint vol goede moed, maar al snel ontstaat er discussie over de aanpak. Milan wil zo hoog mogelijk stapelen; Sanne denkt aan het uitstapje naar de oude brug van vorige maand, waar de gids vertelde dat driehoeken de sterkste vorm zijn. Ze bouwen uiteindelijk haar plan: een brede voet van driehoeken, met daarop één korte, stevige punt. Hun toren wordt drieëndertig centimeter. Om hen heen groeien torens van vijftig, zestig, zelfs zeventig centimeter, en Milan moppert dat ze met al die driehoeken kostbare stokjes hebben verspild. Sanne zegt er niets van terug, maar haar buik voelt zwaar; misschien had Milan wel gelijk.\n\nDan begint het meten. De toren van zeventig centimeter zwiept heen en weer zodra meester Timo het meetlint pakt, buigt langzaam door onder het spekje en klapt precies bij 'zeven' dubbel. De toren van zestig volgt, en die van vijftig haalt de tien tellen evenmin. Overal klinkt gekreun. Als meester Timo bij Sanne's groepje komt, telt de hele klas hardop mee. De kleine toren staat er bij 'tien' nog precies zo bij als bij 'één'.\n\n'Hoog bouwen kan iedereen,' zegt meester Timo terwijl hij het winnende groepje een high five geeft, 'maar blijven staan, dát is de kunst.' Milan geeft Sanne een por en mompelt dat driehoeken toch niet zó saai zijn. En Sanne? Die neemt zich voor om in de vakantie nog eens langs die oude brug te fietsen. Je weet immers nooit waar de volgende wedstrijd over gaat.",
      vragen: [
        { q: "Waarom wint het groepje van Sanne, terwijl hun toren lang niet de hoogste is?", options: ["Hun toren blijft als enige tien tellen staan, en dat was een van de regels", "Hun toren was stiekem toch de hoogste", "Meester Timo vindt driehoeken de mooiste vorm", "De andere groepjes deden niet echt mee"], answer: 0, type: "informatie combineren", uitleg: "Het antwoord zit in twéé alinea's: de bijna vergeten regel uit alinea 1 (tien tellen blijven staan) en het meetmoment in alinea 3. Wie de eerste alinea oversloeg, snapt de uitslag niet — net als de klas zelf." },
        { q: "Wat voelt Sanne vlak vóór het meten?", options: ["Ze twijfelt of haar plan wel goed was", "Ze weet zeker dat haar groepje gaat winnen", "Ze is boos op meester Timo", "Ze verveelt zich"], answer: 0, type: "gevoel afleiden", uitleg: "'Haar buik voelt zwaar' en 'misschien had Milan wel gelijk' — de schrijver noemt het woord 'twijfel' niet, maar laat het je voelen. Let bij verhalen op wat een lichaam 'zegt'." },
        { q: "'Ze bouwen uiteindelijk haar plan.' Wiens plan is dat, en wat houdt het in?", options: ["Sannes plan: een brede voet van driehoeken met een korte punt", "Milans plan: zo hoog mogelijk stapelen", "Het plan van de gids bij de oude brug", "Het plan van meester Timo"], answer: 0, type: "verwijswoord", uitleg: "'Haar' kan niet op Milan slaan, en de gids vertelde alleen een weetje. Het woord wijst een paar zinnen terug naar Sanne — en meteen daarna beschrijft de tekst wat dat plan inhoudt." },
        { q: "Hoe hoog is de toren van Sanne's groepje?", options: ["Drieëndertig centimeter", "Zeventig centimeter", "Vijftig centimeter", "Tien centimeter"], answer: 0, type: "detail opzoeken", uitleg: "De tekst strooit met maten: vijftig, zestig en zeventig horen bij de ándere groepjes, en 'tien' is geen hoogte maar het aantal tellen. Koppel elk getal aan zijn eigenaar voordat je kiest." },
        { q: "Welke gedachte past het best bij dit verhaal?", options: ["Stevig en doordacht bouwen kan belangrijker zijn dan indruk maken", "Hoge torens zijn altijd beter dan lage", "Een beetje ruzie helpt bij het bouwen", "Spaghetti is geen goed bouwmateriaal"], answer: 0, type: "hoofdgedachte", uitleg: "Meester Timo spreekt de les bijna letterlijk uit: hoog bouwen kan iedereen, blijven staan is de kunst. Het goede antwoord zegt datzelfde in andere woorden — dat is waar je bij zulke vragen op let." },
      ],
    },
  ],
];

// ── WOORDHULP_F — alleen woorden die een kind écht niet kent, ─────
// nooit een woord waar een vraag over gaat, sleutel = vorm uit de tekst.
export const WOORDHULP_F = {
  "aandenken": "iets dat je bewaart om aan vroeger terug te denken.",
  "bladdert": "bladderen = oude verf laat in schilfertjes los.",
  "conciërge": "de meneer of mevrouw die op school klusjes doet en het gebouw netjes houdt.",
  "destijds": "in die tijd; toen.",
  "gescandeerd": "scanderen = een naam in een ritme roepen: 'Jill! Jill! Jill!'",
  "gewelf": "een gebogen vorm, zoals een omgekeerd kommetje of een boog boven je hoofd.",
  "imago": "het beeld dat andere mensen van je hebben — of dat nou klopt of niet.",
  "kostbare": "kostbaar = waardevol; je wilt er zuinig op zijn.",
  "soortgenoot": "een dier van dezelfde soort — voor een rat is dat een andere rat.",
  "ter plekke": "meteen, op dat moment en op die plek.",
  "vaarroutes": "de vaste wegen over zee waar veel schepen langskomen.",
  "verduren": "veel te verduren krijgen = veel moeten doorstaan of uithouden.",
  "vergoeding": "geld dat je krijgt omdat iemand iets van jou mag gebruiken.",
  "voorouders": "de mensen uit jouw familie van heel lang geleden.",
  "waakzaam": "goed blijven opletten of er gevaar aankomt.",
  "waarneming": "iets dat iemand zelf ziet of hoort en daarna doorvertelt of opschrijft.",
};
