// versieD.js — Leesladder 2 "de zware ladder", VERSIE D (20 aug 2026).
// Niveau 2: stevige groep 7-8 tot begin brugklas — langere zinnen, zwaardere
// signaalwoorden (hoewel/desondanks/daarentegen/tenzij/bovendien/immers),
// verwijswoorden die vérder terugwijzen, impliciete hoofdgedachte,
// mening-vs-feit en samenvatting-vragen. Zelfde format als leesladderData.js:
// het goede antwoord staat ALTIJD op plek 0; de pagina husselt zelf.

export const VERSIE_D = [
  // ── TREDE 1 — 4 teksten van ±8 zinnen, elk 3 vragen ──────────────
  [
    {
      titel: "De meester van de vermomming",
      tekst: "Een octopus kan in minder dan een seconde van kleur veranderen, waardoor hij bijna onzichtbaar wordt tegen rotsen of zand. Hoewel dat klinkt als toverij, zit er gewone techniek achter: miljoenen piepkleine kleurzakjes in zijn huid, die hij kan oprekken en samenknijpen. Het vreemdste moet dan nog komen. Uit onderzoek blijkt namelijk dat een octopus waarschijnlijk kleurenblind is. Hij doet dus perfect kleuren na die hij zelf niet eens kan zien. Onderzoekers vermoeden dat zijn huid zelf licht kan opvangen — een beetje alsof jij met je arm zou kunnen kijken. Bewezen is dat nog niet. Tot die tijd blijft de octopus een raadsel met acht armen.",
      vragen: [
        { q: "Wat is de belangrijkste gedachte van deze tekst?", options: ["De octopus doet kleuren na die hij zelf waarschijnlijk niet ziet, en niemand weet precies hoe", "Een octopus heeft miljoenen kleurzakjes in zijn huid", "Een octopus verandert in minder dan een seconde van kleur", "Onderzoekers hebben bewezen dat octopushuid licht opvangt"], answer: 0, type: "hoofdgedachte", uitleg: "De hoofdgedachte staat hier nérgens letterlijk — je moet hem zelf bouwen. De andere antwoorden staan wél letterlijk in de tekst, maar dat zijn losse stukjes, geen paraplu die over de hele tekst past. En pas op: 'bewezen' is precies wat de tekst ontkent." },
        { q: "'Hoewel dat klinkt als toverij, zit er gewone techniek achter.' Wat doet het woord 'hoewel' hier?", options: ["Het zet twee dingen tegenover elkaar: het lijkt toverij, maar het is techniek", "Het geeft de reden waarom de octopus van kleur verandert", "Het kondigt een opsomming van voorbeelden aan", "Het laat zien dat de schrijver het zelf niet gelooft"], answer: 0, type: "signaalwoord", uitleg: "'Hoewel' is een tegenstelling-woord, net als 'maar' en 'toch'. Het eerste deel van de zin wekt een verwachting (toverij), het tweede deel gaat daar tegenin (gewone techniek)." },
        { q: "'Bewezen is dat nog niet.' Waar wijst 'dat' naar?", options: ["Dat de huid van de octopus zelf licht kan opvangen", "Dat de octopus kleurenblind is", "Dat een octopus van kleur kan veranderen", "Dat je met je arm kunt kijken"], answer: 0, type: "verwijswoord", uitleg: "Lees terug tot je precies weet wát er nog niet bewezen is. Dat de octopus kleurenblind is, blijkt al 'uit onderzoek' — het níét-bewezen deel is het vermoeden over de huid, in de zin ervóór. Verwijswoorden wijzen soms verder terug dan je denkt." },
      ],
    },
    {
      titel: "De wissel",
      tekst: "Op de laatste training vóór de finale van de estafette laat Jasmijn het stokje twee keer vallen. Niemand zegt er iets van, maar in de kleedkamer blijft het stiller dan anders. Die avond ligt ze wakker en oefent ze de beweging wel honderd keer in haar hoofd. Tijdens de finale komt Timo op haar afgestormd, sneller dan ooit. Jasmijn steekt haar hand naar achteren en telt, precies zoals ze het zichzelf heeft geleerd. De tik van het stokje in haar handpalm voelt als een verlossing. Pas na de finish durft ze weer gewoon adem te halen. Ze wordt tweede, vlak achter de snelste loopster van de regio. Toch gaat het in de kleedkamer nergens anders over dan over háár wissel — de mooiste van de dag.",
      vragen: [
        { q: "Hoe voelt Jasmijn zich vóór de finale?", options: ["Zenuwachtig", "Boos op Timo", "Verveeld", "Trots op zichzelf"], answer: 0, type: "gevoel afleiden", uitleg: "De schrijver zegt nergens 'zenuwachtig', maar laat het zien: wakker liggen, de beweging honderd keer oefenen in haar hoofd, pas na de finish weer durven ademen. Gedrag verklapt gevoel." },
        { q: "Waarom voelt de tik van het stokje 'als een verlossing'?", options: ["Ze was bang dat de wissel wéér mis zou gaan, en nu lukt hij wél", "Het stokje doet pijn aan haar hand", "Ze heeft de wedstrijd gewonnen", "Timo rende sneller dan ooit"], answer: 0, type: "conclusie trekken", uitleg: "Plak het begin en het midden aan elkaar: op de training viel het stokje twee keer (haar angst), nu landt het goed in haar hand (de opluchting). Pas op met 'gewonnen' — ze werd tweede; dat staat letterlijk in de tekst." },
        { q: "'Tóch gaat het nergens anders over dan over háár wissel.' Waarom past het woord 'toch' hier?", options: ["Je verwacht dat het over de winnares gaat, want Jasmijn werd maar tweede — maar iedereen praat over haar wissel", "Omdat Jasmijn eerste is geworden", "Omdat er een reden achteraan komt", "Omdat het verhaal bijna afgelopen is"], answer: 0, type: "signaalwoord", uitleg: "'Toch' verklapt een verrassing: er gebeurt iets anders dan je zou verwachten. Tweede worden is niet het knapste van de dag — haar perfecte wissel wél, en dáár praat iedereen over." },
      ],
    },
    {
      titel: "Opruimen in de ruimte",
      tekst: "Rond de aarde zweven niet alleen satellieten, maar ook honderdduizenden stukken afval: losse boutjes, verfschilfers en zelfs complete kapotte raketonderdelen. Dat klinkt onschuldig, totdat je hoort hoe snel dat puin gaat. Een verfschilfer van één centimeter beweegt met zo'n achtentwintigduizend kilometer per uur — vele malen sneller dan een kogel. Bij die snelheid kan zelfs zoiets kleins een raam van een ruimtestation beschadigen. Ruimtevaartorganisaties houden daarom meer dan dertigduizend grote brokstukken nauwkeurig in de gaten. Moet een ruimtestation uitwijken, dan krijgt de bemanning soms maar een paar uur de tijd. Er bestaan bovendien plannen om het puin met speciale vangnetten en harpoenen op te ruimen. Zolang die niet werken, geldt in de ruimte dezelfde regel als op een schoolplein: wie rommel maakt, krijgt er vroeg of laat zelf last van.",
      vragen: [
        { q: "Waarom kan een klein verfschilfertje toch gevaarlijk zijn?", options: ["Het beweegt zó snel dat het bij een botsing flinke schade aanricht", "Verf is giftig voor astronauten", "Het is groter dan een kogel", "Er zweven dertigduizend verfschilfers rond de aarde"], answer: 0, type: "oorzaak & gevolg", uitleg: "De tekst legt de ketting zelf: eerst de snelheid, dan 'bij die snelheid kan zelfs zoiets kleins...' — niet de grootte maar de snelheid is het gevaar. De dertigduizend gaat over gróte brokstukken, niet over verfschilfers." },
        { q: "Hoeveel grote brokstukken worden nauwkeurig in de gaten gehouden?", options: ["Meer dan dertigduizend", "Achtentwintigduizend", "Honderdduizend", "Een paar honderd"], answer: 0, type: "detail opzoeken", uitleg: "Er staan meerdere grote getallen in de tekst, vlak bij elkaar — dat is een klassieke toets-valstrik. Achtentwintigduizend is de snélheid, honderdduizenden is al het afval samen. Lees precies welk getal bij welke zin hoort." },
        { q: "Waarom eindigt de schrijver met de zin over het schoolplein?", options: ["Om met een bekend voorbeeld duidelijk te maken dat je van je eigen rommel uiteindelijk zelf last krijgt", "Om te vertellen dat schoolpleinen erg vies zijn", "Om te laten zien dat de ruimte net zo groot is als een schoolplein", "Om kinderen te verbieden met boutjes te gooien"], answer: 0, type: "vergelijking begrijpen", uitleg: "De ruimte is ver weg en moeilijk voor te stellen; een schoolplein ken je wél. Met zo'n vergelijking trekt de schrijver zijn boodschap naar jouw eigen wereld — de vergelijking gaat over de regel, niet over de grootte." },
      ],
    },
    {
      titel: "Het jaar zonder zomer",
      tekst: "In 1815 barstte aan de andere kant van de wereld een reusachtige vulkaan uit. De aswolk was zo groot dat hij een jaar later nog steeds zonlicht tegenhield, waardoor oogsten in heel Europa mislukten. Er was daardoor ook nauwelijks voer voor paarden, terwijl bijna al het vervoer in die tijd van paarden afhing. Een Duitse uitvinder bedacht toen een houten 'loopmachine': twee wielen achter elkaar en een stuur, maar nog geen trappers. Je zat erop en duwde jezelf met je voeten vooruit. Veel mensen lachten erom, en sommige steden verboden het ding zelfs omdat voetgangers ervan schrokken. Desondanks was de belangrijkste stap gezet: het idee van rijden op twee wielen. Ruim vijftig jaar later kwamen daar trappers bij — en zo werd uit een hongerjaar uiteindelijk de fiets geboren.",
      vragen: [
        { q: "Wat heeft de vulkaanuitbarsting met de loopmachine te maken?", options: ["Door de aswolk mislukten oogsten, waardoor er te weinig voer voor paarden was — en juist paarden waren toen het vervoer", "De vulkaan verwoestte alle wegen in Europa", "De uitvinder wilde snel naar de vulkaan toe rijden", "Paarden schrokken van de loopmachine"], answer: 0, type: "oorzaak & gevolg", uitleg: "Dit is een kettinkje van gevolgen over meerdere zinnen: vulkaan → aswolk → mislukte oogsten → geen voer → probleem met paardenvervoer → nieuw vervoermiddel nodig. Bij zulke vragen loop je de schakels één voor één na." },
        { q: "'Desondanks was de belangrijkste stap gezet.' Wat betekent 'desondanks' hier?", options: ["Ondanks het gelach en de verboden was het idee tóch een grote stap", "Omdat iedereen de loopmachine meteen wilde hebben", "Daarna volgde er nog een stap", "Daarom werd de loopmachine verboden"], answer: 0, type: "signaalwoord", uitleg: "'Desondanks' is een deftig broertje van 'toch': wat in de zinnen ervóór staat (lachen, verbieden), houdt het niet tegen. Het draait de richting van de tekst om." },
        { q: "Wat had de loopmachine nog níét?", options: ["Trappers", "Een stuur", "Twee wielen", "Wielen achter elkaar"], answer: 0, type: "detail opzoeken", uitleg: "De zin somt op wat er wél was en verklapt dan met 'maar nog geen...' wat er ontbrak. De andere drie staan letterlijk in de tekst als dingen die de loopmachine wél had — letterlijk in de tekst staan betekent dus niet dat het het antwoord is." },
      ],
    },
  ],

  // ── TREDE 2 — 3 teksten van ±150 woorden, elk 3 vragen ───────────
  [
    {
      titel: "De wasserette van het rif",
      tekst: "Op een koraalrif is het net zo druk als in een stad, en net als in een stad zijn er zelfs wasserettes. Bij zo'n poetsstation staan grote vissen keurig in de rij. Kleine poetsvissen zwemmen dan langs hun huid, langs hun kieuwen en zelfs door hun geopende bek, en eten daar dode velletjes en lastige beestjes weg. Allebei worden ze er beter van: de grote vis wordt schoon, de kleine krijgt een gratis maaltijd.\n\nToch is niet iedereen op het rif eerlijk. Er bestaat een visje dat er bijna precies zo uitziet als de poetsvis en ook nog eens hetzelfde dansje zwemt. Grote vissen laten hem daarom nietsvermoedend dichtbij komen. Maar in plaats van te poetsen bijt hij bliksemsnel een stukje uit een vin en schiet weg. Wie op het rif goed geholpen wil worden, moet dus eerst héél goed kijken wie er voor hem zwemt.",
      vragen: [
        { q: "Welke zin geeft de tekst het beste weer?", options: ["Op het rif werken vissen slim samen, maar er is ook een bedrieger die daar misbruik van maakt", "Grote vissen staan keurig in de rij bij een poetsstation", "Poetsvissen eten dode velletjes en lastige beestjes weg", "Op een koraalrif is het net zo druk als in een stad"], answer: 0, type: "hoofdgedachte", uitleg: "Deze tekst heeft twee helften: de samenwerking (alinea 1) én de bedrieger (alinea 2). Alleen het goede antwoord dekt allebei. De andere drie staan letterlijk in de tekst — maar een letterlijke zin is bijna nooit de hoofdgedachte van een héle tekst." },
        { q: "'Grote vissen laten hem daarom nietsvermoedend dichtbij komen.' Wie is 'hem'?", options: ["Het visje dat op de poetsvis lijkt", "De poetsvis", "De grootste vis in de rij", "Een lastig beestje op de huid"], answer: 0, type: "verwijswoord", uitleg: "Je denkt snel 'de poetsvis', want daar ging alinea 1 over — precies de valstrik. Lees terug: de zin ervóór introduceert het na-aap-visje, en dáár wijst 'hem' naar. Controleer een verwijswoord altijd in de zinnen ervoor." },
        { q: "Waarom trapt een grote vis in de truc van de bedrieger?", options: ["Het visje ziet eruit en beweegt als een poetsvis, dus de grote vis verwacht geholpen te worden", "Grote vissen kunnen onder water bijna niets zien", "De bedrieger is veel sterker dan de grote vis", "Grote vissen vinden een beet niet erg"], answer: 0, type: "conclusie trekken", uitleg: "De tekst zegt niet letterlijk waaróm de truc werkt — je combineert zelf: zelfde uiterlijk + zelfde dansje = de grote vis dénkt dat het een poetsvis is. Dat zelf aan elkaar plakken heet een conclusie trekken." },
      ],
    },
    {
      titel: "De nacht dat iedereen omhoog keek",
      tekst: "Als oma over de zomer van 1969 vertelt, gaat ze altijd even rechtop zitten. Ze was elf, net zo oud als ik nu. Midden in de nacht maakte haar vader haar wakker en zette haar in pyjama voor de televisie, een log ding met een klein, grijs beeldscherm. Het beeld ruiste en flikkerde; soms viel het zelfs helemaal weg. Urenlang gebeurde er bijna niets, en toch durfde niemand naar bed te gaan. Toen verscheen er eindelijk een wazige, witte gedaante die traag een laddertje afklom. Oma's vader, die anders nooit iets bijzonders zei, kneep haar zachtjes in haar schouder. 'Onthoud dit, meisje,' fluisterde hij. 'Er loopt nu een mens op de maan.' Oma zegt dat ze het beeld allang niet meer scherp voor zich ziet. Maar die hand op haar schouder, zegt ze, voelt ze nog elke keer als ze naar de maan kijkt.",
      vragen: [
        { q: "Hoe voelde oma's vader zich tijdens de maanlanding?", options: ["Diep onder de indruk", "Verveeld, omdat er urenlang niets gebeurde", "Boos, omdat het beeld steeds wegviel", "Bang in het donker"], answer: 0, type: "gevoel afleiden", uitleg: "Let op wat hij dóét: een man die 'anders nooit iets bijzonders zei' knijpt in haar schouder en fluistert 'onthoud dit'. Het verveeld-antwoord en het weggevallen beeld staan wel in de tekst, maar zeggen niets over zíjn gevoel — klassieke afleiders." },
        { q: "Wat bedoelt oma met de laatste zin?", options: ["Niet het televisiebeeld, maar het moment met haar vader is haar het meest bijgebleven", "Haar schouder doet na al die jaren nog steeds pijn", "Ze kijkt liever niet meer naar de maan", "Ze weet niet zeker meer of de maanlanding echt gebeurd is"], answer: 0, type: "conclusie trekken", uitleg: "Zet de twee slotzinnen naast elkaar: het beeld is vervaagd, de hand op haar schouder niet. De schrijver vertelt zo — zonder het te zeggen — dat het gevoel belangrijker was dan wat er op tv te zien was." },
        { q: "Wat gebeurde er éérst?", options: ["Oma's vader maakte haar midden in de nacht wakker", "Een witte gedaante klom een laddertje af", "Haar vader kneep haar zachtjes in haar schouder", "Het beeld werd eindelijk scherp"], answer: 0, type: "volgorde", uitleg: "Zet de gebeurtenissen op een tijdlijn: wakker maken → urenlang wachten → gedaante op de ladder → knijpen in schouder. En pas op: 'het beeld werd scherp' staat helemáál niet in de tekst — het bleef juist wazig." },
      ],
    },
    {
      titel: "Een ergernis om te plakken",
      tekst: "Sommige uitvindingen beginnen met een ergernis. Een Zwitserse ingenieur ging in 1941 wandelen met zijn hond, en bij thuiskomst zaten ze allebei vol met klitten: stekelige zaadbolletjes die overal aan blijven hangen. De meeste mensen plukken die eraf en gooien ze weg. Hij daarentegen legde er eentje onder de microscoop. Wat hij zag, verraste hem: elk stekeltje eindigde in een piepklein haakje, dat zich vastgreep in de lusjes van kleding of vacht. Als de natuur zó slim kan vastplakken, dacht hij, dan moet een mens dat kunnen namaken. Het kostte hem vervolgens nog jaren om twee stroken stof te maken die net zo werkten: één met haakjes, één met lusjes. Tegenwoordig zit zijn uitvinding op schoenen, op jassen en zelfs in ruimtepakken, want in de ruimte zweeft alles weg wat je niet vastmaakt. Eén vervelende wandeling leverde de wereld dus iets op waar we dagelijks gemak van hebben.",
      vragen: [
        { q: "Welke samenvatting past het best bij deze tekst?", options: ["Een ingenieur bekeek klitten onder de microscoop, ontdekte hun haakjes en maakte dat na — na jaren werk ontstond zo een uitvinding die we overal gebruiken", "Een ingenieur ging in 1941 wandelen met zijn hond en kwam vol klitten thuis", "De uitvinding zit tegenwoordig op schoenen, op jassen en in ruimtepakken", "Klitten hebben stekeltjes die eindigen in piepkleine haakjes"], answer: 0, type: "samenvatten", uitleg: "Een goede samenvatting dekt begin, midden én einde van de tekst. De andere drie kloppen wel, maar pakken elk maar één stukje — en een samenvatting van één stukje is geen samenvatting." },
        { q: "'Hij daarentegen legde er eentje onder de microscoop.' Wat laat 'daarentegen' zien?", options: ["Dat hij iets anders deed dan de meeste mensen", "Dat hij de klitten óók weggooide", "Dat er een reden achteraan komt", "Dat de tekst een opsomming begint"], answer: 0, type: "signaalwoord", uitleg: "'Daarentegen' zet twee dingen tegenover elkaar: de meeste mensen gooien klitten weg — hij juist niet. Zie je 'daarentegen', zoek dan altijd de twee kanten die vergeleken worden." },
        { q: "Waarom is de uitvinding juist in de ruimte zo handig?", options: ["Alles wat je daar niet vastmaakt zweeft weg, en met haakjes en lusjes zet je spullen snel vast", "Ritsen gaan in de ruimte kapot van de kou", "Ruimtepakken kunnen niet gewassen worden", "Haakjes en lusjes plakken in de ruimte sterker dan op aarde"], answer: 0, type: "oorzaak & gevolg", uitleg: "Het reden-woord 'want' wijst je de weg: 'want in de ruimte zweeft alles weg wat je niet vastmaakt'. De andere antwoorden klinken technisch, maar staan nergens in de tekst — verzonnen redenen zijn nooit het antwoord." },
      ],
    },
  ],

  // ── TREDE 3 — 3 teksten van ±230 woorden, elk 4 vragen ───────────
  [
    {
      titel: "Bericht van Mars",
      tekst: "Stel: je bestuurt een speelgoedauto op afstand, maar elke keer dat je stuurt, reageert hij pas een kwartier later. Ongeveer zo voelt het om een Marswagen te besturen. Radiosignalen reizen met de snelheid van het licht, en tóch doen ze er — afhankelijk van waar Mars en de aarde in hun baan staan — drie tot ruim twintig minuten over om aan te komen. Een bevel als 'rem!' komt dus altijd te laat.\n\nDaarom werken Marswagens anders dan veel mensen denken. Niemand op aarde zit live te sturen. In plaats daarvan sturen onderzoekers één keer per dag een compleet plan omhoog: rij naar die rots, maak daar foto's, boor een klein gaatje. De wagen voert dat plan vervolgens grotendeels zelfstandig uit. Zijn camera's speuren de grond af, en herkent de computer een gevaarlijk stuk — een steile helling, een groot rotsblok — dan kiest hij zelf een veiligere route. Pas uren later horen de onderzoekers of alles gelukt is.\n\nDie zelfstandigheid is geen luxe, maar noodzaak. Eén verkeerd wiel in los zand kan immers het einde van een hele missie betekenen, en een sleepwagen sturen is er niet bij. Elke meter op Mars is daarom het resultaat van geduld: eerst denken, dan pas rijden. Misschien is dat nog wel de nuttigste les die de ruimtevaart ons leert.",
      vragen: [
        { q: "Hoe lang doet een radiosignaal er over om van de aarde naar Mars te reizen?", options: ["Drie tot ruim twintig minuten, afhankelijk van waar de planeten staan", "Altijd precies een kwartier", "Een paar uur", "Eén dag"], answer: 0, type: "detail opzoeken", uitleg: "Het kwartier uit de eerste zin hoort bij de speelgoedauto-vergelijking, niet bij het echte signaal — en 'uren later' en 'één keer per dag' gaan over iets anders. De echte tijd staat verderop, mét het woordje 'afhankelijk'. Kies nooit het eerste getal dat je tegenkomt." },
        { q: "Waarom stuurt niemand een Marswagen live met een stuur of joystick?", options: ["Elk stuurbevel komt minuten te laat aan, dus direct reageren is onmogelijk", "Joysticks werken niet in de ruimte", "De onderzoekers hebben er geen tijd voor", "De wagen rijdt te snel om te kunnen sturen"], answer: 0, type: "oorzaak & gevolg", uitleg: "De eerste alinea eindigt met de kern: een bevel als 'rem!' komt altijd te laat. Het woord 'daarom' aan het begin van alinea 2 koppelt die oorzaak aan het gevolg — zo werken de wagens dus met een dagplan." },
        { q: "'Eén verkeerd wiel in los zand kan immers het einde van een hele missie betekenen.' Wat doet het woord 'immers' hier?", options: ["Het geeft de reden waarom die zelfstandigheid noodzaak is", "Het geeft een tegenstelling aan", "Het kondigt een opsomming aan", "Het laat zien dat de schrijver overdrijft"], answer: 0, type: "signaalwoord", uitleg: "'Immers' betekent zoiets als 'want, zoals je zult begrijpen'. Het onderbouwt de zin ervóór: zelfstandigheid is noodzaak, wánt één fout kan het einde zijn. Een deftig reden-woord dus." },
        { q: "Wat is de belangrijkste gedachte van deze tekst?", options: ["Omdat signalen zo lang onderweg zijn, moeten Marswagens veel zelf kunnen beslissen", "Marswagens maken foto's en boren gaatjes in rotsen", "Radiosignalen reizen met de snelheid van het licht", "Op Mars liggen veel steile hellingen en grote rotsblokken"], answer: 0, type: "hoofdgedachte", uitleg: "De hoofdgedachte verbindt het probleem (alinea 1: signaal te traag) met de oplossing (alinea 2-3: de wagen beslist zelf). De andere antwoorden staan letterlijk in de tekst, maar het zijn details onder die paraplu." },
      ],
    },
    {
      titel: "De eerste zet",
      tekst: "Ravi kende in de nieuwe stad precies drie plekken: zijn huis, zijn school en de supermarkt op de hoek. In de pauze zat hij meestal aan de rand van het plein, waar hij deed alsof zijn brood heel veel aandacht nodig had. Thuis vroeg zijn moeder elke dag hoe het ging, en elke dag zei hij 'goed' — op een toon die precies het tegenovergestelde betekende.\n\nOp een woensdag hing er een briefje bij de ingang van de bibliotheek: schaakclub, iedereen welkom. Ravi schaakte al sinds zijn zesde; het was het enige uit de oude stad dat zonder verhuisdozen mee had gekund. Toch liep hij er die week twee keer langs zonder naar binnen te gaan. Pas de derde woensdag stapte hij over de drempel, met wangen die gloeiden alsof hij iets verkeerds deed.\n\nBinnen zaten een meisje van zijn leeftijd en een oude man met een bril vol vingerafdrukken. 'Eindelijk,' zei het meisje, alsof ze al weken op hem had gewacht. 'Nu kunnen we een toernooitje spelen.' Ravi verloor die middag drie potjes op rij, en desondanks fietste hij zingend naar huis. Zijn moeder vroeg hoe het ging. 'Goed,' zei hij — en voor het eerst in weken klonk het precies zoals het bedoeld was.",
      vragen: [
        { q: "Hoe voelt Ravi zich in de eerste alinea?", options: ["Eenzaam", "Boos op zijn moeder", "Blij met de nieuwe stad", "Jaloers op het meisje"], answer: 0, type: "gevoel afleiden", uitleg: "Het woord 'eenzaam' staat er niet — maar alleen aan de rand van het plein zitten, doen alsof je brood interessant is en 'goed' zeggen op een toon die het tegenovergestelde betekent: dat is eenzaamheid, laten zien in plaats van gezegd." },
        { q: "Waarom zegt Ravi elke dag 'goed', terwijl het niet goed gaat?", options: ["Hij wil er waarschijnlijk niet over praten en zijn moeder niet ongerust maken", "Het gaat stiekem juist heel goed met hem", "Hij verstaat de vraag van zijn moeder niet", "Hij is 's middags te moe om te praten"], answer: 0, type: "conclusie trekken", uitleg: "De tekst geeft alleen de aanwijzing 'op een toon die het tegenovergestelde betekende' — de reden moet je zelf invullen op de meest logische manier. De andere antwoorden passen niet bij een jongen die net verhuisd is en alleen op het plein zit." },
        { q: "'Ravi verloor drie potjes op rij, en desondanks fietste hij zingend naar huis.' Wat laat 'desondanks' zien?", options: ["Dat er iets anders gebeurt dan je verwacht: wie verliest is meestal niet vrolijk, maar Ravi wél", "Dat Ravi daarna ook nog een potje won", "Dat er een reden achteraan komt", "Dat het verhaal opnieuw begint"], answer: 0, type: "signaalwoord", uitleg: "'Desondanks' draait de verwachting om, net als 'toch'. Verliezen hoort bij balen — maar hier zingt hij. Dat botsen tussen verwachting en werkelijkheid is precies waar dit signaalwoord voor waarschuwt." },
        { q: "Wat is de belangrijkste gedachte van dit verhaal?", options: ["Niet winnen maakte Ravi blij, maar het vinden van een plek waar hij zich thuis voelt", "Schaken leer je het best in een bibliotheek", "Wie drie potjes verliest, moet meer oefenen", "Ravi ging pas de derde woensdag naar binnen"], answer: 0, type: "hoofdgedachte", uitleg: "Kijk naar het slot: hetzelfde woord 'goed', maar nu klinkt het echt. Het verhaal draait dus niet om schaken of om winnen, maar om erbij horen. De hoofdgedachte staat nergens letterlijk — het einde wijst hem aan." },
      ],
    },
    {
      titel: "De tocht die bijna nooit komt",
      tekst: "De Elfstedentocht is misschien wel de beroemdste schaatstocht ter wereld — en tegelijk de zeldzaamste. De route voert bijna tweehonderd kilometer over natuurijs, langs elf steden in Friesland. De eerste officiële tocht was in 1909; sindsdien is hij in ruim honderd jaar maar vijftien keer verreden. De laatste keer was in 1997. Wie daarna geboren is, heeft de tocht dus nog nooit meegemaakt.\n\nDat komt doordat de eisen streng zijn. De tocht gaat niet door, tenzij het ijs op vrijwel de hele route zo'n vijftien centimeter dik is — dik genoeg om duizenden schaatsers te dragen. Daarvoor is ongeveer twee weken flinke vorst nodig, en zulke lange koude periodes komen in Nederland steeds minder vaak voor, omdat de winters gemiddeld warmer worden. Hoe langer het wachten duurt, hoe groter de verhalen worden. Wie erbij was, vertelt over bevroren wimpers, over onbekenden die elkaar door de nacht heen hielpen, en over de zingende menigte bij de finish.\n\nSommige mensen vinden dat de tocht voortaan op kunstijs gehouden moet worden; dan kan hij tenminste elk jaar doorgaan. Anderen vinden juist dat het wachten erbij hoort: een Elfstedentocht die je kunt plannen, zeggen zij, is geen echte Elfstedentocht meer. Over één ding is bijna iedereen het eens: als het ooit weer twee weken streng vriest, ligt half Nederland 's nachts wakker — en staat de andere helft langs het ijs.",
      vragen: [
        { q: "Welke zin uit de tekst is een mening?", options: ["Een Elfstedentocht die je kunt plannen, is geen echte Elfstedentocht meer", "De eerste officiële tocht was in 1909", "De route voert bijna tweehonderd kilometer langs elf steden", "De laatste tocht was in 1997"], answer: 0, type: "mening vs feit", uitleg: "Een feit kun je nakijken in een boek of archief: jaartallen, afstanden. Een mening vertelt wat iemand vindt — hier verraden de woorden 'zeggen zij' en 'geen échte' dat het om een opvatting gaat, niet om iets controleerbaars." },
        { q: "Hoe vaak is de tocht sinds 1909 verreden?", options: ["Vijftien keer", "Elf keer", "Ruim honderd keer", "Tweehonderd keer"], answer: 0, type: "detail opzoeken", uitleg: "Deze tekst is een getallen-doolhof: elf is het aantal stéden, ruim honderd het aantal járen, tweehonderd het aantal kilométers. Zoek de zin waar het gevraagde getal écht bij hoort voordat je kiest." },
        { q: "Waardoor wordt de tocht steeds zeldzamer?", options: ["De winters worden gemiddeld warmer, waardoor lange vorstperiodes bijna niet meer voorkomen", "Er zijn te weinig schaatsers die mee willen doen", "De elf steden willen de tocht niet meer organiseren", "Het ijs is tegenwoordig te dik geworden"], answer: 0, type: "oorzaak & gevolg", uitleg: "Volg het spoor van reden-woorden in alinea 2: 'dat komt doordat' en 'omdat de winters gemiddeld warmer worden'. De echte oorzaak zit dus in het weer, niet in de mensen of de steden." },
        { q: "Welke samenvatting past het best bij deze tekst?", options: ["De Elfstedentocht kan alleen na lange strenge vorst worden verreden; daardoor is hij zeldzaam en beroemd, en zijn de meningen over kunstijs verdeeld", "In 1997 werd de laatste Elfstedentocht verreden", "Deelnemers vertellen over bevroren wimpers en een zingende menigte", "Op kunstijs zou de tocht elk jaar kunnen doorgaan"], answer: 0, type: "samenvatten", uitleg: "Een samenvatting is de hele tekst in het klein: het wát (zeldzame tocht), het waaróm (strenge eisen, warmere winters) en de discussie (kunstijs of wachten). De andere drie zijn losse details — waar of niet, ze vatten niets samen." },
      ],
    },
  ],

  // ── TREDE 4 — 2 teksten van ±320-350 woorden, elk 5 vragen ───────
  [
    {
      titel: "De doos die de wereld veranderde",
      tekst: "Wie rond 1950 een lading spijkerbroeken van Amerika naar Europa wilde sturen, had vooral geduld nodig. In de haven werd alles stuk voor stuk aan boord getakeld: kisten, vaten, zakken en balen, in honderden verschillende maten. Tientallen havenwerkers waren dagen-, soms wekenlang bezig om één schip te laden. Al die tijd lag het schip stil, en een stilliggend schip kost geld. Bovendien verdween er onderweg nogal eens wat: een kist die 'per ongeluk' openging, een baal die spoorloos zoekraakte.\n\nEen Amerikaanse vrachtwagenondernemer bedacht in de jaren vijftig iets dat achteraf simpel klinkt: stop alle spullen in stalen dozen van precies dezelfde maat. Zo'n container gaat dicht bij de fabriek en pas weer open bij de ontvanger. Kranen kunnen de dozen razendsnel stapelen, en ze passen zonder gedoe op een schip, op een trein én op een vrachtwagen. Het laden van een schip duurde ineens geen weken meer, maar uren.\n\nDe gevolgen waren enorm, al zag bijna niemand ze aankomen. Vervoer over zee werd zó goedkoop dat het ineens loonde om producten aan de andere kant van de wereld te laten maken. Winkels kwamen vol te liggen met spullen uit verre landen. Ook de havens zelf veranderden: het sjouwwerk van duizenden havenarbeiders werd overgenomen door een handvol kraanmachinisten, en oude havens midden in de stad bleken te klein voor de nieuwe reuzenschepen.\n\nVandaag varen er miljoenen containers over de oceanen, gestapeld als kolossale blokkendozen. Kijk maar eens om je heen: grote kans dat je kleding, je telefoon en je fiets ooit in zo'n stalen doos de zee zijn overgestoken. De grootste veranderingen komen blijkbaar niet altijd van een schitterende machine — soms komen ze van een saaie stalen doos, en van iemand die anders durfde te denken over iets heel gewoons.",
      vragen: [
        { q: "Wat is de belangrijkste gedachte van deze tekst?", options: ["Eén simpel idee — dozen van precies dezelfde maat — maakte vervoer zo goedkoop dat het de wereldhandel veranderde", "Kranen kunnen containers razendsnel stapelen", "Rond 1950 waren havenwerkers soms wekenlang bezig met één schip", "Er varen tegenwoordig miljoenen containers over de oceanen"], answer: 0, type: "hoofdgedachte", uitleg: "De hoofdgedachte overspant álle alinea's: probleem (traag en duur), idee (de container) en gevolg (wereldhandel). De andere antwoorden staan letterlijk in de tekst, maar horen elk bij maar één alinea — te klein voor een hoofdgedachte." },
        { q: "Waarom loste de container ook het probleem op van spullen die zoekraakten? Combineer alinea 1 en 2.", options: ["De container gaat dicht bij de fabriek en pas open bij de ontvanger, dus niemand kan er onderweg iets uithalen", "Containers zijn te zwaar om te stelen", "Kraanmachinisten letten beter op dan havenwerkers", "In stalen dozen kan niets kapotgaan"], answer: 0, type: "informatie combineren", uitleg: "Het antwoord staat niet in één alinea. Alinea 1 noemt het probleem (kisten die 'per ongeluk' opengingen), alinea 2 de eigenschap die dat oplost (dicht bij de fabriek, pas open bij de ontvanger). Bij dit soort vragen moet je twee plekken in de tekst aan elkaar knopen." },
        { q: "'Bovendien verdween er onderweg nogal eens wat.' Wat doet het woord 'bovendien' hier?", options: ["Het voegt nóg een probleem toe aan de problemen die al genoemd zijn", "Het geeft een tegenstelling aan", "Het geeft de oorzaak van het stilliggen", "Het kondigt de oplossing aan"], answer: 0, type: "signaalwoord", uitleg: "'Bovendien' is een stapel-woord: er lag al iets op de stapel (traag laden, duur stilliggen) en daar komt iets bíj (spullen raken zoek). Zie je 'bovendien', tel dan mee hoeveel argumenten er al genoemd zijn." },
        { q: "Waardoor kwamen winkels vol te liggen met spullen uit verre landen?", options: ["Vervoer over zee werd zo goedkoop dat het voordelig werd om producten ver weg te laten maken", "Oude havens in de stad werden te klein", "Er kwamen duizenden havenarbeiders bij", "Schepen lagen weer wekenlang stil in de haven"], answer: 0, type: "oorzaak & gevolg", uitleg: "Lees de zin vóór het gevolg: goedkoop vervoer maakte ver-weg-productie lonend, en dáárdoor kwamen die spullen hier in de winkel. De andere antwoorden staan (bijna) letterlijk in de tekst, maar zijn gevolgen of onzin — geen oorzaak." },
        { q: "Waarom eindigt de schrijver met 'kijk maar eens om je heen'?", options: ["Om je te laten beseffen dat de container ook in jouw eigen leven een rol speelt", "Om je te vragen containers te gaan tellen", "Om te vertellen waar je het best een fiets kunt kopen", "Om te waarschuwen voor gevaarlijke reuzenschepen"], answer: 0, type: "doel van de schrijver", uitleg: "Een schrijver die 'jij' en 'je' gaat gebruiken, trekt de tekst jouw wereld in. Grote getallen over wereldhandel blijven anders ver weg; jouw eigen telefoon en fiets maken het ineens echt. Dat is een bewuste slot-truc." },
      ],
    },
    {
      titel: "Het balkon",
      tekst: "Mila speelt al vier jaar dwarsfluit, maar vanavond is alles anders: het is haar eerste optreden in de grote zaal, en oma zit niet op de eerste rij. Oma ligt sinds twee weken in het ziekenhuis — niets dat niet meer goed komt, zei de dokter, maar wel iets dat tijd nodig heeft. Bij elk optreden tot nu toe zat ze vooraan, met haar handtas op schoot en haar duim al omhoog voordat er ook maar één noot had geklonken. Zonder dat opgestoken duimpje, denkt Mila, weet ik niet eens hoe ik moet beginnen.\n\nIn de kleedkamer voelt ze haar vingers koud worden. Ze pakt haar telefoon en ziet een bericht van haar vader: 'Kijk straks even naar het balkon.' Meer staat er niet. Hoewel ze eigenlijk toonladders zou moeten oefenen, staart ze minutenlang naar die ene zin. Wat kán er op het balkon zijn? Een cadeau? Een grap? Als de zaalbel gaat, stopt ze de telefoon diep in haar tas en loopt ze op houten benen het podium op.\n\nHet licht is fel en warm; de zaal is één donker gat vol wachtende mensen. Mila zet de fluit aan haar lippen, kijkt nog één keer omhoog naar het balkon — en dan ziet ze het. Over de rand hangt een laken met grote, kleurige letters: ZET 'M OP, MILA. Ernaast staat haar vader, die een tablet omhooghoudt. Op het scherm, klein maar onmiskenbaar, zit oma rechtop in haar ziekenhuisbed. Haar duim is al omhoog.\n\nVan de muziek zelf weet Mila later weinig meer. Haar vader beweert dat ze nog nooit zo mooi heeft gespeeld, maar vaders vinden natuurlijk alles mooi. Wat ze zich wél herinnert: dat haar vingers ergens tijdens het eerste stuk warm werden, en dat het donkere gat ineens gewoon een zaal vol mensen was. En dat ze bij de laatste noot niet naar het publiek boog, maar naar het balkon.",
      vragen: [
        { q: "Hoe voelt Mila zich in de kleedkamer?", options: ["Zenuwachtig", "Boos op haar vader", "Rustig en goed voorbereid", "Blij dat oma er niet bij is"], answer: 0, type: "gevoel afleiden", uitleg: "Koude vingers, minutenlang naar één zin staren, 'op houten benen' het podium op — de schrijver zegt nergens 'zenuwachtig', maar laat het je via haar lichaam voelen. Zo werkt gevoel in verhalen: kijk naar wat het lichaam doet." },
        { q: "'Haar duim is al omhoog.' Waarom is dat zinnetje zo bijzonder? Combineer met alinea 1.", options: ["In alinea 1 staat dat oma bij elk optreden haar duim al omhoog had vóór de eerste noot — dat doet ze nu weer, vanuit het ziekenhuis", "Oma steekt haar duim op omdat het optreden voorbij is", "Haar vader had om een duim omhoog gevraagd", "Mila steekt zelf haar duim op naar het balkon"], answer: 0, type: "informatie combineren", uitleg: "Het zinnetje lijkt klein, maar het echoot een detail van drie alinea's terug: het vaste duimpje vóór de eerste noot. Alles is anders — en toch is het belangrijkste precies hetzelfde. Goede lezers herkennen zulke terugkerende details." },
        { q: "Waarom werden Mila's vingers tijdens het eerste stuk warm?", options: ["Ze werd rustiger doordat ze wist dat oma tóch meekeek", "Het podiumlicht was fel en warm", "Ze had haar handen in haar tas opgewarmd", "In de zaal stond de verwarming hoog"], answer: 0, type: "conclusie trekken", uitleg: "Koude vingers waren haar zenuwen; warme vingers zijn dus het wegzakken daarvan — vlak nadat ze oma op het scherm zag. Pas op: 'het licht is fel en warm' staat létterlijk in de tekst, maar dat verklaart haar vingers in alinea 4 niet. Letterlijk gevonden is niet hetzelfde als goed." },
        { q: "'Ze heeft nog nooit zo mooi gespeeld.' Wat is dit volgens de tekst?", options: ["Een mening van haar vader — de tekst zegt er zelf bij dat vaders alles mooi vinden", "Een feit dat iedereen kan nakijken", "Een mening van Mila zelf", "Een feit dat door de zaal is gecontroleerd"], answer: 0, type: "mening vs feit", uitleg: "Let op het werkwoord: haar vader 'beweert' het, en de verteller relativeert het meteen ('vaders vinden natuurlijk alles mooi'). Hoe mooi iemand speelt kun je bovendien niet objectief nameten — dat maakt het een mening, geen feit." },
        { q: "Welke samenvatting past het best bij dit verhaal?", options: ["Mila moet voor het eerst optreden zonder oma in de zaal, maar door een verrassing van haar vader kijkt oma vanuit het ziekenhuis tóch mee — en spelen lukt weer", "Mila's oma ligt twee weken in het ziekenhuis", "Op het balkon hangt een laken met grote, kleurige letters", "Mila speelt al vier jaar dwarsfluit en krijgt koude vingers"], answer: 0, type: "samenvatten", uitleg: "Een samenvatting van een verhaal heeft het probleem (oma mist), de wending (het balkon) én de afloop (spelen lukt weer) nodig. De andere drie kloppen letterlijk, maar het zijn losse foto's — een samenvatting is de hele film in het klein." },
      ],
    },
  ],
];

// Woordhulp versie D — alleen woorden die een kind van 11-13 écht kan missen,
// in kindertaal. NOOIT een woord waar een vraag over gaat (dat zou het
// antwoord verklappen). Sleutel = exact de vorm zoals hij in de tekst staat.
export const WOORDHULP_D = {
  "aswolk": "een reuzenwolk van as en stof die uit een vulkaan komt.",
  "balen": "een baal is een groot, stevig samengeperst pak, bijvoorbeeld van stof of wol.",
  "estafette": "een hardloop- of zwemwedstrijd in teams, waarbij je een stokje (of beurt) aan elkaar doorgeeft.",
  "gedaante": "een vorm of figuur waarvan je niet goed kunt zien wie of wat het precies is.",
  "getakeld": "takelen = met een kraan of met touwen en katrollen omhoog hijsen.",
  "harpoenen": "een harpoen is een soort speer aan een lijn, waarmee je iets kunt vastschieten en naar je toe kunt trekken.",
  "ingenieur": "iemand die geleerd heeft om machines, bruggen of andere techniek te bedenken en te bouwen.",
  "kieuwen": "de 'ademhaling' van een vis: spleten aan de zijkant van zijn kop waarmee hij zuurstof uit het water haalt.",
  "kolossale": "kolossaal = reusachtig groot.",
  "koraalrif": "een ondiepe plek in zee, gebouwd door piepkleine diertjes (koraal), waar heel veel vissen wonen.",
  "log": "groot, zwaar en onhandig om te verplaatsen.",
  "loonde": "lonen = de moeite waard zijn; je krijgt er meer voor terug dan het je kost.",
  "menigte": "een grote groep mensen dicht op elkaar.",
  "natuurijs": "ijs dat vanzelf op sloten en meren ontstaat als het vriest — dus niet gemaakt in een ijsbaan.",
  "nietsvermoedend": "zonder ook maar iets door te hebben van wat er gaat gebeuren.",
  "onmiskenbaar": "zó duidelijk dat je je niet kunt vergissen.",
  "toonladders": "rijtjes noten die je van laag naar hoog achter elkaar speelt, om te oefenen.",
  "uitwijken": "opzij gaan om een botsing te voorkomen.",
  "vrachtwagenondernemer": "iemand met een eigen bedrijf vol vrachtwagens die spullen vervoeren.",
};
