const styles = {
  app: {
    fontFamily: "'Nunito', sans-serif",
    minHeight: "100vh",
    background: "linear-gradient(160deg, #0f1729 0%, #162033 50%, #1a2744 100%)",
    maxWidth: 480,
    margin: "0 auto",
    position: "relative",
  },
  page: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  heroSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "48px 24px 32px",
    flex: 1,
    background: "radial-gradient(ellipse 110% 45% at 50% 12%, rgba(20,90,200,0.18) 0%, transparent 70%)",
  },
  logoContainer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  logoIcon: {
    fontSize: 48,
    animation: "float 3s ease infinite",
  },
  logoText: {
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 42,
    fontWeight: 700,
    margin: 0,
    letterSpacing: -1,
  },
  subtitle: {
    fontFamily: "'Nunito', sans-serif",
    color: "#8899aa",
    fontSize: 16,
    marginBottom: 32,
    textAlign: "center",
  },
  nameInput: {
    width: "100%",
    maxWidth: 360,
    marginBottom: 32,
  },
  inputLabel: {
    display: "block",
    fontWeight: 700,
    fontSize: 14,
    color: "#e0e6f0",
    marginBottom: 6,
    fontFamily: "'Fredoka', sans-serif",
  },
  textInput: {
    width: "100%",
    padding: "14px 16px",
    borderRadius: 14,
    border: "2px solid #2a3f5f",
    fontFamily: "'Nunito', sans-serif",
    fontSize: 16,
    fontWeight: 600,
    outline: "none",
    transition: "border-color 0.2s",
    background: "#1e2d45",
    boxSizing: "border-box",
    color: "#ffffff",
    WebkitTextFillColor: "#ffffff",
  },
  roleCards: {
    display: "flex",
    gap: 14,
    width: "100%",
    maxWidth: 360,
  },
  roleCard: {
    flex: 1,
    border: "none",
    borderRadius: 20,
    padding: "24px 16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    transition: "transform 0.2s, box-shadow 0.2s",
    boxShadow: "0 4px 20px rgba(0,0,0,0.4)",
    color: "#fff",
  },
  roleIcon: { fontSize: 36 },
  roleLabel: { fontFamily: "'Fredoka', sans-serif", fontSize: 16, fontWeight: 700 },
  roleDesc: { fontSize: 12, opacity: 0.9 },

  // Header
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 20px",
    background: "#1e2d45",
    borderBottom: "1px solid #e8eef5",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  headerBack: {
    background: "#162033",
    border: "none",
    borderRadius: 12,
    width: 40,
    height: 40,
    fontSize: 18,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
  },
  headerTitle: { fontFamily: "'Fredoka', sans-serif", fontSize: 22, margin: 0, color: "#e0e6f0" },
  headerSubtitle: { fontSize: 13, color: "#8899aa", margin: 0 },

  // Content
  content: { padding: "20px", flex: 1 },

  // Action buttons
  actionRow: { display: "flex", gap: 12, marginBottom: 24 },
  bigButton: {
    flex: 1,
    border: "none",
    borderRadius: 18,
    padding: "20px 16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    color: "#fff",
    fontFamily: "'Nunito', sans-serif",
    fontSize: 14,
    boxShadow: "0 4px 16px rgba(0,0,0,0.4)",
    transition: "transform 0.15s",
  },

  // Section title
  sectionTitle: {
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 18,
    color: "#e0e6f0",
    margin: "0 0 14px",
  },

  // Subject grid
  subjectGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 10,
    marginBottom: 24,
  },
  subjectCard: {
    border: "3px solid transparent",
    borderRadius: 16,
    padding: "16px 8px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    cursor: "pointer",
    transition: "all 0.2s",
    fontFamily: "'Nunito', sans-serif",
    background: "#1e2d45",
  },

  // Level grid
  levelGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginBottom: 24,
  },
  levelCard: {
    border: "3px solid transparent",
    borderRadius: 16,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    cursor: "pointer",
    transition: "all 0.2s",
    fontFamily: "'Nunito', sans-serif",
    background: "#1e2d45",
  },

  // Settings
  settingsGroup: {
    background: "#1e2d45",
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    boxShadow: "0 2px 12px rgba(0,0,0,0.3)",
  },
  settingLabel: {
    display: "block",
    fontWeight: 700,
    fontSize: 14,
    color: "#e0e6f0",
    marginBottom: 6,
    marginTop: 16,
    fontFamily: "'Fredoka', sans-serif",
  },
  slider: {
    width: "100%",
    accentColor: "#69f0ae",
    height: 6,
  },
  toggleRow: { display: "flex", alignItems: "center", gap: 14, marginTop: 20, cursor: "pointer", padding: "12px 0" },
  toggle: { width: 48, height: 26, borderRadius: 13, transition: "background 0.2s", flexShrink: 0, position: "relative" },
  toggleKnob: { width: 22, height: 22, borderRadius: 11, background: "#1e2d45", boxShadow: "0 1px 4px rgba(0,0,0,0.2)", position: "absolute", top: 2, transition: "transform 0.2s" },

  // Progress bar
  progressBar: {
    height: 6,
    background: "#2a3f5f",
    borderRadius: 3,
    marginBottom: 24,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: "linear-gradient(90deg, #FF6B35, #4ECDC4)",
    borderRadius: 3,
    transition: "width 0.4s ease",
  },

  // Step content
  stepContent: { animation: "slideUp 0.3s ease" },
  stepTitle: { fontFamily: "'Fredoka', sans-serif", fontSize: 20, color: "#e0e6f0", marginBottom: 16 },

  // Navigation
  navRow: { display: "flex", gap: 12, marginTop: 24, paddingBottom: 24 },
  backBtn: {
    background: "#162033",
    border: "none",
    borderRadius: 14,
    padding: "14px 24px",
    fontFamily: "'Nunito', sans-serif",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    color: "#8899aa",
  },
  nextBtn: {
    background: "linear-gradient(135deg, #00c853, #00e676)",
    color: "#fff",
    border: "none",
    borderRadius: 14,
    padding: "14px 28px",
    fontFamily: "'Nunito', sans-serif",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    boxShadow: "0 4px 16px rgba(255,107,53,0.3)",
  },

  // Lobby
  lobbyCard: {
    margin: "auto 20px",
    background: "#1e2d45",
    borderRadius: 24,
    padding: "32px 24px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    textAlign: "center",
  },
  lobbyLogo: { fontSize: 48, marginBottom: 8 },
  lobbyTitle: { fontFamily: "'Fredoka', sans-serif", fontSize: 28, margin: 0, color: "#e0e6f0" },
  lobbySubtitle: { color: "#8899aa", marginBottom: 16 },
  whatsappButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    width: "100%",
    background: "#25D366",
    color: "#fff",
    border: "none",
    borderRadius: 14,
    padding: "14px 20px",
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 4px 16px rgba(37,211,102,0.3)",
    marginBottom: 16,
    transition: "transform 0.15s",
  },
  codeDisplay: { display: "flex", justifyContent: "center", gap: 8, marginBottom: 20 },
  codeLetter: {
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 36,
    fontWeight: 700,
    color: "#ffffff",
    background: "#162033",
    padding: "10px 16px",
    borderRadius: 12,
    letterSpacing: 2,
  },
  lobbyInfo: { display: "flex", justifyContent: "center", gap: 10, marginBottom: 20, flexWrap: "wrap" },
  badge: {
    background: "#162033",
    padding: "6px 14px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 600,
  },
  playersSection: { textAlign: "left", marginBottom: 20 },
  playersList: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 8 },
  playerChip: {
    padding: "8px 16px",
    borderRadius: 20,
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "'Nunito', sans-serif",
  },
  startButton: {
    width: "100%",
    background: "linear-gradient(135deg, #00c853, #00a844)",
    color: "#fff",
    border: "none",
    borderRadius: 16,
    padding: "18px",
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 18,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 20px rgba(0,200,83,0.4)",
    marginBottom: 16,
  },
  waitingBox: { padding: 20, color: "#8899aa" },
  lobbyTip: { fontSize: 12, color: "#556677", fontStyle: "italic" },
  linkBtn: {
    background: "none",
    border: "none",
    color: "#8899aa",
    fontSize: 14,
    cursor: "pointer",
    marginTop: 8,
    fontWeight: 600,
    fontFamily: "'Nunito', sans-serif",
  },

  // Quiz card
  quizList: { display: "flex", flexDirection: "column", gap: 12 },
  quizCard: {
    background: "#1e2d45",
    borderRadius: 18,
    padding: 16,
    boxShadow: "0 2px 12px rgba(0,0,0,0.3)",
  },
  quizCardHeader: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 },
  quizTitle: { fontWeight: 700, fontSize: 15, color: "#e0e6f0" },
  quizMeta: { fontSize: 12, color: "#8899aa" },
  quizCardActions: { display: "flex", gap: 8 },
  smallButton: {
    background: "linear-gradient(135deg, #00c853, #00e676)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Nunito', sans-serif",
  },
  smallButtonAlt: {
    background: "#162033",
    color: "#8899aa",
    border: "none",
    borderRadius: 10,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Nunito', sans-serif",
  },
  deadlineBadge: {
    padding: "4px 10px",
    borderRadius: 10,
    color: "#fff",
    fontSize: 12,
    fontWeight: 800,
  },

  // Join section
  joinSection: {
    background: "#1e2d45",
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    boxShadow: "0 2px 12px rgba(0,0,0,0.3)",
  },
  codeInputRow: { display: "flex", gap: 10 },
  joinButton: {
    background: "linear-gradient(135deg, #00c853, #00e676)",
    color: "#fff",
    border: "none",
    borderRadius: 14,
    padding: "14px 20px",
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
    fontFamily: "'Nunito', sans-serif",
    fontSize: 14,
  },
  errorText: { color: "#e74c3c", fontSize: 13, marginTop: 6, fontWeight: 600 },

  // Assignment card
  assignmentCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "#1e2d45",
    borderRadius: 14,
    padding: "14px 16px",
    marginBottom: 10,
    boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
  },
  doneBadge: { fontSize: 13, fontWeight: 700 },

  // Recent card
  recentCard: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#1e2d45",
    borderRadius: 14,
    padding: "12px 16px",
    marginBottom: 8,
    boxShadow: "0 1px 6px rgba(0,0,0,0.3)",
  },
  scoreBadge: {
    padding: "4px 12px",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 800,
  },

  // Play quiz
  quizHeader: {
    display: "flex",
    justifyContent: "space-between",
    padding: "16px 20px 8px",
  },
  qCounter: {
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 16,
    fontWeight: 700,
    color: "#8899aa",
  },
  scoreDisplay: {
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 16,
    fontWeight: 700,
    color: "#00c853",
  },
  timerBar: {
    height: 8,
    background: "#2a3f5f",
    borderRadius: 4,
    margin: "0 20px 4px",
    overflow: "hidden",
  },
  timerFill: {
    height: "100%",
    borderRadius: 4,
  },
  questionCard: {
    margin: "0 20px",
    background: "#1e2d45",
    borderRadius: 24,
    padding: "28px 20px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    animation: "slideUp 0.3s ease",
  },
  questionText: {
    fontFamily: "'Fredoka', sans-serif",
    fontSize: 20,
    color: "#e0e6f0",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 1.4,
  },
  optionsGrid: { display: "flex", flexDirection: "column", gap: 10 },
  optionButton: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "18px 16px",
    minHeight: 56,
    borderRadius: 14,
    border: "2px solid",
    background: "#1e2d45",
    cursor: "pointer",
    fontFamily: "'Nunito', sans-serif",
    fontSize: 15,
    fontWeight: 700,
    transition: "all 0.2s",
    textAlign: "left",
    touchAction: "manipulation",
    WebkitTapHighlightColor: "transparent",
    userSelect: "none",
  },
  optionLetter: {
    width: 32,
    height: 32,
    borderRadius: 10,
    background: "rgba(255,255,255,0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 800,
    flexShrink: 0,
    color: "#e0e6f0",
  },

  // Results
  resultsCard: {
    margin: "32px 20px",
    background: "#1e2d45",
    borderRadius: 24,
    padding: "32px 24px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
  },
  scoreCircle: {
    width: 140,
    height: 140,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #00c853, #00a844)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 24px",
    boxShadow: "0 8px 24px rgba(0,200,83,0.4)",
  },
  scoreNumber: { fontFamily: "'Fredoka', sans-serif", fontSize: 36, fontWeight: 700, color: "#fff" },
  scoreDetail: { fontSize: 13, color: "rgba(255,255,255,0.85)" },
  resultDetails: {
    background: "#162033",
    borderRadius: 14,
    padding: 12,
  },
  resultRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 4px",
    borderBottom: "1px solid #e8eef5",
  },

  // Stats
  statsRow: { display: "flex", gap: 10, marginBottom: 24 },
  statCard: {
    flex: 1,
    background: "#1e2d45",
    borderRadius: 16,
    padding: "16px 12px",
    textAlign: "center",
    boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
  },
  statValue: { fontFamily: "'Fredoka', sans-serif", fontSize: 28, fontWeight: 700, color: "#e0e6f0" },
  statLabel: { fontSize: 12, color: "#8899aa", fontWeight: 600 },

  // Empty state
  emptyState: { textAlign: "center", padding: "48px 20px", color: "#8899aa" },

  // Subject progress
  subjectProgress: {
    background: "#1e2d45",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
  },
  progressBarSmall: {
    height: 8,
    background: "#2a3f5f",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFillSmall: {
    height: "100%",
    borderRadius: 4,
    transition: "width 0.6s ease",
  },
};

export default styles;
